---
title: "Exp333-334: 100 replicates of curiosity bandits, det v samp."
output: html_notebook
---

```{r, message=FALSE}
library(ggplot2)
library(patchwork)
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
library(MASS) 
library(scales)
library(patchwork)
options(scipen=1000000)

kl_divergence <- function(p, q) {
  sum(p * log(p/q))
}
```

# Load data
## Set a main path
```{r}
data_path <- "~/Code/infomercial/data/"
```

## Loader defs
```{r, message=FALSE}
file_names <- c("score_E", "action", "p_bests", "regret", "value_E", "ties", "state")
run_names <- 1:100

# ---
exp_name <- "exp329"
result329 <- NULL
for (run in run_names){
  runtmp <- read_csv(paste(data_path, 
                           exp_name, 
                           paste("run", run, sep=""), 
                           paste(file_names[1], "csv", sep="."), sep="/"))
  for (name in file_names[2:7]){
    tmp <- read_csv(paste(data_path, 
                          exp_name, 
                          paste("run", run, sep=""), 
                          paste(name, "csv", sep="."), sep="/"))  
    runtmp[[name]] <- tmp[[name]]
  }
  runtmp$run <- run
  runtmp$num_trials <- nrow(tmp)
  result329 <- bind_rows(result329, runtmp)  
  
}
result329$exp <- "Deterministic"
rm(runtmp, tmp)

# ---
exp_name <- "exp330"
result330 <- NULL
for (run in run_names){
  runtmp <- read_csv(paste(data_path, 
                           exp_name, 
                           paste("run", run, sep=""), 
                           paste(file_names[1], "csv", sep="."), sep="/"))
  for (name in file_names[2:7]){
    tmp <- read_csv(paste(data_path, 
                          exp_name, 
                          paste("run", run, sep=""), 
                          paste(name, "csv", sep="."), sep="/"))  
    runtmp[[name]] <- tmp[[name]]
  }
  runtmp$run <- run
  runtmp$num_trials <- nrow(tmp)
  result330 <- bind_rows(result330, runtmp)  
  
}
result330$exp <- "Stocastic"
rm(runtmp, tmp)

# --- Drop sto trials when det stopped
tmpfull <- NULL
for (n in run_names){
  tmp1 <- filter(result329, n == run)
  tmp2 <- filter(result330, n == run)
  tmp3 <- filter(tmp2, global_step < tmp1$num_trials[1])
  tmpfull <- bind_rows(tmpfull, tmp3)
}
result330 <- tmpfull
rm(tmpfull, tmp1, tmp2, tmp3)
```

# State dist
```{r, fig.height=0.8, fig.width=1.2}
result329 %>% 
  ggplot(aes(x=state)) +
  geom_bar(stat="count", fill="mediumorchid4") + 
  labs(x="State", title="Det.") +
  scale_x_continuous(breaks=c(1, 2), labels=c(1,2)) +
  theme_classic() -> p1

result330 %>% 
  ggplot(aes(x=state)) +
  geom_bar(stat="count", fill="plum4") + 
  labs(x="State", title="Sto.") +
  scale_x_continuous(breaks=c(1, 2), labels=c(1,2)) +
  theme_classic() -> p2

p1 | p2
```
# Action dist
```{r, fig.height=0.8, fig.width=1.6}
result329 %>% 
  ggplot(aes(x=action+1)) +
  geom_bar(stat="count", fill="mediumorchid4") + 
  labs(x="Action", title="Det.") +
  theme_classic() -> p1

result330 %>% 
  ggplot(aes(x=action+1)) +
  geom_bar(stat="count", fill="plum4") + 
  labs(x="Action", title="Sto.") +
  theme_classic() -> p2

p1 | p2
```
# Random examples actions
```{r, fig.height=2.4, fig.width=3}
result329 %>% 
  filter(run < 13) %>% 
  filter(global_step < 80) %>% 
  ggplot(aes(x=global_step, y=action+1)) +
  geom_point(size=0.6, color="mediumorchid4") + 
  geom_line(size=0.1, color="mediumorchid4") +
  labs(x="Trial", y="Action", title = "Det.") +
  scale_y_continuous(breaks=c(1, 4), labels=c(1,4)) +
  facet_wrap(.~run, ncol = 3) +
  theme_classic() + 
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.background = element_blank()) +
  theme(strip.text.x = element_blank()) ->
  p1
# print(p1)

result330 %>% 
  filter(run < 13) %>% 
  filter(global_step < 80) %>% 
  ggplot(aes(x=global_step, y=action+1)) +
  geom_point(size=0.6, color="plum4") + 
  geom_line(size=0.1, color="plum4") +
  labs(x="Trial", y="Action", title = "Sto.") +
  scale_y_continuous(breaks=c(1, 4), labels=c(1,4)) +
  facet_wrap(.~run, ncol = 3) +
  theme_classic() + 
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.background = element_blank()) +
  theme(strip.text.x = element_blank()) ->
  p2
# print(p2)

p1 / p2
```


# Trials
## Wilcox
```{r}
wilcox.test(x=log10(filter(result329, value_E > 0)$value_E), 
            y=log10(filter(result330, value_E > 0)$value_E))
```

## E dist
```{r, fig.height=0.8, fig.width=2.4}
full_join(result329, result330) %>% 
  filter(value_E > 0) %>%
  ggplot(aes(x=log10(value_E), fill=exp)) +
  geom_density(alpha=0.7, color=NA) +
  scale_fill_manual("", values=c("mediumorchid4", "plum4")) +
  scale_colour_grey() +
  labs(x="log E", y="Fraction") +
  theme_classic() -> p1
p1
```
## E boxplot
```{r, fig.height=0.6, fig.width=1.6}
full_join(result329, result330) -> 
  tmp
tmp %>%
  filter(value_E > 0) %>%
  ggplot(aes(x=exp, y=log10(value_E), fill=exp)) +
  geom_boxplot() +
  scale_fill_manual("", values=c("mediumorchid4", "plum4")) +
  theme_classic() +
  theme(legend.position = "none") +
  labs(y="log E") +
  coord_flip() ->
  p1
print(p1)

rm(tmp)
```
## E jitter
```{r, fig.height=0.6, fig.width=1.6}
full_join(result329, result330) -> 
  tmp
tmp %>% 
  filter(value_E > 0) %>%
  ggplot(aes(x=exp, y=log10(value_E), color=exp)) +
  geom_jitter(size=0.01, width = 0.2, alpha=0.1) +
  stat_summary(fun=median, color="black", alpha=0.9, size=0.5, shape="|") +
  theme_classic() +
  labs(y="Total E") +
  scale_color_manual("", values=c("mediumorchid4", "plum4")) +
  theme(
  legend.position = "none",
  strip.background = element_blank(),
  strip.text.x = element_blank()
  ) +
  coord_flip() ->
  p1
print(p1)
rm(tmp)
```

## Regret dist
```{r, fig.height=0.8, fig.width=1.6}
full_join(result329, result330) %>% 
  filter(value_E > 0) %>%
  ggplot(aes(x=log10(regret), fill=exp)) +
  geom_histogram(aes(y=..count../sum(..count..)), alpha=0.8,  color=NA) +
  scale_fill_manual("", values=c("mediumorchid4", "plum4")) +
  scale_colour_grey() +
  labs(x="Regret", y="Fraction") +
  theme_classic() -> p1
p1
```
# Totals
## Total E dist
```{r, fig.height=0.6, fig.width=1.6}
full_join(result329, result330) %>% 
  group_by(exp, run) %>% 
  filter(value_E > 0) %>%
  summarise(total_E = sum(score_E),
            total_regret = sum(regret)) %>% 
  ungroup() ->
  tmp
tmp %>% 
 ggplot(aes(x=total_E, fill=exp)) +
  geom_density(alpha=0.7, color=NA) +
  scale_fill_manual("", values=c("mediumorchid4", "plum4")) +
  scale_colour_grey() +
  labs(x="Total E", y="Fraction") +
  theme_classic() -> p1
p1
```
## Total E boxplot
```{r, fig.height=0.6, fig.width=1.6}
full_join(result329, result330) %>% 
  filter(value_E > 0) %>%
  group_by(exp, run) %>% 
  summarise(total_E = sum(score_E),
            total_regret = sum(regret)) %>% 
  ungroup() ->
  tmp
tmp %>%
  ggplot(aes(x=exp, y=total_E, fill=exp)) +
  geom_boxplot(notch = TRUE) +
  scale_fill_manual("", values=c("mediumorchid4", "plum4")) +
  theme_classic() +
  theme(legend.position = "none") +
  labs(y="Total E") +
  coord_flip() ->
  p1
print(p1)

rm(tmp)
```
## Total E jitter
```{r, fig.height=0.6, fig.width=1.2}
full_join(result329, result330) %>% 
  filter(value_E > 0) %>%
  group_by(exp, run) %>% 
  summarise(total_E = sum(score_E),
            total_regret = sum(regret)) %>% 
  ungroup() ->
  tmp

tmp %>% 
  ggplot(aes(x=exp, y=total_E, color=exp)) +
  geom_jitter(size=0.4, width = 0.2) +
  stat_summary(fun=median, color="black", alpha=0.9, size=1, shape="|") +
  theme_classic() +
  scale_color_manual("", values=c("mediumorchid4", "plum4")) +
  labs(y="Total E") +
  theme(strip.background = element_blank()) +
  theme(strip.text.x = element_blank()) +
  theme(legend.position = "none") +
  coord_flip() ->
  p1
print(p1)
```
## Total regret jitter
```{r, fig.height=0.4, fig.width=1.2}
full_join(result329, result330) %>% 
  group_by(exp, run) %>% 
  summarise(total_E = sum(score_E),
            total_regret = sum(regret)) %>% 
  ungroup() ->
  tmp

tmp %>% 
  ggplot(aes(x=exp, y=total_regret, color=exp)) +
  geom_jitter(size=0.4, width = 0.2) +
  stat_summary(fun=mean, color="black", alpha=0.9, size=0.7, shape="|") +
  theme_classic() +
  scale_color_manual("", values=c("mediumorchid4", "plum4")) +
  labs(y="Total regret") +
  theme(strip.background = element_blank()) +
  theme(strip.text.x = element_blank()) +
  theme(legend.position = "none") +
  coord_flip() ->
  p1
print(p1)
```
## Total regret bar
```{r, fig.height=0.6, fig.width=1}
full_join(result329, result330) %>% 
  # filter(global_step > 4) %>% # Drop first 4 rows -> E_0
  group_by(exp, run) %>% 
  summarise(total_E = sum(score_E),
            total_regret = sum(regret)) %>% 
  ungroup() ->
  tmp

tmp %>% 
  ggplot(aes(x=exp, y=total_regret, color=exp)) +
  geom_bar(stat = "identity", width=0.8) +
  scale_color_manual("", values=c("mediumorchid4", "plum4")) +
  theme_classic() +
  theme(legend.position = "none") +
  labs(y="Total regret") +
  coord_flip() ->
  p2
print(p2)

rm(tmp)
```
