---
title: "exp499-500 - BanditOneHigh4 - example param versus top1 param"
output: html_notebook
---

# Imports and paths
```{r, message=FALSE}
library(zoo)
library(ggplot2)
library(ggpubr)
library(patchwork)
# library(MASS) 
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
library(scales)
library(patchwork)
options(scipen=1000000)

source("utils.R")

# --- Main path to all data ---
data_path <- "/Volumes/Data/infomercial/data"
max_R <- 200
```

# Load data
## exp499 (non-opt)
```{r message=FALSE, cache=FALSE}
exp_name <- "exp499"
param_codes <- c(0)
run_codes <- 1:100
file_names <- c("score_E", 
                "score_R", 
                "action", 
                "p_bests", 
                "regret", 
                "value_E", 
                "value_R", 
                "ties", 
                "policy",
                "total_E", 
                "total_R",
                "total_regret")

result499 <- load_result(exp_name, param_codes, run_codes, file_names)
```

## exp500 (opt)
```{r message=FALSE, cache=TRUE}
exp_name <- "exp500"
param_codes <- c(0)
run_codes <- 1:100
file_names <- c("score_E", 
                "score_R", 
                "action", 
                "p_bests", 
                "regret", 
                "value_E", 
                "value_R", 
                "ties", 
                "policy",
                "total_E", 
                "total_R",
                "total_regret")

result500 <- load_result(exp_name, param_codes, run_codes, file_names)
```

# Plot
## Actions (all)
```{r, fig.width=1.2, fig.height=2.5}
num_episodes <- 200

result500 %>% 
  filter(global_step <= num_episodes) %>%
  ggplot(aes(x=global_step, y=action, color=factor(policy))) +
  geom_point(size=0.1, alpha=0.9, shape=".") +
  geom_line(size=0.1, alpha=1) +
  labs(x="Time", y="Action", title="Optimized") +
  lims(x=c(0, num_episodes)) +
  facet_wrap(run~.) +
  scale_color_manual("", values=c("mediumpurple4", "black")) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.text = element_text(size=3)) +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.1, "lines")) +
  theme(axis.ticks = element_blank()) + 
  theme(axis.text = element_blank()) -> a1

result499 %>% 
  filter(global_step <= num_episodes) %>%
  ggplot(aes(x=global_step, y=action, color=factor(policy))) +
  geom_point(size=0.1, alpha=0.9, shape=".") +
  geom_line(size=0.1, alpha=1) +
  labs(x="Time", y="Action", title="Non-optimal") +
  lims(x=c(0, num_episodes)) +
  facet_wrap(run~.) +
  scale_color_manual("", values=c("mediumpurple4", "black")) +
  theme_pubr(base_size = 6, legend = "none") +
  # theme(strip.text = element_blank()) +
  theme(strip.text = element_text(size=3)) +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.1, "lines")) +
  theme(axis.ticks = element_blank()) + 
  theme(axis.text = element_blank()) -> a2

a1 / a2 + plot_annotation(
      title="Optimizing boredom for reward collection", 
      subtitle = "100 simulated experiments",
      theme = theme_pubr(base_size = 8, legend = "none"))
```
## One example (up close)
```{r, fig.width=1.8, fig.height=2.3}
example <- 42


### non-optimal ----------------------------------------------------------------
eta <- 0.0001
result499 %>% 
  filter(run == example) %>% 
  ggplot(aes(x=global_step, y=factor(1-policy), color=factor(policy))) +
  geom_point(size=0.8, alpha=0.9) +
  labs(x="", y="", title="Non-optimal") +
  scale_y_discrete(
    breaks=c(0, 1), 
    labels=c("Exploit", "Explore")) +
  scale_color_manual("", values=c("darkorchid4", "black")) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.3, "lines")) -> p1

result499 %>% 
  filter(run == example) %>% 
  ggplot(aes(x=global_step, y=action+1, color=factor(policy))) +
  geom_point(size=0.6, alpha=0.9) +
  geom_line(size=0.1) +
  labs(x="", y="") +
  facet_wrap(policy~., ncol=1) +
  scale_color_manual("", values=c("darkorchid4", "black")) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(strip.text = element_blank()) +
  theme(panel.spacing = unit(0.5, "lines")) -> p2

result499 %>% 
  filter(run == example) %>% 
  ggplot(aes(x=global_step, y=score_R)) +
  geom_point(size=0.1, alpha=1, color="black") +
  geom_ribbon(aes(ymin=0, ymax=score_R), 
              size=0.6, alpha=0.1, fill="black", color=NA) +
  labs(x="", y="") +
  theme(strip.background = element_blank()) +
  theme_pubr(base_size = 6, legend = "none") -> p3

result499 %>% 
  filter(run == example) %>% 
  ggplot(aes(x=global_step, y=total_R/global_step)) +
  geom_line(size=0.6, alpha=1, color="black") +
  labs(x="", y="") +
  lims(y=c(0, 1)) +
  theme(strip.background = element_blank()) +
  theme_pubr(base_size = 6, legend = "none") -> p4

result499 %>% 
  filter(run == example) %>% 
  ggplot(aes(x=global_step, y=value_E)) +
  geom_line(size=0.6, color="darkorchid4") +
  geom_hline(yintercept = eta, color="darkorchid4", alpha=0.5, size=1) +
  scale_y_log10(limits=c(0.00001, 4)) +
  annotation_logticks(side="l", size=.1) + 
  labs(x="Time", y="") +
  theme(strip.background = element_blank()) +
  theme_pubr(base_size = 6, legend = "none") -> p5

c1 <- (p1 / p2 / p3 / p4 / p5) +
  plot_layout(
    heights=c(0.1, 0.3, 0.2, 0.2, 0.2), 
    ncol=)


### optimal ----------------------------------------------------------------------
eta <- 0.005 # taken from file

result500 %>% 
  filter(run == example) %>% 
  ggplot(aes(x=global_step, y=factor(1-policy), color=factor(policy))) +
  geom_point(size=0.8, alpha=0.9) +
  labs(x="", y="Policy", title="Optimized") +
  scale_y_discrete(
    breaks=c(0, 1), 
    labels=c("Exploit", "Explore")) +
  scale_color_manual("", values=c("darkorchid4", "black")) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.3, "lines")) -> p6

result500 %>% 
  filter(run == example) %>% 
  ggplot(aes(x=global_step, y=action+1, color=factor(policy))) +
  geom_point(size=0.6, alpha=0.9) +
  geom_line(size=0.1) +
  labs(x="", y="Action") +
  facet_wrap(policy~., ncol=1) +
  scale_color_manual("", values=c("darkorchid4", "black")) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(strip.text = element_blank()) +
  theme(panel.spacing = unit(0.5, "lines")) -> p7

result500 %>% 
  filter(run == example) %>% 
  ggplot(aes(x=global_step, y=score_R)) +
  geom_point(size=0.1, alpha=1, color="black") +
  geom_ribbon(aes(ymin=0, ymax=score_R), 
              size=0.6, alpha=0.1, fill="black", color=NA) +
  labs(x="", y="Reward") +
  theme(strip.background = element_blank()) +
  theme_pubr(base_size = 6, legend = "none") -> p8

result500 %>% 
  filter(run == example) %>% 
  ggplot(aes(x=global_step, y=total_R/global_step)) +
  geom_line(size=0.6, alpha=1, color="black") +
  labs(x="", y="Total reward") +
  lims(y=c(0, 1)) +
  theme(strip.background = element_blank()) +
  theme_pubr(base_size = 6, legend = "none") -> p9

result500 %>% 
  filter(run == example) %>% 
  ggplot(aes(x=global_step, y=value_E)) +
  geom_line(size=0.6, color="darkorchid4") +
  geom_hline(yintercept = eta, color="darkorchid4", alpha=0.5, size=1) +
  scale_y_log10(limits=c(0.00001, 4)) +
  annotation_logticks(side="l", size=.1) +
  labs(x="Time", y="Info. value") +
  theme(strip.background = element_blank()) +
  theme_pubr(base_size = 6, legend = "none") -> p10

c2 <- (p6 / p7 / p8 / p9 / p10) +
  plot_layout(
    heights=c(0.1, 0.3, 0.2, 0.2, 0.2), 
    ncol=1)

# --------------------------------------------------
c2 | c1 | plot_annotation(
      title="Optimizing boredom for reward collection", 
      subtitle = "Single example experiment",
      theme = theme_pubr(base_size = 8, legend = "none"))
```

# Average value (all)
```{r, fig.width=1.2, fig.height=1}
result499$boredom <- "Non-optimal"
result500$boredom <- "Optimized"
tmp <- bind_rows(result499, result500)

tmp$boredom <- factor(tmp$boredom, levels=c("Optimized", "Non-optimal"))

tmp %>% 
  ggplot(aes(x=global_step, y=total_R/global_step, color=boredom)) +
  geom_smooth() + 
  labs(x="", y="Reward") +
  scale_color_manual("Boredom", values=c("black", "darkgrey")) +
  theme_pubr(base_size = 6, legend = "right") +
  theme(strip.background = element_blank()) -> p1

tmp %>% 
  ggplot(aes(x=global_step, y=value_E, color=boredom)) +
  geom_smooth() +
  scale_y_log10() +
  annotation_logticks(side="l", size=.1) +
  labs(x="Time", y="Info. value") +
  scale_color_manual("", values=c("mediumpurple4", "mediumpurple3")) +
  theme_pubr(base_size = 6, legend = "right") +
  theme(strip.background = element_blank()) -> p2

p1 / p2 +plot_annotation(
      subtitle = "Value summary",
      theme = theme_pubr(base_size = 8, legend = "none"))

  # geom_point() 
  # facet_wrap(boredom~.)
```
