---
title: "exp456 - 457 : BanditOneHigh4 - top10 param runs"
output: html_notebook
---

# Imports and paths
```{r, message=FALSE}
library(zoo)
library(ggplot2)
library(ggpubr)
library(patchwork)
# library(MASS) 
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
library(scales)
library(patchwork)
options(scipen=1000000)

kl_divergence <- function(p, q) {
  sum(p * log(p/q))
}

load.result <- function(exp_name, param_codes, run_codes, file_names){
  num_files <- length(file_names)
  result <- NULL
  for (param in param_codes){
    for (run in run_codes) {
      runtmp <- read_csv(paste(data_path, 
                               exp_name, 
                               paste("param", param, sep=""), 
                               paste("run", run, sep=""), 
                               paste(file_names[1], "csv", sep="."), sep="/"))    
      for (name in file_names[2:num_files]){
        tmp <- read_csv(paste(data_path, 
                              exp_name, 
                              paste("param", param, sep=""), 
                              paste("run", run, sep=""), 
                              paste(name, "csv", sep="."), sep="/"))  
        runtmp[[name]] <- tmp[[name]]
      }
      runtmp$run <- run
      runtmp$param <- param
      result <- bind_rows(result, runtmp)  
    }
  }
  result
}

# --- Main path to all data ---
data_path <- "~/Code/infomercial/data/"
num_episodes <- 80
```

# exp456 - softmeta
## Load data
```{r message=FALSE, cache=TRUE}
exp_name <- "exp456"
param_codes <- 0:9
run_codes <- 1:10
file_names <- c("score_E", 
                "score_R", 
                "action", 
                "p_bests", 
                "regret", 
                "value_E", 
                "value_R", 
                "policy",
                "total_E", 
                "total_R",
                "total_regret")

result456 <- load.result(exp_name, param_codes, run_codes, file_names)
result456 %>% 
  group_by(param, run) %>% 
  summarise(
    total_E=last(total_E),
    total_R=last(total_R),
    total_regret=last(total_regret),
    value_E=last(value_E),
    value_R=last(value_R),
    p_bests=last(p_bests)
  ) %>% 
  ungroup() ->
summary456
```


# exp457 - meta
## Load data
```{r message=FALSE, cache=TRUE}
exp_name <- "exp457"
param_codes <- 0:9
run_codes <- 1:10
file_names <- c("score_E", 
                "score_R", 
                "action", 
                "p_bests", 
                "regret", 
                "value_E", 
                "value_R", 
                "policy",
                "total_E", 
                "total_R",
                "total_regret")

result457 <- load.result(exp_name, param_codes, run_codes, file_names)
result457 %>% 
  group_by(param, run) %>% 
  summarise(
    total_E=last(total_E),
    total_R=last(total_R),
    total_regret=last(total_regret),
    value_E=last(value_E),
    value_R=last(value_R),
    p_bests=last(p_bests)
  ) %>% 
  ungroup() ->
summary457
```


# exp402 - random
## Load data
```{r message=FALSE, cache=TRUE}
exp_name <- "exp402"
param_codes <- c(0)
run_codes <- 1:100
file_names <- c("score_R", 
                "action", 
                "p_bests", 
                "regret", 
                "total_R",
                "value_R",
                "total_regret")

result402 <- load.result(exp_name, param_codes, run_codes, file_names)
result402 <- filter(result402, global_step <= 80) 
result402 %>% 
  group_by(param, run) %>% 
  summarise(
    total_R=last(total_R),
    value_R=last(value_R),
    total_regret=last(total_regret),
    p_bests=last(p_bests)
  ) %>% 
  ungroup() ->
summary402
```


# Joint analysis
## Join data
```{r}
result456 %>% 
  dplyr::select(
    global_step, param, run, action, total_R, score_R,
    total_regret, p_bests) -> tmp1
result457 %>% 
  dplyr::select(
    global_step, param, run, action, total_R, score_R,
    total_regret, p_bests) -> tmp2
result402 %>% 
  dplyr::select(
    global_step, param, run, action, total_R, score_R,
    total_regret, p_bests) -> tmp3

tmp1$agent <- "Stochastic"
tmp2$agent <- "Deterministic"
tmp3$agent <- "Random"

result456_457 <- tmp1
result456_457 <- bind_rows(result456_457, tmp2)
result456_457 <- bind_rows(result456_457, tmp3)


# ---
summary456 %>% 
  dplyr::select(param, run, total_R, total_regret, p_bests) -> tmp1
summary457 %>% 
  dplyr::select(param, run, total_R, total_regret, p_bests) -> tmp2
summary402 %>% 
  dplyr::select(param, run, total_R, total_regret, p_bests) -> tmp3

tmp1$agent <- "Stochastic"
tmp2$agent <- "Deterministic"
tmp3$agent <- "Random"

summary456_457 <- tmp1
summary456_457 <- bind_rows(summary456_457, tmp2)
summary456_457 <- bind_rows(summary456_457, tmp3)
```

# Plot summary
```{r, fig.height=1.2, fig.width=1.4}
## Values
summary456_457 %>% 
  ggplot(aes(x=agent, y=total_R/num_episodes, color=agent)) +
  geom_jitter(size=0.01, alpha=0.9, width=0.2) +
  stat_summary(fun=median, alpha=1, size=0.8, shape="|") +
  scale_colour_manual("", values=c("darkorchid4", "black", "mediumpurple3")) +
  labs(y="Total reward", x="") +
  lims(y=c(0, 1)) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  coord_flip() +
  theme(panel.spacing = unit(1, "lines")) -> p1

summary456_457 %>% 
  ggplot(aes(x=agent, y=total_regret/num_episodes, color=agent)) +
  geom_jitter(size=0.01, alpha=0.9, width=0.2) +
  stat_summary(fun=median, alpha=1, size=0.8, shape="|") +
  scale_colour_manual("", values=c("darkorchid4", "black", "mediumpurple3")) +
  scale_y_log10() +
  labs(y="Total regret", x="") +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  coord_flip() +
  theme(panel.spacing = unit(1, "lines")) -> p2

summary456_457 %>% 
  ggplot(aes(x=agent, y=p_bests, color=agent)) +
  geom_jitter(size=0.05, alpha=0.9, width=0.2) +
  stat_summary(fun=median, alpha=1, size=0.8, shape="|") +
  scale_colour_manual("", values=c("darkorchid4", "black", "mediumpurple3")) +
  labs(y="Best choice", x="") +
  lims(y=c(0, 1)) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  coord_flip() +
  theme(panel.spacing = unit(1, "lines")) -> p3

p1 / p2 / p3 
```
# Plot values 
```{r, fig.height=1.1, fig.width=1.6}
result456_457 %>% 
  filter(run <= 10, param == 0) %>% 
  ggplot(aes(x=global_step, y=total_R/num_episodes, group=run, color=agent)) +
  geom_line(size=0.3, alpha=1) +
  labs(x="", y="Total reward") +
  facet_grid(.~agent) +
  scale_colour_manual("", 
                      values=c("darkorchid4", "black", "mediumpurple3")) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.5, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  # theme(plot.title = element_text(size = 6)) +
  theme(strip.text.y = element_blank()) +
  # theme(axis.text.x = element_blank()) +
  # theme(axis.text.y = element_blank()) +
  theme(axis.ticks.y = element_blank()) + 
  theme(legend.key.size = unit(0.2, "cm")) -> p1 

result456_457 %>% 
  filter(run <= 10, param == 0) %>% 
  ggplot(aes(x=global_step, y=total_regret/num_episodes, group=run, color=agent)) +
  geom_line(size=0.3, alpha=1) +
  scale_colour_manual("", 
                      values=c("darkorchid4", "black", "mediumpurple3")) +
  labs(x="Time", y="Total regret") +
  scale_y_log10() +
  annotation_logticks(sides = "l") +
  facet_grid(.~agent) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.5, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  # theme(plot.title = element_text(size = 6)) +
  theme(strip.text.y = element_blank()) +
  # theme(axis.text.x = element_blank()) +
  # theme(axis.text.y = element_blank()) +
  theme(axis.ticks.y = element_blank()) + 
  theme(legend.key.size = unit(0.2, "cm")) -> p2 

p1 / p2
```

# Plot actions 
```{r, fig.height=3, fig.width=2}
result456_457 %>% 
  filter(agent != "Random") %>% 
  filter(agent == "Deterministic") %>% 
  ggplot(aes(x=global_step, y=action, color=agent)) +
  geom_line(size=0.3, alpha=1) +
  scale_colour_manual("", 
                      values=c("darkorchid4")) +
  labs(x="Time", y="Action", title="Deterministic") +
  lims(x=c(0, 80)) +
  facet_grid(run~param) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.5, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text = element_blank()) +
  # theme(axis.text.x = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks.y = element_blank()) +
  theme(legend.key.size = unit(0.2, "cm")) -> p1

result456_457 %>% 
  filter(agent != "Random") %>% 
  filter(agent == "Stochastic") %>% 
  ggplot(aes(x=global_step, y=action, color=agent)) +
  geom_line(size=0.3, alpha=1) +
  scale_colour_manual("", 
                      values=c("mediumpurple3")) +
  labs(x="Time", y="Action", title="Stochastic") +
  facet_grid(run~param) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text = element_blank()) +
  theme(axis.text.x = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks = element_blank()) +
  theme(legend.key.size = unit(0.2, "cm")) -> p2

p1 / p2
```
# Plot actions and reward
```{r, fig.height=2, fig.width=2.6}
result456_457 %>% 
filter(agent != "Random") %>% 
  filter(agent == "Deterministic") %>% 
  ggplot(aes(x=global_step, y=action, color=factor(score_R), group=run)) +
  geom_point(size=0.1, alpha=1) +
  geom_line(size=0.01, alpha=1, color="black") +
  labs(x="Time", y="", title="Deterministic") +
  facet_grid(run~param) +
  scale_colour_manual("Reward", values=c("dark grey", "firebrick3")) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.1, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "right") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text = element_blank()) +
  theme(axis.text.x = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks = element_blank()) + 
  theme(legend.key.size = unit(0.2, "cm")) -> p1

result456_457 %>% 
filter(agent != "Random") %>% 
  filter(agent == "Stochastic") %>% 
  ggplot(aes(x=global_step, y=action, color=factor(score_R), group=run)) +
  geom_point(size=0.1, alpha=1) +
  geom_line(size=0.01, alpha=1, color="black") +
  labs(x="Time", y="", title="Stochastic") +
  facet_grid(run~param) +
  scale_colour_manual("Reward", values=c("dark grey", "firebrick3")) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.1, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "right") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text = element_blank()) +
  theme(axis.text.x = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks = element_blank()) + 
  theme(legend.key.size = unit(0.2, "cm")) -> p2

p1 / p2
```
# Plot rewards
```{r, fig.height=1.9, fig.width=0.5}
result456_457 %>% 
  filter(agent != "Random") %>%
  ggplot(aes(x=global_step, y=total_R/num_episodes, color=agent)) +
  geom_point(size=0.05, alpha=0.8, shape=".") +
  labs(x="Time", y="Total reward") +
  facet_wrap(run~., ncol=1) +
  lims(y=c(0,1)) +
  scale_colour_manual("Policy", values=c("darkorchid4", "mediumpurple3")) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.5, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text = element_blank()) +
  # theme(axis.text.x = element_blank()) +
  # theme(axis.text.y = element_blank()) +
  # theme(axis.ticks = element_blank()) + 
  theme(legend.key.size = unit(0.2, "cm")) 
```

# Plot regrets
```{r, fig.height=1.7, fig.width=0.6}
result456_457 %>% 
  filter(agent != "Random") %>% 
  ggplot(aes(x=global_step, y=total_regret/num_episodes, color=agent)) +
  geom_point(size=0.05, alpha=0.9, shape=".") +
  labs(x="Time", y="Total regret") +
  facet_wrap(run~., ncol=1) +
  scale_colour_manual("Policy", values=c("darkorchid4", "mediumpurple3")) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.4, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text = element_blank()) +
  # theme(axis.text.x = element_blank()) +
  # theme(axis.text.y = element_blank()) +
  # theme(axis.ticks = element_blank()) + 
  theme(legend.key.size = unit(0.2, "cm")) 
```

# Plot bests
```{r, fig.height=0.9, fig.width=1.8}
result456_457 %>% 
  filter(agent != "Random") %>% 
  ggplot(aes(x=global_step, y=p_bests, color=agent)) +
  geom_point(size=0.05, alpha=0.9, shape=".") +
  labs(x="Time", y="Best choice") +
  facet_wrap(run~., nrow=2) +
  scale_colour_manual("Policy", values=c("darkorchid4", "mediumpurple3")) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.1, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "right") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text = element_blank()) +
  theme(axis.text.x = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks = element_blank()) + 
  theme(legend.key.size = unit(0.2, "cm")) 
```
