---
title: "Analysis of exp674-678: tune runs for alternate memory models on BanditUniform121"
output: html_notebook
---

# Library
```{r, message=FALSE}
library(zoo)
library(ggplot2)
library(ggpubr)
library(patchwork)
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
# library(MASS) 
library(scales)
library(patchwork)
options(scipen=1000000)

# --- Main path to all data ---
data_path <- "~/Code/infomercial/data/"
```

# Load
```{r}
# What to load, and its names exp674-678
exp_names <-
  c("exp678",
    "exp674",
    "exp675",
    "exp676",
    "exp677")
agent_names <- c("KL/Prob",
                 "L1/Prob",
                 "L2/Entropy",
                 "L2/Rate",
                 "UCB/Count")
colors <- c("black",
            "grey",
            "darkgrey",
            "olivedrab4",
            "orange4")
# ---
results674_678 <- NULL

for (i in 1:length(exp_names)) {
  # Meta
  exp_name <- exp_names[i]
  agent_name <- agent_names[i]
  
  # Load
  result <-
    read_csv(paste(data_path, exp_name, "_sorted.csv", sep = ""),
             show_col_types = FALSE)
  
  result$exp <- exp_name
  result$agent <- agent_name
  
  # Save
  results674_678 <- bind_rows(results674_678, result)
}

# Order
results674_678$agent <- factor(results674_678$agent, levels = agent_names)
```


# Vis
## Ranked
```{r, fig.width=6, fig.height=2}
results674_678 %>%
  ggplot(aes(x = index, y = total_R, color = agent)) +
  geom_line(size = 2, alpha = 0.6) +
  labs(x = "Rank", y = "Total reward") +
  theme_classic() +
  theme(strip.background = element_blank()) +
  theme(legend.position = "nane") +
  theme(panel.spacing = unit(1, "lines")) +
  scale_x_continuous(breaks = c(0, 500, 1000)) +
  scale_y_continuous(breaks = c(1, 1000, 2000), limits = c(1, 2000)) +
  scale_color_manual("", values = colors) +
  facet_grid(. ~ agent) 
```

```{r, fig.width=6, fig.height=4}
results674_678 %>%
  ggplot(aes(x = index, y = total_R, color = agent)) +
  geom_line(size = 2, alpha = 0.6) +
  labs(x = "Rank", y = "Total reward") +
  theme_classic() +
  theme(strip.background = element_blank()) +
  scale_y_continuous(breaks = c(1, 1000, 2000), limits = c(1, 2000)) +
  theme(panel.spacing = unit(1, "lines")) +
  scale_x_continuous(breaks = c(0, 500, 1000)) +
  scale_color_manual("", values = colors) 
```

## Threshold
### Log
```{r, fig.width=10, fig.height=6}
results674_678 %>%
  filter(tie_threshold < 2) %>% 
  ggplot(aes(x = tie_threshold, y = total_R, color = agent)) +
  geom_point(size = 1, alpha = 0.6) +
  geom_vline(aes(xintercept=1.0), color="grey") +
  geom_vline(aes(xintercept=0.5), color="grey") +
  geom_vline(aes(xintercept=0.25), color="grey") +
  geom_vline(aes(xintercept=0.125), color="grey") +
  geom_vline(aes(xintercept=0.06), color="grey") +
  geom_vline(aes(xintercept=0.03), color="grey") +
  geom_vline(aes(xintercept=0.015), color="grey") +
  labs(x = "Boredom", y = "Total reward") +
  theme_classic() +
  theme(strip.background = element_blank()) +
  theme(legend.position = "nane") +
  theme(panel.spacing = unit(1, "lines")) +
  scale_x_log10() +
  scale_y_continuous(breaks = c(1, 1000, 2000), limits = c(1, 2000)) +
  scale_color_manual("", values = colors) +
  facet_wrap(. ~ agent) 
```

### Raw
```{r, fig.width=10, fig.height=6}
results674_678 %>%
  filter(tie_threshold < 2) %>% 
  ggplot(aes(x = tie_threshold, y = total_R, color = agent)) +
  geom_point(size = 1, alpha = 0.6) +
  geom_vline(aes(xintercept=1.0), color="grey") +
  geom_vline(aes(xintercept=0.5), color="grey") +
  geom_vline(aes(xintercept=0.25), color="grey") +
  geom_vline(aes(xintercept=0.125), color="grey") +
  geom_vline(aes(xintercept=0.06), color="grey") +
  geom_vline(aes(xintercept=0.03), color="grey") +
  geom_vline(aes(xintercept=0.015), color="grey") +
  labs(x = "Boredom", y = "Total reward") +
  theme_classic() +
  theme(strip.background = element_blank()) +
  theme(legend.position = "nane") +
  theme(panel.spacing = unit(1, "lines")) +
  scale_y_continuous(breaks = c(1, 1000, 2000), limits = c(1, 2000)) +
  scale_color_manual("", values = colors) +
  facet_wrap(. ~ agent) 
```
### Overlap 
```{r, fig.width=8, fig.height=4}
results674_678 %>%
  ggplot(aes(x = tie_threshold, y = total_R, color = agent)) +
  geom_point(size = 1, alpha = 0.6) +
  geom_vline(aes(xintercept=1.0), color="grey") +
  geom_vline(aes(xintercept=0.5), color="grey") +
  geom_vline(aes(xintercept=0.25), color="grey") +
  geom_vline(aes(xintercept=0.125), color="grey") +
  geom_vline(aes(xintercept=0.06), color="grey") +
  geom_vline(aes(xintercept=0.03), color="grey") +
  geom_vline(aes(xintercept=0.015), color="grey") +
  labs(x = "Boredom", y = "Total reward") +
  theme_classic() +
  theme(strip.background = element_blank()) +
  # theme(legend.position = "nane") +
  theme(panel.spacing = unit(1, "lines")) +
  scale_x_log10() +
  scale_y_continuous(breaks = c(1, 1000, 2000), limits = c(1, 2000)) +
  scale_color_manual("", values = colors) 
```

## Learning rate
### Raw
```{r, fig.width=10, fig.height=6}
results674_678 %>%
  filter(tie_threshold < 2) %>% 
  ggplot(aes(x = lr_R, y = total_R, color = agent)) +
  geom_point(size = 1, alpha = 0.6) +
  geom_vline(aes(xintercept=0.5), color="grey") +
  geom_vline(aes(xintercept=0.25), color="grey") +
  geom_vline(aes(xintercept=0.125), color="grey") +
  geom_vline(aes(xintercept=0.06), color="grey") +
  geom_vline(aes(xintercept=0.03), color="grey") +
  geom_vline(aes(xintercept=0.015), color="grey") +
  labs(x = "Learning rate", y = "Total reward") +
  theme_classic() +
  theme(strip.background = element_blank()) +
  theme(legend.position = "nane") +
  theme(panel.spacing = unit(1, "lines")) +
  scale_y_continuous(breaks = c(1, 1000, 2000), limits = c(1, 2000)) +
  scale_color_manual("", values = colors) +
  facet_wrap(. ~ agent) 
```

## Threshold v rate
```{r, fig.width=10, fig.height=6}
results674_678 %>%
  filter(tie_threshold < 2) %>%
  ggplot(aes(x = tie_threshold, y = lr_R, color = total_R)) +
  geom_point(size=4, alpha=0.6) +
  labs(x = "Boredom", y = "Learning rate") +
  theme_classic() +
  theme(strip.background = element_blank()) +
  theme(legend.position = "right") +
  theme(panel.spacing = unit(1, "lines")) +
  scale_color_viridis_b("Total reward") +
  facet_wrap(. ~ agent) 
```
