---
title: "Fig. exploration behavoir by strategy and task"
output: html_notebook
---

# Library
```{r, message=FALSE}
library(zoo)
library(ggplot2)
library(ggpubr)
library(patchwork)
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
# library(MASS) 
library(scales)
library(patchwork)
options(scipen=1000000)

# Load load_result and other helpful functions
source("utils.R")

# --- Main path to all data ---
data_path <- "/Volumes/Data/infomercial/data"
```

# Fig. Exploration 
## Load data (task 1)
```{r, message=FALSE}
# -------------------------------------------------------------
task_name <- "BanditOneHigh4"
task_code <- 2
num_episodes <- 2*50

# The overestimate due to E0
num_arms <- 4
E_bias <- log(num_arms) * num_arms 

exp_names <- c(
  "exp457", 
  "exp526", 
  "exp527", 
  "exp547", 
  "exp502",
  "exp525", 
  "exp501", 
  "exp504", 
  "exp503", 
  "exp539")

agent_names <- c(
  "Curiosity", 
  "Random/Greedy", 
  "Decay/Greedy", 
  "Random",
  "Reward", 
  "Bayesian", 
  "Novelty", 
  "Entropy", 
  "Count (EB)",
  "Count (UCB)"
)

class_names <- c(
  "Curiosity",
  "Random",
  "Random",
  "Random",
  "Extrinsic",
  "Intrinsic",
  "Intrinsic",
  "Intrinsic",
  "Intrinsic",
  "Intrinsic"
)

file_names <- c("action", 
                "total_R",
                "policy",
                "regret")

result_task1<- NULL
for(i in 1:length(exp_names)){
  exp_name <- exp_names[i]
  agent_name <- agent_names[i]
  class_name <- class_names[i]
  if (agent_name == "Random"){
    param_codes <- c(0)
    run_codes <- 1:100
  } else{
    param_codes <- 0:9
    run_codes <- 1:10
  }
  
  tmp <- load_result(exp_name, param_codes, run_codes, file_names, 
                     n_max=num_episodes+1)
  
  tmp %>% 
    filter(global_step <= num_episodes) -> tmp
  tmp$exp <- exp_name
  tmp$agent <- agent_name
  tmp$task <- task_name
  tmp$task_code <- task_code
  tmp$strategy <- class_name
  tmp$num_episodes <- num_episodes
  
  result_task1 <- bind_rows(result_task1, tmp)
}

# ----------------------------------------------------------------------------
# post-process
# Force order
result_task1$agent <- factor(result_task1$agent, levels=agent_names)

# Set 'policy' in agents without separate ones.
#
# 1. Policy does not exist as a field in any but curiosity
# it was filled with zero, which is misleading when I go to color by 
# policy. All strategies not curiosity should have a policy of 1
# to mean exploitation
result_task1$policy[result_task1$strategy != "Curiosity"] <- 1

# 2. To estimate exploration we use regret. Regret driven exploration we 
# denote as -1
result_task1$policy[result_task1$regret > 0] <- -1 
```

## Plot
```{r, fig.width=3.6, fig.height=2.1}
# Pick an exp to show actions for
r <- 6

# Plot actions
result_task1 %>% 
  filter(agent != "Random") %>% 
  filter(run == r) %>% 
  ggplot(aes(x=global_step, y=action+1)) + #, color=factor(policy))) +
  geom_point(size=0.1, alpha=0.9) +
  geom_line(size=0.1) +
  labs(x="Time", y="Choice") +
  scale_x_continuous(
    limits=c(0, num_episodes+(num_episodes*.1)), 
    breaks = c(0, num_episodes)) +
  scale_color_manual("", values=c("darkslategray4", "chartreuse4", "black")) +
  scale_y_continuous(limits=c(0.9, num_arms+.1), breaks = c(1, 4)) +
  facet_grid(param~agent) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(.2, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text.y = element_blank()) +
  theme(strip.text.x = element_text(hjust = -.1)) + 
  plot_annotation(
      title="Exploration strategies (task 1)", 
      subtitle = "Ten 'animals'",
      theme = theme_pubr(base_size = 8, legend = "none")) -> a1

# -
# Plot reward
# Show all total_R (all animals and exps)
result_task1 %>% 
  filter(agent != "Random") %>% 
  filter(global_step > 10) %>%
  filter(run == r) %>% 
  ggplot(aes(x=global_step, y=total_R/global_step, group=interaction(param,run))) +
  geom_line(size=0.4, alpha=0.8) +
  labs(x="Time", y="Reward") +
  scale_x_continuous(limits=c(0, 100), breaks = c(0, 100)) +
  scale_y_continuous(limits=c(-.1, 1.1), breaks = c(0, 1)) +
  facet_grid(agent~.) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(panel.spacing = unit(.2, "lines")) +
  theme(strip.text.y = element_text(angle=0, hjust = -.1)) + 
  theme(strip.background = element_blank()) -> r1

# -
exploration1 <- a1 + r1 +
  plot_layout(widths = c(0.9, 0.1)) + 
  plot_annotation(
      tag_levels="a", tag_suffix=".", 
      title="Exploration strategies", 
      subtitle = "Ten 'animals'",
      theme = theme_pubr(base_size = 8, legend = "none"))

print(exploration1)

# -
name <- "img/exploration1"
ggsave(paste(name, ".pdf", sep=""), plot=exploration1, width = 3.6*2, height = 2.1*2)
```