---
title: "Fig. Alt. memory for WSLS"
output: html_notebook
---

# Library
```{r, message=FALSE}
library(zoo)
library(ggplot2)
library(ggpubr)
library(patchwork)
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
# library(MASS) 
library(scales)
library(patchwork)
options(scipen=1000000)

# Load load_result and other helpful functions
source("utils.R")

# --- Main path to all data ---
data_path <- "~/Code/infomercial/data"
```

# Load data
## BanditOneHigh4
```{r, message=FALSE}
task_name <- "BanditOneHigh4"
task_code <- 2
num_episodes <- 200

exp_names <- c(
  "exp689", 
  "exp690", 
  "exp691", 
  "exp692",
  "exp693"
)

agent_names <- c(
  "Prob/L1", 
  "Entropy/L2", 
  "Rate/L2", 
  "Count/UCB",
  "Prob/KL"
)

class_names <- c(
  "Curiosity",
  "Curiosity",
  "Curiosity",
  "Curiosity",
  "Curiosity"
)

file_names <- c("action", 
                "total_R",
                "policy",
                "total_regret")

result689_693 <- NULL
for(i in 1:length(exp_names)){
  exp_name <- exp_names[i]
  agent_name <- agent_names[i]
  class_name <- class_names[i]
  if (agent_name == "Random"){
    param_codes <- c(0)
    run_codes <- 1:100
  } else{
    param_codes <- 0:9
    run_codes <- 1:10
  }
  
  tmp <- load_result(exp_name, param_codes, run_codes, file_names, 
                     n_max=num_episodes+1)
  
  tmp %>% 
    filter(global_step <= num_episodes) -> tmp
  tmp$exp <- exp_name
  tmp$agent <- agent_name
  tmp$task <- task_name
  tmp$task_code <- task_code
  tmp$strategy <- class_name
  tmp$num_episodes <- num_episodes
  
  result689_693 <- bind_rows(result689_693, tmp)
}

# ----------------------------------------------------------------------------
# post-process
# Force order
result689_693$agent <- factor(result689_693$agent, levels=rev(agent_names))

# Policy as factors
# Rename levels
result689_693$policy <- as.factor(result689_693$policy)
result689_693$policy <- recode_factor(result689_693$policy, `0`="explore", `1`="exploit")
```

## BanditUniform121
```{r, message=FALSE}
task_name <- "BanditUniform121"
task_code <- 6
num_episodes <- 121*50

exp_names <- c(
  "exp694", 
  "exp695", 
  "exp696", 
  "exp697",
  "exp698"
)

agent_names <- c(
  "Prob/L1", 
  "Entropy/L2", 
  "Rate/L2", 
  "Count/UCB",
  "Prob/KL"
)

class_names <- c(
  "Curiosity",
  "Curiosity",
  "Curiosity",
  "Curiosity",
  "Curiosity"
)

file_names <- c("action", 
                "total_R",
                "policy",
                "total_regret")

result694_698 <- NULL
for(i in 1:length(exp_names)){
  exp_name <- exp_names[i]
  agent_name <- agent_names[i]
  class_name <- class_names[i]
  tie_threshold <- boredoms[i]
  
  if (agent_name == "Random"){
    param_codes <- c(0)
    run_codes <- 1:100
  } else{
    param_codes <- 0:9
    run_codes <- 1:10
  }
  
  tmp <- load_result(exp_name, param_codes, run_codes, file_names, 
                     n_max=num_episodes+1)
  
  tmp %>% 
    filter(global_step <= num_episodes) -> tmp
  tmp$exp <- exp_name
  tmp$agent <- agent_name
  tmp$task <- task_name
  tmp$task_code <- task_code
  tmp$strategy <- class_name
  tmp$num_episodes <- num_episodes
  tmp$tie_threshold <- tie_threshold
  
  result694_698 <- bind_rows(result694_698, tmp)
}

# ----------------------------------------------------------------------------
# post-process
# Force order
result694_698$agent <- factor(result694_698$agent, levels=rev(agent_names))

# Policy as factors
# Rename levels
result694_698$policy <- as.factor(result694_698$policy)
result694_698$policy <- recode_factor(result694_698$policy, `0`="explore", `1`="exploit")

# Shift action
result694_698$action <- result694_698$action + 1
```


# Vis
## Fig. - Total reward
```{r, fig.width=3.5, fig.height=4.5}
# Create
max_R1 <- max(result689_693$total_R)

result689_693 %>%
  group_by(strategy, agent, param, run) %>%
  summarise(total_R = last(total_R),
            total_regret = last(total_regret)) %>%
  ungroup() ->
  tmp

tmp %>%
  mutate(color = ifelse(agent == "Prob/KL", "chartreuse4", "black")) %>%
  ggplot(aes(
    x = agent,
    y = total_R / max_R1,
    color = color
  )) +
  geom_boxplot(outlier.size = 0, width = 0.5) +
  labs(x = "",
       y = "Relative reward",
       subtitle = "Task 2 - Classic",
       tag = "a.") +
  scale_color_identity() +
  theme_pubr(base_size = 10, legend = "none") +
  theme(strip.background = element_blank()) +
  coord_flip() -> p3

# ---
max_R2 <- max(result694_698$total_R)

result694_698 %>%
  group_by(strategy, agent, param, run) %>%
  summarise(total_R = last(total_R),
            total_regret = last(total_regret)) %>%
  ungroup() ->
  tmp

tmp %>%
  mutate(color = ifelse(agent == "Prob/KL", "chartreuse4", "black")) %>%
  ggplot(aes(
    x = agent,
    y = total_R / max_R2,
    color = color
  )) +
  geom_boxplot(outlier.size = 0, width = 0.5) +
  labs(x = "",
       y = "Relative reward",
       subtitle = "Task 6 - High dimensional",
       tag = "b.") +
  scale_color_identity() +
  theme_pubr(base_size = 10, legend = "none") +
  theme(strip.background = element_blank()) +
  coord_flip() -> p4

alt1 <-
  (p3 / p4) + plot_annotation(title = "WSLS with alternate memory models")
print(alt1)

# Save
name <- "img/alt_memory1"
ggsave(
  paste(name, ".pdf", sep = ""),
  plot = alt1,
  width = 3.5,
  height = 4.5
)
```

