---
title: "Figures - reward consistency"
output: html_notebook
---

# Load data
## Cached?
```{r, eval=FALSE}
load(file="performance.RData")
```

## New
From indivdual notebooks, for all bandit tasks.
```{r, warning=FALSE, message=FALSE, eval=FALSE}
library(knitr)
source(knitr::purl("task2_results.Rmd", quiet=TRUE))
source(knitr::purl("task3_results.Rmd", quiet=TRUE))
source(knitr::purl("task4_results.Rmd", quiet=TRUE))
source(knitr::purl("task5_results.Rmd", quiet=TRUE))
source(knitr::purl("task6_results.Rmd", quiet=TRUE))
source(knitr::purl("task7_results.Rmd", quiet=TRUE))

# Save
save.image(file="performance.RData")
```

# Vis
Est. reward deviance on the last episode
## Overall
### Gather data
```{r, message=FALSE, warning=FALSE, fig.width=5, fig.height=5.0}
# norm, for each step get MAD
result_task2 %>%  
  filter(global_step > 10) %>%  # drop for num. stability
  group_by(strategy, agent, param, run, global_step) %>% 
  summarise(total_R = total_R/global_step) %>%  # norm 
  ungroup() %>% 
  group_by(strategy, agent, global_step) %>%
  summarise(var_R = mad(total_R)) %>%  # dev
  ungroup() -> tmp2

result_task3 %>%  
  filter(global_step > 10) %>% 
  group_by(strategy, agent, param, run, global_step) %>% 
  summarise(total_R = total_R/global_step) %>% 
  ungroup() %>% 
  group_by(strategy, agent, global_step) %>% 
  summarise(var_R = mad(total_R)) %>% 
  ungroup() ->
  tmp3

result_task4 %>%  
  filter(global_step > 10) %>% 
  group_by(strategy, agent, param, run, global_step) %>% 
  summarise(total_R = total_R/global_step) %>% 
  ungroup() %>% 
  group_by(strategy, agent, global_step) %>% 
  summarise(var_R = mad(total_R)) %>% 
  ungroup() -> 
  tmp4

result_task5 %>%  
  filter(global_step > 10) %>% 
  group_by(strategy, agent, param, run, global_step) %>% 
  summarise(total_R = total_R/global_step) %>% 
  ungroup() %>% 
  group_by(strategy, agent, global_step) %>% 
  summarise(var_R = mad(total_R)) %>% 
  ungroup() -> 
  tmp5

result_task6 %>%  
  filter(global_step > 10) %>% 
  group_by(strategy, agent, param, run, global_step) %>% 
  summarise(total_R = total_R/global_step) %>% 
  ungroup() %>% 
  group_by(strategy, agent, global_step) %>% 
  summarise(var_R = mad(total_R)) %>% 
  ungroup() -> 
  tmp6

result_task7 %>%  
  filter(global_step > 10) %>% 
  group_by(strategy, agent, param, run, global_step) %>% 
  summarise(total_R = total_R/global_step) %>% 
  ungroup() %>% 
  group_by(strategy, agent, global_step) %>% 
  summarise(var_R = mad(total_R)) %>% 
  ungroup() ->
  tmp7

bind_rows(tmp2, tmp3, tmp4, tmp5, tmp6, tmp7) ->
  tmp
```


### Scatter
```{r, message=FALSE, warning=FALSE, fig.width=5, fig.height=5.0}
# Threshold 
min_var <- 0.0075
tmp %>% 
  filter(var_R > min_var) %>% 
  filter(strategy == "E-explore") %>% 
  select(var_R) -> wsls_s
wsls_s <- median(wsls_s$var_R)
# Vis
tmp %>% 
  sample_n(nrow(tmp)/10) %>% 
  filter(var_R > min_var) %>%
  filter(strategy != "Random") %>% 
  ggplot(aes(x=agent, y=var_R)) +
  geom_jitter(size=.4, alpha=0.02) +
  stat_summary(fun.y = median, aes(color=strategy), size=1) +
  geom_hline(aes(yintercept=wsls_s), 
             color="chartreuse4",
             size=0.4) +
  labs(x="", y="Total reward") +
  theme_pubr(base_size = 10, legend = "none") +
  theme(panel.spacing = unit(.5, "lines")) +
  theme(strip.text.y = element_text(angle = 0, hjust = -.1)) +
  scale_color_manual("", values = c("black", "darkgrey", "chartreuse4")) +
  labs(
    x = "",
    y = "Normalized reward deviance",
    subtitle = "Overall",
    title="Consistency of reward collection"
  ) +
  # scale_y_continuous(limits = c(0, 0.01)) +
  coord_flip() ->
  consistency

print(consistency)

# -------------------------------------------------------------
# Save
name <- "img/consistency"
ggsave(paste(name, ".pdf", sep=""), plot=consistency, width = 5, height = 5)
```

### Boxplot
```{r, message=FALSE, warning=FALSE, fig.width=5, fig.height=5.0}
# Thresh 
min_var <- 0.0075
tmp %>% 
  filter(var_R > min_var) %>% 
  filter(strategy == "E-explore") %>% 
  select(var_R) -> wsls_s
wsls_s <- median(wsls_s$var_R)
# Vis
tmp %>% 
  sample_n(nrow(tmp)/10) %>% 
  filter(var_R > min_var) %>% 
  filter(strategy != "Random") %>% 
  ggplot(aes(x=agent, y=var_R, color=strategy)) +
  geom_boxplot() +
  # geom_jitter(size=.4, alpha=0.1) +
  # stat_summary(fun.y = median, aes(color=strategy), size=1) +
  geom_hline(aes(yintercept=wsls_s), 
             color="chartreuse4",
             size=0.4) +
  labs(x="", y="Total reward") +
  theme_pubr(base_size = 10, legend = "none") +
  theme(panel.spacing = unit(.5, "lines")) +
  theme(strip.text.y = element_text(angle = 0, hjust = -.1)) +
  scale_color_manual("", values = c("black", "darkgrey", "chartreuse4")) +
  labs(
    x = "",
    y = "Normalized reward deviance",
    subtitle = "Overall",
    title="Consistency of reward collection"
  ) +
  # scale_y_continuous(limits = c(0, 0.01)) +
  coord_flip() ->
  consistency

print(consistency)

# -------------------------------------------------------------
# Save
name <- "img/consistency"
ggsave(paste(name, ".pdf", sep=""), plot=consistency, width = 5, height = 5)
```
