---
title: "Fig - Curiosity"
output: html_notebook
---

# Library
```{r, message=FALSE}
library(zoo)
library(ggplot2)
library(ggpubr)
library(patchwork)
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
# library(MASS) 
library(scales)
library(patchwork)
options(scipen=1000000)

# Load load_result and other helpful functions
source("utils.R")

# --- Main path to all data ---
data_path <- "/Volumes/Data/infomercial/data"
```

# Load data
```{r message=FALSE, cache=TRUE}
# ---
exp_name <- "exp348"
num_episodes <- 320
num_arms <- 4

actor_names <- c("DeterministicActor", 
                 "SoftmaxActor")
better_names <- c("Deterministic", 
                  "Stochastic")

run_codes <- 1:100
file_names <- c("score_E", 
                "action", 
                "p_bests", 
                "regret", 
                "value_E", 
                "ties", 
                "state", 
                "total_E", 
                "total_regret")

# -------------------------------------------------------------------
# This data has a slightly different structure compared to the rest in 
# this notebook so we Need a custom load loop.
result348 <- NULL
for (i in 1:length(actor_names)){
  actor <- actor_names[i]
  better <- better_names[i]
  for (run in run_codes) {
    runtmp <- read_csv(paste(data_path, 
                             exp_name, 
                             actor,
                             paste("run", run, sep=""), 
                             paste(file_names[1], "csv", sep="."), sep="/"))    
    for (name in file_names[2:9]){
      tmp <- read_csv(paste(data_path, 
                            exp_name, 
                            actor,
                            paste("run", run, sep=""), 
                            paste(name, "csv", sep="."), sep="/"))  
      runtmp[[name]] <- tmp[[name]]
    }
    runtmp$run <- run
    runtmp$actor <- better
    runtmp$num_episodes <- nrow(tmp)
    result348 <- bind_rows(result348, runtmp)  
  }
}

# -----------------------------------------------------------------------
# Don't need wall time
result348[["t"]] <- NULL

# Remove E_bias
E_bias <- log(num_arms)
 
result348$total_E <- result348$total_E - (E_bias * num_arms)
result348$total_E[result348$total_E < 0] <- 0
# result348$score_E <- result348$score_E - E_bias
# result348$score_E[result348$score_E < 0] <- 0
# result348$value_E <- result348$value_E - E_bias
# result348$value_E[result348$value_E < 0] <- 0

# -----------------------------------------------------------------------
# Summarize the results 
result348 %>% 
  group_by(actor, run) %>% 
  summarise(
    total_E=last(total_E)/last(num_episodes),
    total_regret=last(total_regret)/last(num_episodes),
    num_explore=last(num_episodes)
  ) %>% 
  ungroup() ->
final348
final348$actor <- factor(
  final348$actor, levels=c("Stochastic", "Deterministic"))

final348 %>% 
  group_by(actor) %>% 
  summarise(
            median_E = median(total_E), 
            var_E = mad(total_E),
            median_num_explore = median(num_explore), 
            var_num_explore = mad(num_explore),
            median_regret = median(total_regret),
            var_regret = mad(total_regret)) %>% 
    ungroup() -> summary348
```

# Cleanup
```{r}
rm(tmp, runtmp, run, name, better, i, actor_names, actor, better_names,
   E_bias, file_names, , run_codes, n, num_arms, name)
```

# Fig. Curiosity
```{r, fig.width=2.4, fig.height=1.7}
r <- 1

# -------------------------------------------------------------------
result348 %>% 
  filter(actor == "Deterministic") %>% 
  filter(run == r) %>% 
  ggplot(aes(x=global_step, y=action+1, color=actor)) +
  lims(x=c(0, 320)) +
  geom_point(size=0.2, alpha=1) +
  geom_line(size=0.1) +
  labs(x="", y="Choice", title="Deterministic") +
  facet_wrap(.~run, ncol=1) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  scale_y_continuous(limits=c(0.8,4.5), breaks=c(1,4)) +
  scale_color_manual("Search", values=c("chartreuse4")) +
  theme(panel.spacing = unit(0.1, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text.y = element_text(angle = 0)) +
  theme(strip.text.x = element_blank()) +
  theme(legend.key.size = unit(0.2, "cm")) -> 
  c1a

result348 %>% 
  filter(actor == "Stochastic") %>% 
  filter(run == r) %>% 
  ggplot(aes(x=global_step, y=action+1, color=actor)) +
  lims(x=c(0, 320)) +
  geom_point(size=0.2, alpha=1) +
  geom_line(size=0.1) +
  scale_y_continuous(limits=c(0.8,4.5), breaks=c(1,4)) +
  labs(x="", y="", title="Stochastic") +
  facet_wrap(.~run, ncol=1) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  scale_color_manual("Search", values=c("black")) +
  theme(panel.spacing = unit(0.1, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(plot.title = element_text(size = 6)) +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(strip.text.y = element_text(angle = 0)) +
  theme(strip.text.x = element_blank()) +
  theme(legend.key.size = unit(0.2, "cm")) -> 
  c1b

result348 %>% 
  filter(run == r) %>% 
  filter(global_step > 5) %>%
  ggplot(aes(x=global_step, y=value_E, color=actor)) +
  geom_vline(aes(xintercept=min(num_episodes)), 
             color="black", linetype="dashed", alpha=0.9, size=0.2) +
  geom_line(size=0.8, alpha=1) +
  lims(x=c(0, 320)) +
  scale_y_log10() +
  annotation_logticks(size=0.1, sides = "l") +
  facet_wrap(.~actor) +
  labs(x="", y="Info. value") + 
  scale_color_manual("", values=c("chartreuse4", "black")) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.background = element_blank()) +
  theme(strip.text.x = element_blank()) -> 
  c1c

result348 %>% 
  filter(run == r) %>% 
  filter(global_step > 5) %>%
  ggplot(aes(x=global_step, y=regret, color=actor)) +
  geom_line(size=0.8, alpha=1) +
  lims(x=c(0, 320)) +
  facet_wrap(.~actor) +
  labs(x="Time", y="Regret") + 
  scale_color_manual("", values=c("chartreuse4", "black")) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.text.x = element_blank()) -> 
  c1d

sub1 <- (c1a + c1b) / c1c / c1d #+ 

# ------------------------------------------------------------------
summary348 %>% 
  ggplot(aes(x=actor, y=median_E, color=actor)) +
  geom_point(size=1.25, alpha=0.8) +
  geom_linerange(aes(
    ymin=((median_E+var_E)), 
    ymax=((median_E-var_E))), 
    alpha=0.4) +
  geom_hline(aes(yintercept=max(median_E)), 
             color="black",
             size=0.1) +
  labs(x="", y="Info. value") +
  scale_y_continuous(limits=c(0.0015, 0.0032), breaks = c(0.0015, 0.0015*2, 0.003)) +
  scale_color_manual("", values=c("black", "chartreuse4")) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  coord_flip() -> c2a

summary348 %>% 
  ggplot(aes(x=actor, y=median_regret, color=actor)) +
  geom_point(size=1.25, alpha=0.8) +
  geom_linerange(aes(
    ymin=((median_regret+var_regret)), 
    ymax=((median_regret-var_regret))), 
    alpha=0.4) +
  geom_hline(aes(yintercept=min(median_regret)),  
             color="black",
             size=0.1) +
  labs(x="", y="Regret") +
  scale_y_continuous(limits=c(0, 0.000045), breaks = c(0, 0.00004)) +
  scale_color_manual("", values=c("black", "chartreuse4")) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  coord_flip() -> c2b

summary348 %>% 
  ggplot(aes(x=actor, y=median_num_explore, color=actor)) +
  geom_point(size=1, alpha=0.8) +
  geom_linerange(aes(
    ymin=((median_num_explore+var_num_explore)), 
    ymax=((median_num_explore-var_num_explore))), 
    alpha=0.4) +
  # geom_hline(aes(yintercept=min(median_num_explore)),  
             # color="black",
             # size=0.1) +
  labs(x="", y="Num. explore") +
  scale_y_continuous(limits=c(80, 160), breaks = c(80, 120, 160)) +
  scale_color_manual("", values=c("black", "chartreuse4")) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  coord_flip() -> c2c


sub2 <- c2a / c2b / c2c

# -------------------------------------------------------------------------
curiosity1 <- (sub1 | sub2 + plot_spacer() + plot_spacer()) + 
  plot_layout(widths = c(0.7, 0.3)) +
    plot_annotation(
      tag_levels="a", tag_suffix=".", 
      title="Deterministic versus stochastic curiosity in a random world (task 0)", 
      theme = theme_pubr(base_size=8, legend="none"))
print(curiosity1)

name <- "img/curiosity"
ggsave(paste(name, ".pdf", sep=""), plot=curiosity1, width = 2.4*2, height = 1.7*2)
```

# Cleanup
```{r}
# -----------------------------------------------------------------------
## Cleanup
rm(sub1, sub2, c1a, c1b, c1c, c1d, c2a, c2b, c2c)
```
