---
title: "Exp346 - sto versus det, value and regret."
output: html_notebook
---

```{r, message=FALSE}
library(ggplot2)
library(ggpubr)
library(patchwork)
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
library(MASS) 
library(scales)
library(patchwork)
options(scipen=1000000)

kl_divergence <- function(p, q) {
  sum(p * log(p/q))
}
```

# Load data
## Set a main path
```{r}
data_path <- "~/Code/infomercial/data/"
```

## Loader defs
```{r, message=FALSE}
file_names <- c("score_E", "action", "p_bests", "regret", "value_E", "ties", "state", "total_E", "total_regret")
run_names <- c("DeterministicActor", "SoftmaxActor", "RandomActor")
better_names <- c("Deterministic", "Stochastic", "Random")

# ---
exp_name <- "exp346"
result346 <- NULL
for (i in 1:length(run_names)){
  run <- run_names[i]
  better <- better_names[i]
  runtmp <- read_csv(paste(data_path, 
                           exp_name, 
                           run,
                           paste(file_names[1], "csv", sep="."), sep="/"))
  for (name in file_names[2:9]){
    tmp <- read_csv(paste(data_path, 
                          exp_name, 
                          run,
                          paste(name, "csv", sep="."), sep="/"))  
    runtmp[[name]] <- tmp[[name]]
  }
  runtmp$exp <- better
  runtmp$num_trials <- nrow(tmp)
  result346 <- bind_rows(result346, runtmp) 
}

result346$exp <- factor(result346$exp, levels=c("Deterministic", "Stochastic", "Random"))
rm(tmp, runtmp, run, name)
```

# actions and total R
```{r, fig.width=3, fig.height=1.1}
# actions
result346 %>% 
  filter(exp != "Random") %>% 
  ggplot(aes(x=global_step, y=action+1, color=exp)) +
  # geom_point(size=1, shape=15) + 
  geom_line(size=1) +
  labs(x="Time", y="Room choice") +
  scale_y_continuous(breaks=c(1, 4), labels=c(1,4)) +
  facet_grid(exp~.) +
  theme_pubr(base_size = 10, legend = "none") +
  theme(strip.background = element_blank()) +
  scale_color_manual("", values=c("mediumorchid4", "paleturquoise4", "darkgrey")) +
  theme(panel.spacing = unit(0.6, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(strip.text.y = element_text(angle = 0)) +
  theme(strip.text.y = element_blank()) ->
  p1
# print(p1)

# total values time course
result346 %>% 
  filter(global_step > 10) %>%
  ggplot(aes(x=global_step, y=total_E - 1.38*4, color=exp)) +
  # geom_point(size=0.6) +
  geom_line(size=1) +
  labs(x="Time", y="Cumulative value") +
  theme_pubr(base_size = 10, legend = "none") +
  theme(strip.background = element_blank()) +
  scale_color_manual("Search", values=c("mediumorchid4", "paleturquoise4", "darkgrey")) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "right") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(strip.text.y = element_text(angle = 0)) +
  theme(strip.text.y = element_blank()) ->
  p2
# print(p2)

# ---
r1 <- p1 
  # plot_layout(widths = c(0.7, 0.3))
print(r1)
```

# values timecourse
```{r, fig.width=3, fig.height=1}
result346 %>% 
  filter(exp != "Random") %>% 
  filter(global_step > 10) %>% 
  ggplot(aes(x=global_step, y=log10(value_E), color=exp)) +
  geom_point(size=0.6) +
  geom_line(size=0.1) +
  labs(x="Time", y="log value") +
  theme_pubr(base_size = 10, legend = "none") +
  theme(strip.background = element_blank()) +
  facet_grid(.~exp) +
  scale_color_manual("", values=c("mediumorchid4", "paleturquoise4", "darkgrey")) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(strip.text.y = element_text(angle = 0)) +
  theme(strip.text.x = element_blank()) ->
  r2
print(r2)
```

# reget timecourse
```{r, fig.width=3, fig.height=0.6}
result346 %>% 
  filter(exp != "Random") %>% 
  filter(global_step > 10) %>%
  ggplot(aes(x=global_step, y=log10(regret), color=exp)) +
  geom_point(size=0.6) +
  geom_line(size=0.1) +
  # geom_smooth() +
  labs(x="Time", y="log regret") +
  facet_grid(.~exp) +
  theme_pubr(base_size = 10, legend = "none") +
  theme(strip.background = element_blank()) +
  scale_color_manual("", values=c("mediumorchid4", "paleturquoise4", "darkgrey")) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(strip.text.y = element_text(angle = 0)) +
  theme(strip.text.x = element_blank()) ->
  r3
# print(p1)
```

```{r, fig.width=3, fig.height=3}
r1 / r2 / r3 + 
  plot_layout(heights = c(0.5, 0.3, 0.2)) + 
   plot_annotation(tag_levels = 'a', 
                  tag_suffix = ".") + 
   plot_annotation(title="Deterministic versus stochastic curiosity", 
                   theme = theme_pubr(base_size = 12))
```



