---
title: "Exp326-327 - two examples of curiosity bandits"
output: html_notebook
---

```{r, message=FALSE}
library(ggplot2)
library(patchwork)
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
library(MASS) 
library(scales)
library(patchwork)
options(scipen=1000000)

kl_divergence <- function(p, q) {
  sum(p * log(p/q))
}
```

# Load data
## Set a main path
```{r}
data_path <- "~/Code/infomercial/data/"
```

## Loader defs
```{r, message=FALSE}
num_episodes <- 160

file_names <- c("score_E", "action", "p_bests", "regret", "value_E", "ties", "state")

exp_name <- "exp326"
result326 <- read_csv(paste(data_path, exp_name, paste(file_names[1], "csv", sep="."), sep="/"))
for(name in file_names[2:7]){
  tmp <- read_csv(paste(data_path, exp_name, paste(name, "csv", sep="."), sep="/"))
  result326[[name]] <- tmp[[name]]
}
result326$exp <- "Deterministic"

exp_name <- "exp327"
result327 <- read_csv(paste(data_path, exp_name, paste(file_names[1], "csv", sep="."), sep="/"))
for(name in file_names[2:7]){
  tmp <- read_csv(paste(data_path, exp_name, paste(name, "csv", sep="."), sep="/"))
  result327[[name]] <- tmp[[name]]
}
result327$exp <- "Stocastic"

result327 <- filter(result327, global_step < nrow(result326))
```

# States
```{r, fig.height=1, fig.width=1}
result326 %>% 
  filter(global_step < 40) %>% 
  ggplot(aes(x=global_step, y=action+1, color=factor(state))) +
  geom_point(size=1, alpha=0.6) + 
  scale_colour_manual(values=c("yellow", "blue")) +
  theme_classic() + 
  theme(legend.position = "none") -> p1

result327 %>% 
  filter(global_step < 40) %>% 
  ggplot(aes(x=global_step, y=action+1, color=factor(state))) +
  geom_point(size=1, alpha=0.6) + 
  scale_colour_manual(values=c("yellow", "blue")) +
  theme_classic() +
  theme(legend.position = "none") -> p2

p1 / p2
```

# Actions
```{r, fig.height=1.4, fig.width=1.2}
result326 %>% 
  ggplot(aes(x=global_step, y=action)) +
  geom_point() + 
  theme_classic() -> p1

result327 %>% 
  ggplot(aes(x=global_step, y=action)) +
  geom_point() + 
  theme_classic() -> p2

p1 / p2
```
```{r, fig.height=1.4, fig.width=0.6}
result326 %>% 
  ggplot(aes(x=action)) +
  geom_histogram() + 
  theme_classic() -> p1

result327 %>% 
  ggplot(aes(x=action)) +
  geom_histogram() + 
  theme_classic() -> p2

p1 / p2
```

## Ties
```{r, fig.height=1.4, fig.width=1.2}
result326 %>% 
  ggplot(aes(x=global_step, y=ties)) +
  geom_point() + 
  lims(x=c(0, num_episodes)) +
  theme_classic() -> p1

result327 %>% 
  ggplot(aes(x=global_step, y=ties)) +
  geom_point() + 
  lims(x=c(0, num_episodes)) +
  theme_classic() -> p2

p1 / p2
```
# Scores 
## Timecourse
```{r, fig.height=1.4, fig.width=2}
result326 %>% 
  ggplot(aes(x=global_step, y=value_E)) +
  geom_point() + 
  scale_y_log10() +
  facet_grid(.~action) +
  theme_classic() -> p1

result327 %>% 
  ggplot(aes(x=global_step, y=value_E)) +
  geom_point() + 
  scale_y_log10() +
  facet_grid(.~action) +
  theme_classic() -> p2

p1 / p2
```
## Score histograms
```{r, fig.height=1.4, fig.width=2.6}
result326 %>% 
  ggplot(aes(x=log10(score_E))) +
  geom_histogram() + 
  geom_vline(xintercept = log10(median(result326$score_E)), 
             color="red", alpha=0.6) +
  theme_classic() -> p1

result327 %>% 
  ggplot(aes(x=log10(score_E))) +
  geom_histogram() + 
  geom_vline(xintercept = log10(median(result327$score_E)), 
             color="red", alpha=0.6) +
  theme_classic() -> p2

p1 / p2
```
# Regret 
## Timecourse
```{r, fig.height=1.4, fig.width=1.2}
result326 %>% 
  ggplot(aes(x=global_step, y=regret)) +
  geom_point() + 
  lims(y=c(0, 0.005)) +
  theme_classic() -> p1

result327 %>% 
  ggplot(aes(x=global_step, y=regret)) +
  geom_point() + 
  lims(y=c(0, 0.005)) +
  theme_classic() -> p2

p1/p2
```

# Scores and regrets
## Totals
```{r, fig.height=0.9, fig.width=1.4}
full_join(result326, result327) %>% 
  group_by(exp) %>% 
  summarise(total_E = sum(score_E),
            total_regret = sum(regret)) %>% 
  ungroup() ->
  tmp

tmp %>% 
  ggplot(aes(x=exp, y=total_E - 4*1.3862943611)) +
  geom_bar(stat = "identity", width=0.8) +
  theme_classic() +
  labs(y="Total E") +
  coord_flip() ->
  p1

tmp %>% 
  ggplot(aes(x=exp, y=total_regret)) +
  geom_bar(stat = "identity", width=0.8) +
  theme_classic() +
  labs(y="Total regret") +
  coord_flip() ->
  p2

p1 / p2 

rm(tmp)
```
## Totals, by action
```{r, fig.height=1.2, fig.width=2.6}
full_join(result326, result327) %>% 
  group_by(exp, action) %>% 
  summarise(total_E = sum(score_E),
            total_regret = sum(regret)) %>% 
  ungroup() ->
  tmp

tmp %>% 
  ggplot(aes(x=exp, y=total_E - 1.3862943611)) +
  geom_bar(stat = "identity", width=0.8) +
  theme_classic() +
  labs(y="Total E") +
  facet_grid(.~action) +
  coord_flip() ->
  p1

tmp %>% 
  ggplot(aes(x=exp, y=total_regret)) +
  geom_bar(stat = "identity", width=0.8) +
  theme_classic() +
  facet_grid(.~action) +
  coord_flip() ->
  p2

p1 / p2 

rm(tmp)
```
## Totals, by state
```{r, fig.height=1.2, fig.width=2.6}
full_join(result326, result327) %>% 
  group_by(exp, state) %>% 
  summarise(total_E = sum(score_E),
            total_regret = sum(regret)) %>% 
  ungroup() ->
  tmp

tmp %>% 
  ggplot(aes(x=exp, y=total_E - 1.3862943611)) +
  geom_bar(stat = "identity", width=0.8) +
  theme_classic() +
  labs(y="Total E") +
  facet_grid(.~state) +
  coord_flip() ->
  p1

tmp %>% 
  ggplot(aes(x=exp, y=total_regret)) +
  geom_bar(stat = "identity", width=0.8) +
  theme_classic() +
  facet_grid(.~state) +
  coord_flip() ->
  p2

p1 / p2 

rm(tmp)
```
