---
title: "Exp351 - Stochastic curiosity in a random world, v2"
output: html_notebook
---

```{r, message=FALSE}
library(ggplot2)
library(patchwork)
library(tidyr)
library(dplyr)
library(ggpubr)
library(ggthemes)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
library(MASS) 
library(scales)
library(patchwork)
options(scipen=1000000)

kl_divergence <- function(p, q) {
  sum(p * log(p/q))
}
```

# Load data
## Set a main path
```{r}
data_path <- "~/Code/infomercial/data/"
```

## Load
```{r, message=FALSE}
file_names <- c("score_E", "action", "p_bests", "regret", "value_E", "ties")
run_names <- c("run1", "run2", "run3", "run4", "run5", "run6")

exp_name <- "exp351"
result351 <- NULL
for (run in run_names){
  runtmp <- read_csv(paste(data_path, exp_name, run, paste(file_names[1], "csv", sep="."), sep="/"))
  for (name in file_names[2:6]){
    tmp <- read_csv(paste(data_path, exp_name, run, paste(name, "csv", sep="."), sep="/"))  
    runtmp[[name]] <- tmp[[name]]
  }
  runtmp$run <- run
  result351 <- bind_rows(result351, runtmp)  
}
rm(runtmp, tmp)
```

## Plot
```{r, fig.height=1.7, fig.width=1.8}
result351 %>% 
  filter(global_step < 40) %>% 
  ggplot(aes(x=global_step, y=action+1)) +
  geom_point(size=0.5, shape=15, color="mediumorchid4") + 
  geom_line(size=.1, color="mediumorchid4") +
  labs(x="Time", y="Room choice") +
  scale_y_continuous(breaks=c(1, 4), labels=c(1,4)) +
  facet_wrap(.~run, ncol=1) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(plot.title = element_text(vjust=3, hjust = 0.0, size=8)) +
  theme(panel.spacing = unit(0.75, "lines")) +
  theme(strip.background = element_blank()) +
  theme(strip.text.x = element_blank()) +
  theme(strip.text.y = element_text(angle = 0)) -> 
  p1
# plot(p1)

result351 %>% 
  filter(global_step < 40) %>% 
  ggplot(aes(x=action+1)) +
  geom_bar(width=0.9) + 
  labs(x="Room", y="Relative count", title="40 steps") +
  theme_pubr(base_size=6, legend = "none")  +
  theme(text = element_text(color = "black")) +
  theme(strip.text.y = element_text(angle = 0)) +
  theme(strip.background = element_blank()) +
  theme(strip.text.y = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks.y = element_blank()) +
  theme(plot.title = element_text(vjust = -2, hjust = 0, size = 6)) +
  facet_grid(run~.) -> 
  p2
# print(p2)

result351 %>% 
  ggplot(aes(x=action+1)) +
  geom_bar(width=0.9) + 
  labs(x="Room", y="", title="All steps") +
  theme_pubr(base_size=6, legend = "none")  +
  theme(text = element_text(color = "black")) +
  theme(strip.text.y = element_text(angle = 0)) +
  theme(strip.background = element_blank()) +
  # theme(strip.text.y = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks.y = element_blank()) +
  theme(plot.title = element_text(vjust = -2, hjust = 0.0, size = 6)) +
  facet_grid(run~.) -> 
  p3
# print(p3)

(p1 + p2 + p3) + 
  plot_layout(widths = c(0.5, 0.25, 0.25)) +
  plot_annotation(title="Stochastic curiosity in a random world", 
                   theme = theme_pubr(base_size = 8)) +
  plot_annotation(tag_levels = 'a',
                  tag_suffix = ".")
  
```
