---
title: "Exp340 versus 342 - with and without initial values in M"
output: html_notebook
---

```{r, message=FALSE}
library(ggplot2)
library(patchwork)
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
library(MASS) 
library(scales)
library(patchwork)
options(scipen=1000000)

kl_divergence <- function(p, q) {
  sum(p * log(p/q))
}
```

# Load data
## Set a main path
```{r}
data_path <- "~/Code/infomercial/data/"
```

## Loader defs
```{r, message=FALSE}
file_names <- c("score_E", "action", "p_bests", "regret", "value_E", "ties", "state")
run_names <- c("DeterministicActor", "SoftmaxActor", "ThresholdActor", "RandomActor")

# ---
exp_name <- "exp340"
result340 <- NULL
for (run in run_names){
  runtmp <- read_csv(paste(data_path, 
                           exp_name, 
                           run,
                           paste(file_names[1], "csv", sep="."), sep="/"))
  for (name in file_names[2:7]){
    tmp <- read_csv(paste(data_path, 
                          exp_name, 
                          run,
                          paste(name, "csv", sep="."), sep="/"))  
    runtmp[[name]] <- tmp[[name]]
  }
  runtmp$exp <- run
  runtmp$num_trials <- nrow(tmp)
  result340 <- bind_rows(result340, runtmp) 
}

# ---
exp_name <- "exp342"
result342 <- NULL
for (run in run_names){
  runtmp <- read_csv(paste(data_path, 
                           exp_name, 
                           run,
                           paste(file_names[1], "csv", sep="."), sep="/"))
  for (name in file_names[2:7]){
    tmp <- read_csv(paste(data_path, 
                          exp_name, 
                          run,
                          paste(name, "csv", sep="."), sep="/"))  
    runtmp[[name]] <- tmp[[name]]
  }
  runtmp$exp <- run
  runtmp$num_trials <- nrow(tmp)
  result342 <- bind_rows(result342, runtmp) 
}

# ---
rm(tmp, runtmp, run, name)
```

# actions
```{r, fig.width=3.6, fig.height=1.6}
result340 %>% 
  ggplot(aes(x=global_step, y=action+1, color=exp)) +
  geom_point(size=0.6) + 
  geom_line(size=0.1) +
  labs(x="Trial", y="Arm", title="Intial knowledge") +
  scale_y_continuous(breaks=c(1, 4), labels=c(1,4)) +
  facet_grid(exp~.) +
  theme_classic() + 
  scale_color_manual("", values=c("mediumorchid4", "grey", "plum4",  "paleturquoise4")) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(strip.text.y = element_blank()) +
  theme(strip.text.x = element_blank()) ->
  p1

result342 %>% 
  ggplot(aes(x=global_step, y=action+1, color=exp)) +
  geom_point(size=0.6) + 
  geom_line(size=0.1) +
  labs(x="Trial", y="", title="No intial") +
  scale_y_continuous(breaks=c(1, 4), labels=c(1,4)) +
  facet_grid(exp~.) +
  theme_classic() + 
  scale_color_manual("", values=c("mediumorchid4", "grey", "plum4",  "paleturquoise4")) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(strip.text.y = element_text(angle = 0)) +
  theme(strip.text.x = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(strip.text.x = element_blank()) ->
  p2

pa <- p1 + p2
print(pa)
```

# values
```{r, fig.width=3.6, fig.height=1.6}
result340 %>% 
  ggplot(aes(x=global_step, y=log10(value_E), color=exp)) +
  geom_point(size=0.6) + 
  geom_line(size=0.1) +
  labs(x="Trial", y="E") +
  facet_grid(exp~.) +
  theme_classic() + 
  scale_color_manual("", values=c("mediumorchid4", "grey", "plum4",  "paleturquoise4")) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(strip.text.y = element_blank()) +
  theme(strip.text.x = element_blank()) ->
  p1 

result342 %>% 
  ggplot(aes(x=global_step, y=log10(value_E), color=exp)) +
  geom_point(size=0.6) + 
  geom_line(size=0.1) +
  labs(x="Trial", y="") +
  facet_grid(exp~.) +
  theme_classic() + 
  scale_color_manual("", values=c("mediumorchid4", "grey", "plum4",  "paleturquoise4")) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(strip.text.y = element_text(angle = 0)) +
  theme(axis.text.y = element_blank()) +
  theme(strip.text.x = element_blank()) ->
  p2

pb <- p1 + p2
print(pb)
```


## E boxplot
```{r, fig.height=0.8, fig.width=3.6}
result340 %>%
  filter(value_E > 0) %>%
  ggplot(aes(x=exp, y=log10(value_E), fill=exp)) +
  geom_boxplot(notch = TRUE) +
  scale_fill_manual("", values=c("mediumorchid4", "grey", "plum4",  "paleturquoise4")) +
  theme_classic() +
  theme(legend.position = "none") +
  labs(y="log E") +
  coord_flip() ->
  p1

result342 %>%
  filter(value_E > 0) %>%
  ggplot(aes(x=exp, y=log10(value_E), fill=exp)) +
  geom_boxplot(notch = TRUE) +
  scale_fill_manual("", values=c("mediumorchid4", "grey", "plum4",  "paleturquoise4")) +
  theme_classic() +
  theme(legend.position = "none") +
  theme(axis.text.y = element_blank()) +
  labs(y="log E", x="") +
  coord_flip() ->
  p2

pc <- p1 + p2
print(pc)
```
## E jitter
```{r, fig.height=0.8, fig.width=3.6}
result340 %>% 
  filter(value_E > 0) %>%
  ggplot(aes(x=exp, y=value_E, color=exp)) +
  geom_jitter(size=0.1, width = 0.2, alpha=0.9) +
  stat_summary(fun=mean, color="black", alpha=1, size=0.6, shape="|") +
  theme_classic() +
  labs(y="E") +
  scale_y_log10() +
  scale_color_manual("", values=c("mediumorchid4", "grey", "plum4",  "paleturquoise4")) +
  theme(
  legend.position = "none",
  strip.background = element_blank(),
  strip.text.x = element_blank()
  ) +
  coord_flip() ->
  p1

result342 %>% 
  filter(value_E > 0) %>%
  ggplot(aes(x=exp, y=value_E, color=exp)) +
  geom_jitter(size=0.1, width = 0.2, alpha=0.9) +
  stat_summary(fun=mean, color="black", alpha=1, size=0.6, shape="|") +
  theme_classic() +
  labs(y="E") +
  scale_y_log10() +
  scale_color_manual("", values=c("mediumorchid4", "grey", "plum4",  "paleturquoise4")) +
  theme(
  legend.position = "none",
  strip.background = element_blank(),
  strip.text.x = element_blank()
  ) +
  coord_flip() ->
  p2

p1 + p2
```

## Regret boxplot
```{r, fig.height=0.8, fig.width=3.6}
result340 %>%
  ggplot(aes(x=exp, y=log10(regret), fill=exp)) +
  geom_boxplot(notch = TRUE) +
  scale_fill_manual("", values=c("grey", "plum4",  "paleturquoise4")) +
  theme_classic() +
  theme(legend.position = "none") +
  labs(y="log Regret") +
  coord_flip() ->
  p1

result342 %>%
  ggplot(aes(x=exp, y=log10(regret), fill=exp)) +
  geom_boxplot(notch = TRUE) +
  scale_fill_manual("", values=c("grey", "plum4",  "paleturquoise4")) +
  theme_classic() +
  theme(legend.position = "none") +
  theme(axis.text.y = element_blank()) +
  labs(y="log Regret", x="") +
  coord_flip() ->
  p2

pd <- p1 + p2
print(pd)
```
## Regret jitter
```{r, fig.height=0.6, fig.width=3.6}
result340 %>% 
  # filter(regret > 0) %>%
  ggplot(aes(x=exp, y=regret, color=exp)) +
  geom_jitter(size=0.1, width = 0.2, alpha=0.9) +
  stat_summary(fun=mean, color="black", alpha=0.9, size=0.5, shape="|") +
  theme_classic() +
  labs(y="Regret") +
  scale_y_log10() +
  scale_color_manual("", values=c("mediumorchid4", "grey", "plum4",  "paleturquoise4")) +
  theme(legend.position = "none") +
  theme(strip.background = element_blank()) +
  theme(strip.text.x = element_blank()) +
  coord_flip() ->
  p1

result342 %>% 
  # filter(regret > 0) %>%
  ggplot(aes(x=exp, y=regret, color=exp)) +
  geom_jitter(size=0.1, width = 0.2, alpha=0.9) +
  stat_summary(fun=mean, color="black", alpha=0.9, size=0.5, shape="|") +
  theme_classic() +
  labs(y="Regret") +
  scale_y_log10() +
  scale_color_manual("", values=c("mediumorchid4", "grey", "plum4",  "paleturquoise4")) +
  theme(legend.position = "none") +
  theme(strip.background = element_blank()) +
  theme(strip.text.x = element_blank()) +
  coord_flip() ->
  p2

p1 + p2
```

## Assemble
```{r, fig.height=4, fig.width=3.6}
pa / pb / pc / pd +
  plot_layout(heights = c(0.35, 0.35, 0.15, 0.15)) 
```