---
title: "exp377-380 - BanditOneHigh10"
output: html_notebook
---

# Imports and paths
```{r, message=FALSE}
library(zoo)
library(ggplot2)
library(ggpubr)
library(patchwork)
# library(MASS) 
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
library(scales)
library(patchwork)
options(scipen=1000000)

kl_divergence <- function(p, q) {
  sum(p * log(p/q))
}

# --- Main path to all data ---
data_path <- "~/Code/infomercial/data/"
```

# Load data
```{r, message=FALSE}
result377 <- read_csv(paste(data_path, "exp377_sorted.csv", sep=""))
result378 <- read_csv(paste(data_path, "exp378_sorted.csv", sep=""))
result379 <- read_csv(paste(data_path, "exp379_sorted.csv", sep=""))
result380 <- read_csv(paste(data_path, "exp380_sorted.csv", sep=""))

result377$agent <- "ep-greedy"
result378$agent <- "anneal-ep"
result379$agent <- "dual value"
result380$agent <- "bayesian"

result377.380 <- result377
result377.380 <- bind_rows(result377.380, result378)
result377.380 <- bind_rows(result377.380, result379)
result377.380 <- bind_rows(result377.380, result380)
```

# Best 
```{r, fig.width=1.4, fig.height=0.5}
result377.380 %>% 
  group_by(agent) %>% 
  mutate(total_R = max(total_R)) %>% 
  ggplot(aes(x=agent, y=total_R, color=agent)) +
  geom_point(size=.5) +
  labs(x="Agent", y="Best reward") +
  lims(y=c(0, 100)) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) +
  coord_flip()
```

# Top 10, jitter
```{r, fig.width=1.4, fig.height=0.5}
result377.380 %>% 
  filter(index <= 10) %>% 
  ggplot(aes(x=agent, y=total_R, color=agent)) +
  geom_jitter(size=.1, width=0.2) +
  labs(x="Agent", y="Reward") +
  lims(y=c(0, 100)) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) +
  coord_flip()
```

# Overall, boxplot
```{r, fig.width=1.4, fig.height=0.5}
result377.380 %>% 
  ggplot(aes(x=agent, y=total_R, fill=agent)) +
  geom_boxplot(outlier.colour = NA) +
  labs(x="Agent", y="Reward") +
  lims(y=c(0, 100)) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) +
  coord_flip()
```

# Overall, jitter
```{r, fig.width=1.4, fig.height=0.5}
result377.380 %>% 
  ggplot(aes(x=agent, y=total_R, color=agent)) +
  geom_jitter(size=.1, width=0.2) +
  labs(x="Agent", y="Reward") +
  lims(y=c(0, 100)) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) +
  coord_flip()
```

# Top 10, sorted
```{r, fig.width=0.7, fig.height=0.5}
result377.380 %>% 
  filter(index <= 10) %>% 
  ggplot(aes(x=factor(index), y=total_R, color=agent, group=agent)) +
  geom_line(size=1) +
  labs(x="Param code", y="Total R") +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) 
```

# Overall, sorted
```{r, fig.width=1.4, fig.height=0.5}
result377.380 %>% 
  ggplot(aes(x=index, y=total_R, color=agent)) +
  geom_line(size=1) +
  lims(y=c(20, 70)) +
  labs(x="Param code", y="Total R") +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) 
```

