---
title: "Exp349 - 100 experiments in exploring boredom"
output: html_notebook
---

```{r, message=FALSE}
library(zoo)
library(ggplot2)
library(ggpubr)
library(patchwork)
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
library(MASS) 
library(scales)
library(patchwork)
options(scipen=1000000)

# ---
kl_divergence <- function(p, q) {
  sum(p * log(p/q))
}
```

# Load data
## Set a main path
```{r}
data_path <- "~/Code/infomercial/data/"
```

## Load
```{r message=FALSE, cache=TRUE}
# ---
exp_name <- "exp349"

actor_names <- c("DeterministicActor", "SoftmaxActor", "RandomActor")
threshold_names <- c("threshold1e-1", "threshold1e-2", "threshold1e-3", "threshold1e-4", "threshold1e-5")
thresholds <- c(1e-1, 1e-2, 1e-3, 1e-4, 1e-5)
run_codes <- 1:100

file_names <- c("score_E", "action", "p_bests", "regret", "value_E", 
                "ties", "state", "total_E", "total_regret")

# ---
result349 <- NULL
for (actor in actor_names){
  for (i in 1:length(threshold_names)){
    t_name <- threshold_names[i]
    threshold <- thresholds[i]
    
    for (run in run_codes) {
      runtmp <- read_csv(paste(data_path, 
                               exp_name, 
                               actor,
                               t_name,
                               paste("run", run, sep=""), 
                               paste(file_names[1], "csv", sep="."), sep="/"))    
      for (name in file_names[2:9]){
        tmp <- read_csv(paste(data_path, 
                              exp_name, 
                              actor,
                              t_name,
                              paste("run", run, sep=""), 
                              paste(name, "csv", sep="."), sep="/"))  
        runtmp[[name]] <- tmp[[name]]
      }
      runtmp$run <- run
      runtmp$actor <- actor
      runtmp$threshold <- as.character(threshold)
      runtmp$num_trials <- nrow(tmp)
      result349 <- bind_rows(result349, runtmp)  
    }
  }
}

# ---
rm(tmp, runtmp, run, name)
```

## Summarize
```{r}
# --
Ebias <- 4*1.38

result349 %>% 
  group_by(threshold, actor, run) %>% 
  summarise(
    total_E=max(total_E),
    total_regret=max(total_regret),
    value_E=mean(value_E),
    regret=mean(regret[regret > 0]),
    num_steps=max(num_trials)
  ) %>% 
  ungroup() ->
summary349

# --
summary349$actor <- factor(summary349$actor, 
                           levels=c("DeterministicActor", "SoftmaxActor", "RandomActor"))
```
## jitter - value and steps
```{r, fig.height=1.5, fig.width=5}
# average value
summary349 %>% 
  filter(actor != "RandomActor") %>% 
  ggplot(aes(x=actor, y=value_E, color=actor)) +
  geom_jitter(size=1, alpha=0.9, width=0.2) +
  stat_summary(fun=mean, color="black", alpha=1, size=2, shape="|") +
  scale_colour_manual("", values=c("mediumorchid4", "paleturquoise4", "darkgray")) +
  labs(x="", y="Average value") +
  facet_wrap(.~threshold, scales="free") +
  # lims(y=c(0, 0.08)) +
  theme_classic() +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1.25, "lines")) +
  # theme(axis.text.y = element_blank()) +
  theme(strip.text.y = element_text(angle = 0)) +
  coord_flip() 
```
```{r, fig.height=1.5, fig.width=5}
# steps
summary349 %>% 
  filter(actor != "RandomActor") %>% 
  ggplot(aes(x=actor, y=num_steps, color=actor)) +
  geom_jitter(size=1, alpha=0.9, width=0.2) +
  stat_summary(fun=mean, color="black", alpha=1, size=2, shape="|") +
  scale_colour_manual("", values=c("mediumorchid4", "paleturquoise4", "darkgray")) +
  labs(x="", y="Steps until bored") +
  facet_wrap(.~threshold, scales="free") +
  theme_classic() +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.text.y = element_text(angle = 0)) +
  coord_flip() 
```
```{r, fig.height=1.5, fig.width=5}
# total value
summary349 %>% 
  filter(actor != "RandomActor") %>% 
  ggplot(aes(x=actor, y=total_E - Ebias, color=actor)) +
  geom_jitter(size=1, alpha=0.9, width=0.2) +
  stat_summary(fun=mean, color="black", alpha=1, size=2, shape="|") +
  scale_colour_manual("", values=c("mediumorchid4", "paleturquoise4", "darkgray")) +
  facet_wrap(.~threshold, scales="free") +
  labs(x="", y="Total value") +
  theme_classic() +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) +
  # theme(axis.text.y = element_blank()) +
  theme(strip.text.y = element_text(angle = 0)) +
  coord_flip()
```
