---
title: "exp462 - 466 : DistractionOneHigh10 - top10 param runs"
output: html_notebook
---

# Imports and paths
```{r, message=FALSE}
library(zoo)
library(ggplot2)
library(ggpubr)
library(patchwork)
# library(MASS) 
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
library(scales)
library(patchwork)
options(scipen=1000000)

kl_divergence <- function(p, q) {
  sum(p * log(p/q))
}

load.result <- function(exp_name, param_codes, run_codes, file_names){
  num_files <- length(file_names)
  result <- NULL
  for (param in param_codes){
    for (run in run_codes) {
      runtmp <- read_csv(paste(data_path, 
                               exp_name, 
                               paste("param", param, sep=""), 
                               paste("run", run, sep=""), 
                               paste(file_names[1], "csv", sep="."), sep="/"))    
      for (name in file_names[2:num_files]){
        tmp <- read_csv(paste(data_path, 
                              exp_name, 
                              paste("param", param, sep=""), 
                              paste("run", run, sep=""), 
                              paste(name, "csv", sep="."), sep="/"))  
        runtmp[[name]] <- tmp[[name]]
      }
      runtmp$run <- run
      runtmp$param <- param
      result <- bind_rows(result, runtmp)  
    }
  }
  result
}

# --- Main path to all data ---
data_path <- "~/Code/infomercial/data/"
max_R <- 200
```

# exp462 - meta
## Load data
```{r message=FALSE, cache=TRUE}
exp_name <- "exp462"
param_codes <- 0:9
run_codes <- 1:10
file_names <- c("score_E", 
                "score_R", 
                "action", 
                "p_bests", 
                "regret", 
                "value_E", 
                "value_R", 
                "ties", 
                "state",
                "policy",
                "total_E", 
                "total_R",
                "total_regret")

result462 <- load.result(exp_name, param_codes, run_codes, file_names)
result462 %>% 
  group_by(param, run) %>% 
  summarise(
    total_E=last(total_E),
    total_R=last(total_R),
    total_regret=last(total_regret),
    value_E=last(value_E),
    value_R=last(value_R),
    p_bests=last(p_bests)
  ) %>% 
  ungroup() ->
summary462
```

# exp463 - ep
## Load data
```{r message=FALSE, cache=TRUE}
exp_name <- "exp463"
param_codes <- 0:9
run_codes <- 1:10
file_names <- c("score_R", 
                "action", 
                "p_bests", 
                "regret", 
                "state",
                "value_R", 
                "total_R",
                "p_bests",
                "total_regret")

result463 <- load.result(exp_name, param_codes, run_codes, file_names)
result463 %>% 
  group_by(param, run) %>% 
  summarise(
    total_R=last(total_R),
    total_regret=last(total_regret),
    value_R=last(value_R),
    p_bests=last(p_bests)
  ) %>% 
  ungroup() ->
summary463
```

# exp464 - ep decay
## Load data
```{r message=FALSE, cache=TRUE}
exp_name <- "exp464"
param_codes <- 0:9
run_codes <- 1:10
file_names <- c("score_R", 
                "action", 
                "p_bests", 
                "regret", 
                "state",
                "value_R", 
                "total_R",
                "p_bests",
                "total_regret")

result464 <- load.result(exp_name, param_codes, run_codes, file_names)
result464 %>% 
  group_by(param, run) %>% 
  summarise(
    total_R=last(total_R),
    total_regret=last(total_regret),
    value_R=last(value_R),
    p_bests=last(p_bests)
  ) %>% 
  ungroup() ->
summary464
```


# exp465 - beta
## Load data
```{r message=FALSE, cache=TRUE}
exp_name <- "exp465"
param_codes <- 0:9
run_codes <- 1:10
file_names <- c("score_R", 
                "score_E", 
                "action", 
                "p_bests", 
                "regret", 
                "state",
                "value_ER",
                "total_R",
                "total_E",
                "total_regret")

result465 <- load.result(exp_name, param_codes, run_codes, file_names)
result465 %>% 
  group_by(param, run) %>% 
  summarise(
    total_R=last(total_R),
    total_E=last(total_E),
    total_regret=last(total_regret),
    value_ER=last(value_ER),
    p_bests=last(p_bests)
  ) %>% 
  ungroup() ->
summary465
```


# exp466 - random
## Load data
```{r message=FALSE, cache=TRUE}
exp_name <- "exp466"
param_codes <- c(0)
run_codes <- 1:100
file_names <- c("score_R", 
                "action", 
                "p_bests", 
                "regret", 
                "total_R",
                "value_R",
                "state",
                "total_regret")

result466 <- load.result(exp_name, param_codes, run_codes, file_names)
result466 %>% 
  group_by(param, run) %>% 
  summarise(
    total_R=last(total_R),
    value_R=last(value_R),
    total_regret=last(total_regret),
    p_bests=last(p_bests)
  ) %>% 
  ungroup() ->
summary466
```

# Joint analysis
## Join data
```{r}
result462 %>% 
  dplyr::select(
    global_step, param, run, action, total_R, 
    state, score_R, total_regret, p_bests) -> tmp1
result463 %>% 
  dplyr::select(
    global_step, param, run, action, total_R, 
    state, score_R, total_regret, p_bests) -> tmp2
result464 %>% 
  dplyr::select(
    global_step, param, run, action, total_R, 
    state, score_R, total_regret, p_bests) -> tmp3
result465 %>% 
  dplyr::select(
    global_step, param, run, action, total_R, 
    state, score_R, total_regret, p_bests) -> tmp4
result466 %>% 
  dplyr::select(
    global_step, param, run, action, total_R, 
    state, score_R, total_regret, p_bests) -> tmp5

tmp1$agent <- "dual value"
tmp2$agent <- "ep-greedy"
tmp3$agent <- "anneal-ep"
tmp4$agent <- "bayesian"
tmp5$agent <- "random"

result462_466 <- tmp1
result462_466 <- bind_rows(result462_466, tmp2)
result462_466 <- bind_rows(result462_466, tmp3)
result462_466 <- bind_rows(result462_466, tmp4)
result462_466 <- bind_rows(result462_466, tmp5)

# ---
summary462 %>% 
  dplyr::select(param, run, total_R, total_regret, p_bests) -> tmp1
summary463 %>% 
  dplyr::select(param, run, total_R, total_regret, p_bests) -> tmp2
summary464 %>% 
  dplyr::select(param, run, total_R, total_regret, p_bests) -> tmp3
summary465 %>% 
  dplyr::select(param, run, total_R, total_regret, p_bests) -> tmp4
summary466 %>% 
  dplyr::select(param, run, total_R, total_regret, p_bests) -> tmp5

tmp1$agent <- "dual value"
tmp2$agent <- "ep-greedy"
tmp3$agent <- "anneal-ep"
tmp4$agent <- "bayesian"
tmp5$agent <- "random"

summary462_466 <- tmp1
summary462_466 <- bind_rows(summary462_466, tmp2)
summary462_466 <- bind_rows(summary462_466, tmp3)
summary462_466 <- bind_rows(summary462_466, tmp4)
summary462_466 <- bind_rows(summary462_466, tmp5)
```

## Plot total values
```{r, fig.height=1.5, fig.width=1.4}
## Values
summary462_466 %>% 
  ggplot(aes(x=agent, y=total_R/max_R, color=agent)) +
  geom_jitter(size=0.01, alpha=0.9, width=0.2) +
  stat_summary(fun=median, color="darkgrey", alpha=1, size=0.7, shape="|") +
  scale_colour_manual("", values=c("goldenrod4", "dodgerblue4", "mediumorchid4", "goldenrod3", "darkgrey")) +
  labs(y="Average reward", x="") +
  lims(y=c(0, 1)) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  coord_flip() +
  theme(panel.spacing = unit(1, "lines")) -> p1

summary462_466 %>% 
  ggplot(aes(x=agent, y=total_regret/max_R, color=agent)) +
  geom_jitter(size=0.01, alpha=0.9, width=0.2) +
  stat_summary(fun=median, color="darkgrey", alpha=1, size=0.7, shape="|") +
  scale_colour_manual("", values=c("goldenrod4", "dodgerblue4", "mediumorchid4", "goldenrod3", "darkgrey")) +
  labs(y="Average regret", x="") +
  lims(y=c(0, 1)) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  coord_flip() +
  theme(panel.spacing = unit(1, "lines")) -> p2

summary462_466 %>% 
  ggplot(aes(x=agent, y=p_bests, color=agent)) +
  geom_jitter(size=0.05, alpha=0.9, width=0.2) +
  stat_summary(fun=median, color="darkgrey", alpha=1, size=0.7, shape="|") +
  scale_colour_manual("", values=c("goldenrod4", "dodgerblue4", "mediumorchid4", "goldenrod3", "darkgrey")) +
  labs(y="Best choice", x="") +
  lims(y=c(0, 1)) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  coord_flip() +
  theme(panel.spacing = unit(1, "lines")) -> p3

p1 / p2 / p3 
```
## Plot states (random agent only)
- This plot is a sanity check for the env

### States
```{r, fig.height=1, fig.width=1.2}
result466 %>% 
  filter(run <= 10) %>% 
  ggplot(aes(x=global_step, y=state, color=factor(state), group=run)) +
  geom_point(size=0.3, alpha=1) +
  geom_line(size=0.01, alpha=1, color="black") +
  labs(x="Time", y="State") +
  facet_wrap(run~., ncol=1) +
  scale_colour_manual("State", values=c("yellow", "blue")) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.1, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text = element_blank()) +
  theme(axis.text.x = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks = element_blank()) + 
  theme(legend.key.size = unit(0.2, "cm")) 
```

### By action
```{r, fig.height=2, fig.width=3}
result462_466 %>% 
  filter(agent == "anneal-ep") %>% 
  filter(run <= 10, param==0) %>% 
  ggplot(aes(x=global_step, y=action, color=factor(state), group=run)) +
  geom_point(size=0.1, alpha=1) +
  geom_line(size=0.01, alpha=1, color="black") +
  labs(x="Time", y="Action", title="anneal-ep") +
  facet_wrap(run~., ncol=1) +
  scale_colour_manual("State", values=c("yellow", "blue")) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.1, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text = element_blank()) +
  theme(axis.text.x = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks = element_blank()) + 
  theme(legend.key.size = unit(0.2, "cm")) -> p1

result462_466 %>% 
  filter(agent == "bayesian") %>% 
  filter(run <= 10, param==0) %>% 
  ggplot(aes(x=global_step, y=action, color=factor(state), group=run)) +
  geom_point(size=0.1, alpha=1) +
  geom_line(size=0.01, alpha=1, color="black") +
  labs(x="Time", y="", title="bayesian") +
  facet_wrap(run~., ncol=1) +
  scale_colour_manual("State", values=c("yellow", "blue")) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.1, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text = element_blank()) +
  theme(axis.text.x = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks = element_blank()) + 
  theme(legend.key.size = unit(0.2, "cm")) -> p2

result462_466 %>% 
  filter(agent == "dual value") %>% 
  filter(run <= 10, param==0) %>% 
  ggplot(aes(x=global_step, y=action, color=factor(state), group=run)) +
  geom_point(size=0.1, alpha=1) +
  geom_line(size=0.01, alpha=1, color="black") +
  labs(x="Time", y="", title="dual value") +
  facet_wrap(run~., ncol=1) +
  scale_colour_manual("State", values=c("yellow", "blue")) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.1, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text = element_blank()) +
  theme(axis.text.x = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks = element_blank()) + 
  theme(legend.key.size = unit(0.2, "cm")) -> p3

result462_466 %>% 
  filter(agent == "ep-greedy") %>% 
  filter(run <= 10, param==0) %>% 
  ggplot(aes(x=global_step, y=action, color=factor(state), group=run)) +
  geom_point(size=0.1, alpha=1) +
  geom_line(size=0.01, alpha=1, color="black") +
  labs(x="Time", y="", title="ep-greedy") +
  facet_wrap(run~., ncol=1) +
  scale_colour_manual("State", values=c("yellow", "blue")) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.1, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "right") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text = element_blank()) +
  theme(axis.text.x = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks = element_blank()) + 
  theme(legend.key.size = unit(0.2, "cm")) -> p4

p1 + p2 + p3 + p4 + plot_layout(nrow=1)
```

## Plot rewards
### Totals
```{r, fig.height=0.5, fig.width=1.2}
result462_466 %>% 
  ggplot(aes(x=global_step, y=total_R/max_R, color=agent, group=run)) +
  geom_line(size=0.1, alpha=0.4) +
  labs(x="Time", y="Total reward") +
  facet_grid(.~agent) +
  scale_colour_manual("", values=c("goldenrod4", "dodgerblue4", "mediumorchid4", "goldenrod3", "darkgrey")) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.5, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text.y = element_blank()) +
  theme(axis.text.x = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks = element_blank()) + 
  theme(legend.key.size = unit(0.2, "cm")) 
```

### By action
```{r, fig.height=2, fig.width=3}
result462_466 %>% 
  filter(agent == "anneal-ep") %>% 
  filter(run <= 10, param==0) %>% 
  ggplot(aes(x=global_step, y=action, color=factor(score_R), group=run)) +
  geom_point(size=0.1, alpha=1) +
  geom_line(size=0.01, alpha=1, color="black") +
  labs(x="Time", y="Action", title="anneal-ep") +
  facet_wrap(run~., ncol=1) +
  scale_colour_manual("Reward", values=c("dark grey", "firebrick3")) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.1, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text = element_blank()) +
  theme(axis.text.x = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks = element_blank()) + 
  theme(legend.key.size = unit(0.2, "cm")) -> p1

result462_466 %>% 
  filter(agent == "bayesian") %>% 
  filter(run <= 10, param==0) %>% 
  ggplot(aes(x=global_step, y=action, color=factor(score_R), group=run)) +
  geom_point(size=0.1, alpha=1) +
  geom_line(size=0.01, alpha=1, color="black") +
  labs(x="Time", y="", title="bayesian") +
  facet_wrap(run~., ncol=1) +
  scale_colour_manual("Reward", values=c("dark grey", "firebrick3")) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.1, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text = element_blank()) +
  theme(axis.text.x = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks = element_blank()) + 
  theme(legend.key.size = unit(0.2, "cm")) -> p2

result462_466 %>% 
  filter(agent == "dual value") %>% 
  filter(run <= 10, param==0) %>% 
  ggplot(aes(x=global_step, y=action, color=factor(score_R), group=run)) +
  geom_point(size=0.1, alpha=1) +
  geom_line(size=0.01, alpha=1, color="black") +
  labs(x="Time", y="", title="dual value") +
  facet_wrap(run~., ncol=1) +
  scale_colour_manual("Reward", values=c("dark grey", "firebrick3")) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.1, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text = element_blank()) +
  theme(axis.text.x = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks = element_blank()) + 
  theme(legend.key.size = unit(0.2, "cm")) -> p3

result462_466 %>% 
  filter(agent == "ep-greedy") %>% 
  filter(run <= 10, param==0) %>% 
  ggplot(aes(x=global_step, y=action, color=factor(score_R), group=run)) +
  geom_point(size=0.1, alpha=1) +
  geom_line(size=0.01, alpha=1, color="black") +
  labs(x="Time", y="", title="ep-greedy") +
  facet_wrap(run~., ncol=1) +
  scale_colour_manual("Reward", values=c("dark grey", "firebrick3")) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.1, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "right") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text = element_blank()) +
  theme(axis.text.x = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks = element_blank()) + 
  theme(legend.key.size = unit(0.2, "cm")) -> p4

p1 + p2 + p3 + p4 + plot_layout(nrow=1)
```

## Plot regrets
### Totals
```{r, fig.height=0.5, fig.width=1.2}
result462_466 %>% 
  ggplot(aes(x=global_step, y=total_regret/max_R, color=agent, group=run)) +
  geom_line(size=0.1, alpha=0.4) +
  labs(x="Time", y="Total regret") +
  facet_grid(.~agent) +
  scale_colour_manual("", values=c("goldenrod4", "dodgerblue4", "mediumorchid4", "goldenrod3", "darkgrey")) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.5, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text.y = element_blank()) +
  theme(axis.text.x = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks = element_blank()) + 
  theme(legend.key.size = unit(0.2, "cm")) 
```

## Plot bests
### Totals
```{r, fig.height=0.5, fig.width=1.2}
result462_466 %>% 
  ggplot(aes(x=global_step, y=p_bests, color=agent, group=run)) +
  geom_line(size=0.1, alpha=0.4) +
  labs(x="Time", y="Best choice") +
  facet_grid(.~agent) +
  scale_colour_manual("", values=c("goldenrod4", "dodgerblue4", "mediumorchid4", "goldenrod3", "darkgrey")) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.5, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text.y = element_blank()) +
  theme(axis.text.x = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks = element_blank()) + 
  theme(legend.key.size = unit(0.2, "cm")) 
```

## Plot actions (by run)
```{r, fig.height=1.5, fig.width=1.2}
result462_466 %>% 
  filter(agent != "random") %>% 
  filter(run <= 10, param == 0) %>% 
  ggplot(aes(x=global_step, y=action, color=agent)) +
  geom_line(size=0.3, alpha=1) +
  labs(x="Time", y="Choice") +
  facet_grid(run~agent) +
  scale_colour_manual("", values=c("goldenrod4", "dodgerblue4", "mediumorchid4", "goldenrod3", "darkgrey")) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.5, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text.y = element_blank()) +
  theme(axis.text.x = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks.y = element_blank()) + 
  theme(legend.key.size = unit(0.2, "cm")) 
```
