---
title: "exp403-407 - BanditOneHigh121 - top10 param runs"
output: html_notebook
---

# Imports and paths
```{r, message=FALSE}
library(zoo)
library(ggplot2)
library(ggpubr)
library(patchwork)
# library(MASS) 
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
library(scales)
library(patchwork)
options(scipen=1000000)

kl_divergence <- function(p, q) {
  sum(p * log(p/q))
}

load.result <- function(exp_name, param_codes, run_codes, file_names){
  num_files <- length(file_names)
  result <- NULL
  for (param in param_codes){
    for (run in run_codes) {
      runtmp <- read_csv(paste(data_path, 
                               exp_name, 
                               paste("param", param, sep=""), 
                               paste("run", run, sep=""), 
                               paste(file_names[1], "csv", sep="."), sep="/"))    
      for (name in file_names[2:num_files]){
        tmp <- read_csv(paste(data_path, 
                              exp_name, 
                              paste("param", param, sep=""), 
                              paste("run", run, sep=""), 
                              paste(name, "csv", sep="."), sep="/"))  
        runtmp[[name]] <- tmp[[name]]
      }
      runtmp$run <- run
      runtmp$param <- param
      result <- bind_rows(result, runtmp)  
    }
  }
  result
}

# --- Main path to all data ---
data_path <- "~/Code/infomercial/data/"
max_R <- 24200
```

# exp403 - meta
## Load data
```{r message=FALSE, cache=TRUE}
exp_name <- "exp403"
param_codes <- 0:9
run_codes <- 1:10
file_names <- c("score_E", 
                "score_R", 
                "action", 
                "p_bests", 
                "regret", 
                "value_E", 
                "value_R", 
                "ties", 
                "policy",
                "total_E", 
                "total_R",
                "total_regret")

result403 <- load.result(exp_name, param_codes, run_codes, file_names)
result403 %>% 
  group_by(param, run) %>% 
  summarise(
    total_E=max(total_E),
    total_R=max(total_R),
    total_regret=max(total_regret),
    value_E=median(value_E),
    value_R=median(value_R),
    p_bests=max(p_bests),
    regret=median(regret[regret > 0])
  ) %>% 
  ungroup() ->
summary403
```

## values
### example dual value
```{r, fig.height=2, fig.width=1.2}
result403 %>% 
  filter(run == 1, param == 1) %>% 
  # filter(global_step > 10) %>% 
  ggplot(aes(x=global_step, y=factor(policy), color=factor(policy))) +
  geom_point(size=0.8, alpha=0.5) +
  labs(x="", y="Policy") +
  scale_y_discrete(
    breaks=c(0, 1), 
    labels=c("Explore", "Exploit")) +
  scale_color_manual("", values=c("darkorchid4", "firebrick3")) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) -> p0

result403 %>% 
  filter(run == 1, param == 1) %>% 
  filter(global_step > 10) %>% 
  ggplot(aes(x=global_step, y=value_E)) +
  geom_line(size=0.8, alpha=1, color="darkorchid4") +
  scale_y_log10() +
  annotation_logticks(sides = "l") +
  labs(x="", y="Information value") + 
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) -> p1

result403 %>% 
  filter(run == 1, param == 1) %>% 
  filter(global_step > 10) %>% 
  ggplot(aes(x=global_step, y=value_R)) +
  geom_line(size=0.8, alpha=1, color="firebrick3") +
  scale_y_log10() +
  annotation_logticks(sides = "l") +
  labs(x="", y="Reward value") + 
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) -> p2

result403 %>% 
  filter(run == 1, param == 1) %>% 
  filter(global_step > 10) %>% 
  ggplot(aes(x=global_step, y=regret)) +
  geom_line(size=0.8, alpha=1, color="azure4") +
  lims(x=c(0, 200), y=c(0, 1)) +
  # scale_y_log10() +
  # annotation_logticks(sides = "l") +
  labs(x="Time", y="Regret") + 
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) -> p3

p0 / p1 / p2 / p3
```

### jitter
```{r, fig.height=1.5, fig.width=0.8}
summary403 %>% 
  ggplot(aes(x=factor(param), y=total_E)) +
  geom_jitter(size=0.01, alpha=0.9, width=0.2) +
  stat_summary(fun=median, color="black", alpha=0.9, size=2, shape="-") +
  # geom_boxplot(alpha=0.9, width=0.4, outlier.colour = NA) +
  scale_colour_manual("", values=c("mediumorchid4")) +
  labs(x="Parameter set") +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) -> p1

summary403 %>% 
  ggplot(aes(x=factor(param), y=total_R)) +
  geom_jitter(size=0.01, alpha=0.9, width=0.2) +
  stat_summary(fun=median, color="black", alpha=0.9, size=2, shape="-") +
  # geom_boxplot(alpha=0.9, width=0.4, outlier.colour = NA) +
  scale_colour_manual("", values=c("mediumorchid4")) +
  lims(y=c(0, max_R)) +
  labs(x="Parameter set") +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) -> p2

summary403 %>% 
  ggplot(aes(x=factor(param), y=p_bests)) +
  geom_jitter(size=0.01, alpha=0.9, width=0.2) +
  stat_summary(fun=median, color="black", alpha=0.9, size=2, shape="-") +
  # geom_boxplot(alpha=0.9, width=0.4, outlier.colour = NA) +
  scale_colour_manual("", values=c("mediumorchid4")) +
  labs(x="Parameter set") +
  lims(y=c(0,1)) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) -> p3

p1 / p2 / p3
```

## actions
```{r, fig.height=1.5, fig.width=4}
result403 %>% 
  filter(global_step <= 50) %>%
  ggplot(aes(x=global_step, y=action, color=factor(param))) +
  lims(x=c(0, 50)) +
  geom_line(size=0.3, alpha=1) +
  geom_hline(yintercept = 7, color="grey") +
  labs(x="Time", y="Choice") +
  facet_grid(run~param) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  # scale_color_grey() +
  theme(panel.spacing = unit(0.5, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text.y = element_text(angle = 0)) +
  theme(strip.text.x = element_blank()) +
  theme(axis.text.x = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks = element_blank()) + 
  theme(legend.key.size = unit(0.2, "cm")) 
```

# exp404 - ep
## Load data
```{r message=FALSE, cache=TRUE}
exp_name <- "exp404"
param_codes <- 0:9
run_codes <- 1:10
file_names <- c("score_R", 
                "action", 
                "p_bests", 
                "regret", 
                "value_R", 
                "total_R",
                "p_bests",
                "total_regret")

result404 <- load.result(exp_name, param_codes, run_codes, file_names)
result404 %>% 
  group_by(param, run) %>% 
  summarise(
    total_R=max(total_R),
    total_regret=max(total_regret),
    value_R=median(value_R),
    p_bests=max(p_bests),
    regret=median(regret[regret > 0])
  ) %>% 
  ungroup() ->
summary404
```

## values
### jitter
```{r, fig.height=1.5, fig.width=0.8}
summary404 %>% 
  ggplot(aes(x=factor(param), y=total_R)) +
  geom_jitter(size=0.01, alpha=0.9, width=0.2) +
  stat_summary(fun=median, color="black", alpha=0.9, size=2, shape="-") +
  scale_colour_manual("", values=c("mediumorchid4")) +
  labs(x="Parameter set") +
  lims(y=c(0, max_R)) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) -> p1

summary404 %>% 
  ggplot(aes(x=factor(param), y=total_regret)) +
  geom_jitter(size=0.01, alpha=0.9, width=0.2) +
  stat_summary(fun=median, color="black", alpha=0.9, size=2, shape="-") +
  scale_colour_manual("", values=c("mediumorchid4")) +
  labs(x="Parameter set") +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) -> p2

summary404 %>% 
  ggplot(aes(x=factor(param), y=p_bests)) +
  geom_jitter(size=0.01, alpha=0.9, width=0.2) +
  stat_summary(fun=median, color="black", alpha=0.9, size=2, shape="-") +
  scale_colour_manual("", values=c("mediumorchid4")) +
  labs(x="Parameter set") +
  lims(y=c(0,1)) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) -> p3

p1 / p2 / p3
```

## actions
```{r, fig.height=1.5, fig.width=4}
result404 %>% 
  filter(global_step <= 50) %>%
  ggplot(aes(x=global_step, y=action, color=factor(param))) +
  lims(x=c(0, 50)) +
  geom_line(size=0.3, alpha=1) +
  geom_hline(yintercept = 7, color="grey") +
  labs(x="Time", y="Choice") +
  facet_grid(run~param) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  # scale_color_grey() +
  theme(panel.spacing = unit(0.5, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text.y = element_text(angle = 0)) +
  theme(strip.text.x = element_blank()) +
  theme(strip.text.x = element_blank()) +
  theme(axis.text.x = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks = element_blank()) + 
  theme(legend.key.size = unit(0.2, "cm")) 
```

# exp405 - ep decay
## Load data
```{r message=FALSE, cache=TRUE}
exp_name <- "exp405"
param_codes <- 0:9
run_codes <- 1:10
file_names <- c("score_R", 
                "action", 
                "p_bests", 
                "regret", 
                "value_R", 
                "total_R",
                "p_bests",
                "total_regret")

result405 <- load.result(exp_name, param_codes, run_codes, file_names)
result405 %>% 
  group_by(param, run) %>% 
  summarise(
    total_R=max(total_R),
    total_regret=max(total_regret),
    value_R=median(value_R),
    p_bests=max(p_bests),
    regret=median(regret[regret > 0])
  ) %>% 
  ungroup() ->
summary405
```

## values
### jitter
```{r, fig.height=1.5, fig.width=0.8}
summary405 %>% 
  ggplot(aes(x=factor(param), y=total_R)) +
  geom_jitter(size=0.01, alpha=0.9, width=0.2) +
  stat_summary(fun=median, color="black", alpha=0.9, size=2, shape="-") +
  # geom_boxplot(alpha=0.9, width=0.4, outlier.colour = NA) +
  scale_colour_manual("", values=c("mediumorchid4")) +
  labs(x="Parameter set") +
  lims(y=c(0, max_R)) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) -> p1

summary405 %>% 
  ggplot(aes(x=factor(param), y=total_regret)) +
  geom_jitter(size=0.01, alpha=0.9, width=0.2) +
  stat_summary(fun=median, color="black", alpha=0.9, size=2, shape="-") +
  # geom_boxplot(alpha=0.9, width=0.4, outlier.colour = NA) +
  scale_colour_manual("", values=c("mediumorchid4")) +
  labs(x="Parameter set") +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) -> p2

summary405 %>% 
  ggplot(aes(x=factor(param), y=p_bests)) +
  geom_jitter(size=0.01, alpha=0.9, width=0.2) +
  stat_summary(fun=median, color="black", alpha=0.9, size=2, shape="-") +
  scale_colour_manual("", values=c("mediumorchid4")) +
  labs(x="Parameter set") +
  lims(y=c(0,1)) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) -> p3

p1 / p2 / p3
```

## actions
```{r, fig.height=1.5, fig.width=4}
result405 %>% 
  filter(global_step <= 50) %>%
  ggplot(aes(x=global_step, y=action, color=factor(param))) +
  lims(x=c(0, 50)) +
  geom_line(size=0.3, alpha=1) +
  geom_hline(yintercept = 7, color="grey") +
  labs(x="Time", y="Choice") +
  facet_grid(run~param) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  # scale_color_grey() +
  theme(panel.spacing = unit(0.5, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text.y = element_text(angle = 0)) +
  theme(strip.text.x = element_blank()) +
  theme(strip.text.x = element_blank()) +
  theme(axis.text.x = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks = element_blank()) + 
  theme(legend.key.size = unit(0.2, "cm")) 
```

# exp406 - beta
## Load data
```{r message=FALSE, cache=TRUE}
exp_name <- "exp406"
param_codes <- 0:9
run_codes <- 1:10
file_names <- c("score_R", 
                "score_E", 
                "action", 
                "p_bests", 
                "regret", 
                "value_ER",
                "total_R",
                "total_E",
                "total_regret")

result406 <- load.result(exp_name, param_codes, run_codes, file_names)
result406 %>% 
  group_by(param, run) %>% 
  summarise(
    total_R=max(total_R),
    total_E=max(total_E),
    total_regret=max(total_regret),
    value_ER=median(value_ER),
    p_bests=max(p_bests),
    regret=median(regret[regret > 0])
  ) %>% 
  ungroup() ->
summary406
```

## values
### jitter
```{r, fig.height=2.0, fig.width=0.8}
summary406 %>% 
  ggplot(aes(x=factor(param), y=total_R)) +
  geom_jitter(size=0.01, alpha=0.9, width=0.2) +
  stat_summary(fun=median, color="black", alpha=0.9, size=2, shape="-") +
  # geom_boxplot(alpha=0.9, width=0.4, outlier.colour = NA) +
  scale_colour_manual("", values=c("mediumorchid4")) +
  labs(x="Parameter set") +
  lims(y=c(0, max_R)) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) -> p1

summary406 %>% 
  ggplot(aes(x=factor(param), y=total_E)) +
  geom_jitter(size=0.01, alpha=0.9, width=0.2) +
  stat_summary(fun=median, color="black", alpha=0.9, size=2, shape="-") +
  # geom_boxplot(alpha=0.9, width=0.4, outlier.colour = NA) +
  scale_colour_manual("", values=c("mediumorchid4")) +
  labs(x="Parameter set") +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) -> p2

summary406 %>% 
  ggplot(aes(x=factor(param), y=total_regret)) +
  geom_jitter(size=0.01, alpha=0.9, width=0.2) +
  stat_summary(fun=median, color="black", alpha=0.9, size=2, shape="-") +
  # geom_boxplot(alpha=0.9, width=0.4, outlier.colour = NA) +
  scale_colour_manual("", values=c("mediumorchid4")) +
  labs(x="Parameter set") +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) -> p3

summary406 %>% 
  ggplot(aes(x=factor(param), y=p_bests)) +
  geom_jitter(size=0.01, alpha=0.9, width=0.2) +
  stat_summary(fun=median, color="black", alpha=0.9, size=2, shape="-") +
  scale_colour_manual("", values=c("mediumorchid4")) +
  labs(x="Parameter set") +
  lims(y=c(0,1)) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) -> p4

p1 / p2 / p3 / p4
```

## actions
```{r, fig.height=1.5, fig.width=4}
result406 %>% 
  filter(global_step <= 50) %>%
  ggplot(aes(x=global_step, y=action, color=factor(param))) +
  lims(x=c(0, 50)) +
  geom_line(size=0.3, alpha=1) +
  geom_hline(yintercept = 7, color="grey") +
  labs(x="Time", y="Choice") +
  facet_grid(run~param) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  # scale_color_grey() +
  theme(panel.spacing = unit(0.5, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text.y = element_text(angle = 0)) +
  theme(strip.text.x = element_blank()) +
  theme(strip.text.x = element_blank()) +
  theme(axis.text.x = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks = element_blank()) + 
  theme(legend.key.size = unit(0.2, "cm")) 
```

# exp407 - random
## Load data
```{r message=FALSE, cache=TRUE}
exp_name <- "exp407"
param_codes <- c(0)
run_codes <- 1:100
file_names <- c("score_R", 
                "action", 
                "p_bests", 
                "regret", 
                "total_R",
                "value_R",
                "total_regret")

result407 <- load.result(exp_name, param_codes, run_codes, file_names)
result407 %>% 
  group_by(param, run) %>% 
  summarise(
    total_R=max(total_R),
    total_R=max(value_R),
    total_regret=max(total_regret),
    p_bests=max(p_bests),
    regret=median(regret[regret > 0])
  ) %>% 
  ungroup() ->
summary407
```

## values
### jitter
```{r, fig.height=2.0, fig.width=0.8}
summary407 %>% 
  ggplot(aes(x=factor(param), y=total_R)) +
  geom_jitter(size=0.01, alpha=0.9, width=0.2) +
  stat_summary(fun=median, color="black", alpha=0.9, size=2, shape="-") +
  # geom_boxplot(alpha=0.9, width=0.4, outlier.colour = NA) +
  scale_colour_manual("", values=c("mediumorchid4")) +
  labs(x="Parameter set") +
  lims(y=c(0, max_R)) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) -> p1

summary407 %>% 
  ggplot(aes(x=factor(param), y=total_E)) +
  geom_jitter(size=0.01, alpha=0.9, width=0.2) +
  stat_summary(fun=median, color="black", alpha=0.9, size=2, shape="-") +
  # geom_boxplot(alpha=0.9, width=0.4, outlier.colour = NA) +
  scale_colour_manual("", values=c("mediumorchid4")) +
  labs(x="Parameter set") +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) -> p2

summary407 %>% 
  ggplot(aes(x=factor(param), y=total_regret)) +
  geom_jitter(size=0.01, alpha=0.9, width=0.2) +
  stat_summary(fun=median, color="black", alpha=0.9, size=2, shape="-") +
  # geom_boxplot(alpha=0.9, width=0.4, outlier.colour = NA) +
  scale_colour_manual("", values=c("mediumorchid4")) +
  labs(x="Parameter set") +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) -> p3

summary407 %>% 
  ggplot(aes(x=factor(param), y=p_bests)) +
  geom_jitter(size=0.01, alpha=0.9, width=0.2) +
  stat_summary(fun=median, color="black", alpha=0.9, size=2, shape="-") +
  scale_colour_manual("", values=c("mediumorchid4")) +
  labs(x="Parameter set") +
  lims(y=c(0,1)) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) -> p4

p1 / p2 / p3 / p4
```

## actions
```{r, fig.height=1.5, fig.width=4}
result407 %>% 
  filter(global_step <= 50) %>%
  ggplot(aes(x=global_step, y=action, color=factor(param))) +
  lims(x=c(0, 50)) +
  geom_line(size=0.3, alpha=1) +
  geom_hline(yintercept = 7, color="grey") +
  labs(x="Time", y="Choice") +
  facet_grid(run~param) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  # scale_color_grey() +
  theme(panel.spacing = unit(0.5, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text.y = element_text(angle = 0)) +
  theme(strip.text.x = element_blank()) +
  theme(strip.text.x = element_blank()) +
  theme(axis.text.x = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks = element_blank()) + 
  theme(legend.key.size = unit(0.2, "cm")) 
```

# Joint analysis
## Join
```{r}
result403 %>% 
  dplyr::select(
    global_step, param, run, action, total_R, 
    value_R, total_regret, p_bests) -> tmp1
result404 %>% 
  dplyr::select(
    global_step, param, run, action, total_R, 
    value_R, total_regret, p_bests) -> tmp2
result405 %>% 
  dplyr::select(
    global_step, param, run, action, total_R, 
    value_R, total_regret, p_bests) -> tmp3
result406 %>% 
  dplyr::select(
    global_step, param, run, action, total_R, 
    value_ER, total_regret, p_bests) -> tmp4
result407 %>% 
  dplyr::select(
    global_step, param, run, action, total_R, 
    value_R, total_regret, p_bests) -> tmp5

tmp1$agent <- "dual value"
tmp2$agent <- "ep-greedy"
tmp3$agent <- "anneal-ep"
tmp4$agent <- "bayesian"
tmp5$agent <- "random"

result403_407 <- tmp1
result403_407 <- bind_rows(result403_407, tmp2)
result403_407 <- bind_rows(result403_407, tmp3)
result403_407 <- bind_rows(result403_407, tmp4)
result403_407 <- bind_rows(result403_407, tmp5)

# ---
summary403 %>% 
  dplyr::select(param, run, total_R, total_regret, p_bests) -> tmp1
summary404 %>% 
  dplyr::select(param, run, total_R, total_regret, p_bests) -> tmp2
summary405 %>% 
  dplyr::select(param, run, total_R, total_regret, p_bests) -> tmp3
summary406 %>% 
  dplyr::select(param, run, total_R, total_regret, p_bests) -> tmp4
summary407 %>% 
  dplyr::select(param, run, total_R, total_regret, p_bests) -> tmp5

tmp1$agent <- "dual value"
tmp2$agent <- "ep-greedy"
tmp3$agent <- "anneal-ep"
tmp4$agent <- "bayesian"
tmp5$agent <- "random"

summary403_407 <- tmp1
summary403_407 <- bind_rows(summary403_407, tmp2)
summary403_407 <- bind_rows(summary403_407, tmp3)
summary403_407 <- bind_rows(summary403_407, tmp4)
summary403_407 <- bind_rows(summary403_407, tmp5)
```

## values
```{r, fig.height=1.5, fig.width=1.2}
## Values
summary403_407 %>% 
  ggplot(aes(x=agent, y=total_R/max_R)) +
  geom_jitter(size=0.01, alpha=0.9, width=0.2) +
  stat_summary(fun=median, color="red", alpha=0.6, size=1, shape="|") +
  scale_colour_manual("", values=c("mediumorchid4")) +
  labs(y="Average reward", x="") +
  lims(y=c(0, 1)) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  coord_flip() +
  theme(panel.spacing = unit(1, "lines")) -> p1

summary403_407 %>% 
  ggplot(aes(x=agent, y=total_regret/max_R)) +
  geom_jitter(size=0.01, alpha=0.9, width=0.2) +
  stat_summary(fun=median, color="red", alpha=0.6, size=1, shape="|") +
  labs(y="Average regret", x="") +
  lims(y=c(0, 1)) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  coord_flip() +
  theme(panel.spacing = unit(1, "lines")) -> p2

summary403_407 %>% 
  ggplot(aes(x=agent, y=p_bests)) +
  geom_jitter(size=0.05, alpha=0.9, width=0.2) +
  stat_summary(fun=median, color="red", alpha=0.6, size=1, shape="|") +
  labs(y="Best choice", x="") +
  lims(y=c(0, 1)) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  coord_flip() +
  theme(panel.spacing = unit(1, "lines")) -> p3

p1 / p2 / p3 
```
## actions (by run)
```{r, fig.height=1.5, fig.width=1.2}
result403_407 %>% 
  filter(run <= 10, param == 0) %>% 
  ggplot(aes(x=global_step, y=action, color=agent)) +
  geom_line(size=0.3, alpha=1) +
  labs(x="Time", y="Choice") +
  facet_grid(run~agent) +
  scale_colour_manual("", values=c("goldenrod4", "dodgerblue4", "mediumorchid4", "goldenrod3", "darkgrey")) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.5, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text.y = element_blank()) +
  theme(axis.text.x = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks.y = element_blank()) + 
  theme(legend.key.size = unit(0.2, "cm")) 
```
## actions (by run, 605 trials)
```{r, fig.height=1.5, fig.width=1.2}
result403_407 %>% 
  filter(run <= 10, param == 0) %>% 
  filter(global_step <= 605) %>%
  ggplot(aes(x=global_step, y=action, color=agent)) +
  geom_line(size=0.3, alpha=1) +
  labs(x="Time", y="Choice") +
  facet_grid(run~agent) +
  scale_colour_manual("", values=c("goldenrod4", "dodgerblue4", "mediumorchid4", "goldenrod3", "darkgrey")) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.5, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text.y = element_blank()) +
  theme(axis.text.x = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks.y = element_blank()) + 
  theme(legend.key.size = unit(0.2, "cm")) 
```

## Det v sto
### actions - det v sto
```{r, fig.height=1.5, fig.width=1}
result403_407 %>% 
filter(agent == "dual value") %>% 
  # filter(global_step < 40) %>%
  filter(run == 1, param <= 10) %>% 
  ggplot(aes(x=global_step, y=action)) +
  geom_line(size=0.3, alpha=1, color="darkorchid4") +
  scale_x_continuous(breaks=c(0, 100, 200, 300)) +
  labs(x="", y="Choice", title="Deterministic\n(Dual value)") +
  facet_wrap(.~param, ncol=1) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.1, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text.y = element_text(angle = 0)) +
  theme(strip.text.x = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks = element_blank()) + 
  theme(legend.key.size = unit(0.2, "cm")) -> p1

result403_407 %>% 
filter(agent == "bayesian") %>% 
  # filter(global_step < 40) %>%
  filter(run == 1, param <= 10) %>% 
  ggplot(aes(x=global_step, y=action)) +
  geom_line(size=0.3, alpha=1, color="dodgerblue4") +
  labs(x="", y="", title="Stochastic\n(Intrinsic reward)") +
  scale_x_continuous(breaks=c(0, 100, 200, 300)) +
  facet_wrap(.~param, ncol=1) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.1, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text.y = element_text(angle = 0)) +
  theme(strip.text.x = element_blank()) +
  # theme(axis.text.x = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks = element_blank()) + 
  theme(legend.key.size = unit(0.2, "cm")) -> p2

p1 + p2
```

### values - det v sto
```{r, fig.height=1.5, fig.width=1.2}
## Values
summary403_407 %>% 
  filter(agent %in% c("dual value", "bayesian")) %>%
  ggplot(aes(x=agent, y=total_R, color=agent)) +
  geom_jitter(size=0.01, alpha=0.9, width=0.2) +
  stat_summary(fun=median, color="red", alpha=0.6, size=1, shape="|") +
  scale_colour_manual("", values=c("dodgerblue4", "mediumorchid4")) +
  labs(y="Total reward", x="") +
  lims(y=c(0, max_R)) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  coord_flip() +
  theme(panel.spacing = unit(1, "lines")) -> p1

summary403_407 %>% 
  filter(agent %in% c("dual value", "bayesian")) %>%
  ggplot(aes(x=agent, y=total_regret, color=agent)) +
  geom_jitter(size=0.01, alpha=0.9, width=0.2) +
  scale_colour_manual("", values=c("dodgerblue4", "mediumorchid4")) +
  stat_summary(fun=median, color="red", alpha=0.6, size=1, shape="|") +
  labs(y="Total regret", x="") +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  coord_flip() +
  theme(panel.spacing = unit(1, "lines")) -> p2

summary403_407 %>% 
  filter(agent %in% c("dual value", "bayesian")) %>%
  ggplot(aes(x=agent, y=p_bests, color=agent)) +
  geom_jitter(size=0.05, alpha=0.9, width=0.2) +
  scale_colour_manual("", values=c("dodgerblue4", "mediumorchid4")) +
  stat_summary(fun=median, color="red", alpha=0.6, size=1, shape="|") +
  labs(y="Best choice", x="") +
  lims(y=c(0,1)) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  coord_flip() +
  theme(panel.spacing = unit(1, "lines")) -> p3

p1 / p2 / p3 
```