---
title: "exp499-500 - BanditOneHigh4 - example param versus top1 param"
output: html_notebook
---

# Imports and paths
```{r, message=FALSE}
library(zoo)
library(ggplot2)
library(ggpubr)
library(patchwork)
# library(MASS) 
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
library(scales)
library(patchwork)
options(scipen=1000000)

kl_divergence <- function(p, q) {
  sum(p * log(p/q))
}

load.result <- function(exp_name, param_codes, run_codes, file_names){
  num_files <- length(file_names)
  result <- NULL
  for (param in param_codes){
    for (run in run_codes) {
      runtmp <- read_csv(paste(data_path, 
                               exp_name, 
                               paste("param", param, sep=""), 
                               paste("run", run, sep=""), 
                               paste(file_names[1], "csv", sep="."), sep="/"))    
      for (name in file_names[2:num_files]){
        tmp <- read_csv(paste(data_path, 
                              exp_name, 
                              paste("param", param, sep=""), 
                              paste("run", run, sep=""), 
                              paste(name, "csv", sep="."), sep="/"))  
        runtmp[[name]] <- tmp[[name]]
      }
      runtmp$run <- run
      runtmp$param <- param
      result <- bind_rows(result, runtmp)  
    }
  }
  result
}

# --- Main path to all data ---
data_path <- "~/Code/infomercial/data/"
max_R <- 200
```

# exp499 - example hp
## Load data
```{r message=FALSE, cache=FALSE}
exp_name <- "exp499"
param_codes <- c(0)
run_codes <- 1:100
file_names <- c("score_E", 
                "score_R", 
                "action", 
                "p_bests", 
                "regret", 
                "value_E", 
                "value_R", 
                "ties", 
                "policy",
                "total_E", 
                "total_R",
                "total_regret")

result499 <- load.result(exp_name, param_codes, run_codes, file_names)
result499 %>% 
  group_by(param, run) %>% 
  summarise(
    total_E=max(total_E),
    total_R=max(total_R),
    total_regret=max(total_regret),
    value_E=median(value_E),
    value_R=median(value_R),
    p_bests=max(p_bests),
    regret=median(regret[regret > 0])
  ) %>% 
  ungroup() ->
summary499
```

# exp500 - top1 hp
## Load data
```{r message=FALSE, cache=TRUE}
exp_name <- "exp500"
param_codes <- c(0)
run_codes <- 1:100
file_names <- c("score_E", 
                "score_R", 
                "action", 
                "p_bests", 
                "regret", 
                "value_E", 
                "value_R", 
                "ties", 
                "policy",
                "total_E", 
                "total_R",
                "total_regret")

result500 <- load.result(exp_name, param_codes, run_codes, file_names)
result500 %>% 
  group_by(param, run) %>% 
  summarise(
    total_E=max(total_E),
    total_R=max(total_R),
    total_regret=max(total_regret),
    value_E=median(value_E),
    value_R=median(value_R),
    p_bests=max(p_bests),
    regret=median(regret[regret > 0])
  ) %>% 
  ungroup() ->
summary500
```

# Plot
# all actions
```{r, fig.width=1, fig.height=2.5}
t <- 200
result499 %>% 
  filter(global_step <= t) %>%
  ggplot(aes(x=global_step, y=action)) +
  geom_line(size=0.3, alpha=1) +
  labs(x="Time", y="Choice", "Examples") +
  lims(x=c(0, t)) +
  facet_wrap(run~.) +
  theme_pubr(base_size = 6, legend = "none") +
  # theme(strip.text = element_blank()) +
  theme(strip.text = element_text(size=3)) +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.1, "lines")) +
  theme(axis.ticks = element_blank()) + 
  theme(axis.text = element_blank()) -> p1
  
result500 %>% 
  filter(global_step <= t) %>%
  ggplot(aes(x=global_step, y=action)) +
  
  geom_line(size=0.3, alpha=1) +
  labs(x="Time", y="Choice", "Top 1") +
  lims(x=c(0, t)) +
  facet_wrap(run~.) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.text = element_text(size=3)) +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.1, "lines")) +
  theme(axis.ticks = element_blank()) + 
  theme(axis.text = element_blank()) -> p2

p1 / p2
```

## select run 
```{r}
example <- 42
```

### plot example
```{r, fig.width=0.8, fig.height=1.3}
eta <- 0.0001
result499 %>% 
  filter(run == example) %>% 
  ggplot(aes(x=global_step, y=factor(1-policy), color=factor(policy))) +
  geom_point(size=0.8, alpha=0.9) +
  labs(x="", y="Policy") +
  scale_y_discrete(
    breaks=c(0, 1), 
    labels=c("Exploit", "Explore")) +
  scale_color_manual("", values=c("darkorchid4", "black")) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.3, "lines")) -> p1

result499 %>% 
  filter(run == example) %>% 
  ggplot(aes(x=global_step, y=action, color=factor(policy))) +
  geom_point(size=0.6, alpha=0.9) +
  geom_line(size=0.1) +
  labs(x="Time", y="Choice") +
  facet_wrap(policy~., ncol=1) +
  scale_color_manual("", values=c("darkorchid4", "black")) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(strip.text = element_blank()) +
  theme(panel.spacing = unit(0.5, "lines")) -> p2

result499 %>% 
  filter(run == example) %>% 
  ggplot(aes(x=global_step, y=value_E)) +
  geom_line(size=0.6, color="darkorchid4") +
  geom_ribbon(aes(ymin=0, ymax=score_R), 
              size=0.6, alpha=0.1, fill="black", color=NA) +
  geom_point(aes(global_step, score_R+0.00001), 
              size=0.1, alpha=1, color="black") +
  geom_hline(yintercept = eta, color="darkorchid4", alpha=0.5, size=1) +
  scale_y_log10(limits=c(0.00001, 4)) +
  annotation_logticks(side="l", size=.1) + 
  theme(strip.background = element_blank()) +
  theme_pubr(base_size = 6, legend = "none") -> p3

sub1 <- (p1 / p2 / p3) + 
  plot_layout(heights = c(0.15, 0.35, 0.5)) +
  plot_annotation(title = "Example")
print(sub1)
```

### plot top1
```{r, fig.width=0.8, fig.height=1.3}
eta <- 0.005 # taken from file

result500 %>% 
  filter(run == example) %>% 
  ggplot(aes(x=global_step, y=factor(1-policy), color=factor(policy))) +
  geom_point(size=0.8, alpha=0.9) +
  labs(x="", y="Policy") +
  scale_y_discrete(
    breaks=c(0, 1), 
    labels=c("Exploit", "Explore")) +
  scale_color_manual("", values=c("darkorchid4", "black")) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.3, "lines")) -> p1

result500 %>% 
  filter(run == example) %>% 
  ggplot(aes(x=global_step, y=action, color=factor(policy))) +
  geom_point(size=0.6, alpha=0.9) +
  geom_line(size=0.1) +
  labs(x="Time", y="Choice") +
  facet_wrap(policy~., ncol=1) +
  scale_color_manual("", values=c("darkorchid4", "black")) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(strip.text = element_blank()) +
  theme(panel.spacing = unit(0.5, "lines")) -> p2

result500 %>% 
  filter(run == example) %>% 
  ggplot(aes(x=global_step, y=value_E)) +
  geom_line(size=0.6, color="darkorchid4") +
  geom_ribbon(aes(ymin=0, ymax=score_R), 
              size=0.6, alpha=0.1, fill="black", color=NA) +
  geom_point(aes(global_step, score_R+0.00001), 
              size=0.1, alpha=1, color="black") +
  geom_hline(yintercept = eta, color="darkorchid4", alpha=0.5, size=1) +
  scale_y_log10(limits=c(0.00001, 4)) +
  annotation_logticks(side="l", size=.1) + 
  theme(strip.background = element_blank()) +
  theme_pubr(base_size = 6, legend = "none") -> p3

sub2 <- (p1 / p2 / p3) +
  plot_layout(heights = c(0.15, 0.35, 0.5)) +
  plot_annotation(title = "Top-1")
```

### Build joint 
```{r, fig.width=1.7, fig.height=1.3}
sub1 | sub2
```
