---
title: "exp585_594 : BanditChange121 - 100 trials"
output: html_notebook
---

# Library
```{r, message=FALSE}
library(zoo)
library(ggplot2)
library(ggpubr)
library(patchwork)
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
# library(MASS) 
library(scales)
library(patchwork)
options(scipen=1000000)

# Load load_result and other helpful functions
source("utils.R")

# --- Main path to all data ---
data_path <- "~/Code/infomercial/data"
```


# Load data - task 6
```{r, message=FALSE}
# -------------------------------------------------------------
task_name <- "BanditChange121"
task_code <- 1
num_episodes <- 12100

# The overestimate due to E0
num_arms <- 4
E_bias <- log(num_arms) * num_arms 

exp_names <- c(
  "exp585", 
  "exp586", 
  "exp587", 
  "exp588",
  "exp589",
  "exp590", 
  "exp591", 
  "exp592", 
  "exp593", 
  "exp594")

agent_names <- c(
  "Curiosity", 
  "Random/Greedy", 
  "Decay/Greedy", 
  "Random",
  "Reward", 
  "Bayesian", 
  "Novelty", 
  "Entropy", 
  "Count (EB)",
  "Count (UCB)"
)

class_names <- c(
  "Curiosity",
  "Random",
  "Random",
  "Random",
  "Extrinsic",
  "Intrinsic",
  "Intrinsic",
  "Intrinsic",
  "Intrinsic",
  "Intrinsic"
)

file_names <- c("action", 
                "p_bests", 
                "total_R",
                "total_E",
                "policy",
                "regret",
                "total_regret")

result584_594<- NULL
for(i in 1:length(exp_names)){
  exp_name <- exp_names[i]
  agent_name <- agent_names[i]
  class_name <- class_names[i]
  if (agent_name == "Random"){
    param_codes <- c(0)
    run_codes <- 1:100
  } else{
    param_codes <- 0:9
    run_codes <- 1:10
  }
  
  tmp <- load_result(exp_name, param_codes, run_codes, file_names, 
                     n_max=num_episodes+1)
  
  tmp %>% 
    filter(global_step <= num_episodes) -> tmp
  tmp$exp <- exp_name
  tmp$agent <- agent_name
  tmp$task <- task_name
  tmp$task_code <- task_code
  tmp$strategy <- class_name
  tmp$num_episodes <- num_episodes
  
  result584_594 <- bind_rows(result584_594, tmp)
}

# ----------------------------------------------------------------------------
# post-process
# Force order
result584_594$agent <- factor(result584_594$agent, levels=rev(agent_names))

# Remove E_bias
result584_594$total_E <- result584_594$total_E - E_bias
result584_594$total_E[result584_594$total_E < 0] <- 0

# Clean total_E
# - Novelty, extrinsic have total_E but it is not used, so set 
#   it to zero 
for(a_name in c("Reward", "Novelty")) {
  m <- result584_594$agent == a_name
  result584_594[["total_E"]][m] <- 0
}

# Estimate num_explore
# - for curiosity this is defined by policy
# - for the rest we can count non-zero regret values
result584_594 %>%
  filter(agent != "Curiosity") %>% 
  group_by(agent, run, param) %>%
  mutate(num_explore = sum(regret > 0)) %>% 
  ungroup() -> tmp1

result584_594 %>% 
  filter(agent == "Curiosity") %>% 
  group_by(agent, run, param) %>%
  mutate(num_explore = sum(policy == 0)) -> tmp2

tmp <- bind_rows(tmp2, tmp1)
result584_594 <- tmp
rm(tmp1, tmp2)
```

# Summary stats
```{r, fig.width=1.2, fig.height=1.7}
# ----------------------------------------------------------------------------------------
n <- 121 * 20

result584_594 %>% 
  filter(global_step < n) -> tmp

tmp %>% 
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R),
            total_E = last(total_E),
            total_regret = last(total_regret),
            p_bests = last(p_bests)) %>%  
  ungroup() -> 
  tmp

# Med R for curiosity
median_R <- median((filter(tmp, strategy == "Curiosity"))$total_R)
  
tmp %>% 
  filter(strategy == "Curiosity") %>% 
  mutate(
    color = ifelse(strategy == "Curiosity", "chartreuse4", "black")) %>%
  ggplot(aes(x=agent, y=total_R, color=color)) +
  geom_boxplot(outlier.size = 0, width=0.5) +
  labs(x="", y="", title="Deterministic") +
  lims(y=c(0, n)) +
  scale_color_identity() +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  coord_flip() -> p1

tmp %>% 
  filter(strategy == "Random") %>% 
  mutate(
    color = ifelse(strategy == "Curiosity", "chartreuse4", "black")) %>%
  ggplot(aes(x=agent, y=total_R, color=color)) +
  geom_boxplot(outlier.size = 0, width=0.5) +
  geom_hline(aes(yintercept=max(median_R)), 
             color="chartreuse4",
             size=0.3) +
  labs(x="", y="", title="Random") +
  lims(y=c(0, n)) +
  scale_color_identity() +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  coord_flip() -> p2

tmp %>% 
  filter(strategy == "Extrinsic") %>% 
  mutate(
    color = ifelse(strategy == "Curiosity", "chartreuse4", "black")) %>%
  ggplot(aes(x=agent, y=total_R, color=color)) +
  geom_boxplot(outlier.size = 0, width=0.5) +
  geom_hline(aes(yintercept=max(median_R)), 
             color="chartreuse4",
             size=0.3) +
  labs(x="", y="", title="Extrinsic") +
  lims(y=c(0, n)) +
  scale_color_identity() +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  coord_flip() -> p3

tmp %>% 
  filter(strategy == "Intrinsic") %>% 
  mutate(
    color = ifelse(strategy == "Curiosity", "chartreuse4", "black")) %>%
  ggplot(aes(x=agent, y=total_R, color=color)) +
  geom_boxplot(outlier.size = 0, width=0.5) +
  geom_hline(aes(yintercept=max(median_R)), 
             color="chartreuse4",
             size=0.3) +
  labs(x="", y="Reward", title="Extrinsic + Intrinsic") +
  lims(y=c(0, n)) +
  scale_color_identity() +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  coord_flip() -> p4

# ----------------------------------------------------------------------------------------
summary6 <- p1 / p2  / p3 / p4 + 
  plot_layout(heights = c(0.1, 0.3, 0.1, 0.5)) +
  plot_annotation(title = "Task 6 - Unexpected change", 
                  theme = theme_pubr(base_size = 8, legend = "none"))

print(summary6)
```


# Load data - task 3
```{r, message=FALSE}
# -------------------------------------------------------------
task_name <- "BanditUniform121"
task_code <- 3
num_episodes <- 121 * 250

# The overestimate due to E0
num_arms <- 121
E_bias <- log(num_arms) * num_arms 

exp_names <- c("exp548", 
               "exp550", 
               "exp552", 
               "exp553", 
               "exp574",
               "exp555",
               "exp557", 
               "exp576", 
               "exp559", 
               "exp561")

agent_names <- c(
  "Curiosity", 
  "Random/Greedy", 
  "Decay/Greedy", 
  "Random",
  "Reward", 
  "Bayesian", 
  "Novelty", 
  "Entropy", 
  "Count (EB)",
  "Count (UCB)"
)

class_names <- c(
  "Curiosity",
  "Random",
  "Random",
  "Random",
  "Extrinsic",
  "Intrinsic",
  "Intrinsic",
  "Intrinsic",
  "Intrinsic",
  "Intrinsic"
)

file_names <- c("action", 
                "p_bests", 
                "total_R",
                "total_E",
                "policy",
                "regret",
                "total_regret")

result_task3 <- NULL
for(i in 1:length(exp_names)){
  exp_name <- exp_names[i]
  agent_name <- agent_names[i]
  class_name <- class_names[i]
  if (agent_name == "Random"){
    param_codes <- c(0)
    run_codes <- 1:100
  } else{
    param_codes <- 0:9
    run_codes <- 1:10
  }
  
  tmp <- load_result(
    exp_name, param_codes, run_codes, file_names, n_max=num_episodes+1)
  
  tmp %>% 
    filter(global_step <= num_episodes) -> tmp
  tmp$exp <- exp_name
  tmp$agent <- agent_name
  tmp$task <- task_name
  tmp$task_code <- task_code
  tmp$strategy <- class_name
  tmp$num_episodes <- num_episodes
  
  result_task3 <- bind_rows(result_task3, tmp)
}

# ----------------------------------------------------------------------------
# post-process
# Force order
result_task3$agent <- factor(result_task3$agent, levels=rev(agent_names))

# Remove E_bias
result_task3$total_E <- result_task3$total_E - E_bias
result_task3$total_E[result_task3$total_E < 0] <- 0

# Clean total_E
# - Novelty, extrinsic have total_E but it is not used, so set 
#   it to zero 
for(a_name in c("Extrinsic", "Novelty")) {
  m <- result_task3$agent == a_name
  result_task3[["total_E"]][m] <- 0
}

# Estimate num_explore
# - for curiosity this is defined by policy
# - for the rest we can count non-zero regret values
result_task3 %>%
  filter(agent != "Curiosity") %>% 
  group_by(agent, run, param) %>%
  mutate(num_explore = sum(regret > 0)) %>% 
  ungroup() -> tmp1

result_task3 %>% 
  filter(agent == "Curiosity") %>% 
  group_by(agent, run, param) %>%
  mutate(num_explore = sum(policy == 0)) -> tmp2

tmp <- bind_rows(tmp2, tmp1)
result_task3 <- tmp
rm(tmp1, tmp2)
```

# Summary stats
```{r, fig.width=1.2, fig.height=1.7}
# ----------------------------------------------------------------------------------------
n <- 121 * 20

result_task3 %>% 
  filter(global_step < n) -> tmp

tmp %>% 
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R),
            total_E = last(total_E),
            total_regret = last(total_regret),
            p_bests = last(p_bests)) %>%  
  ungroup() -> 
  tmp

# Med R for curiosity
median_R <- median((filter(tmp, strategy == "Curiosity"))$total_R)
  
tmp %>% 
  filter(strategy == "Curiosity") %>% 
  mutate(
    color = ifelse(strategy == "Curiosity", "chartreuse4", "black")) %>%
  ggplot(aes(x=agent, y=total_R, color=color)) +
  geom_boxplot(outlier.size = 0, width=0.5) +
  labs(x="", y="", title="Deterministic") +
  lims(y=c(0, n)) +
  scale_color_identity() +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  coord_flip() -> p1

tmp %>% 
  filter(strategy == "Random") %>% 
  mutate(
    color = ifelse(strategy == "Curiosity", "chartreuse4", "black")) %>%
  ggplot(aes(x=agent, y=total_R, color=color)) +
  geom_boxplot(outlier.size = 0, width=0.5) +
  geom_hline(aes(yintercept=max(median_R)), 
             color="chartreuse4",
             size=0.3) +
  labs(x="", y="", title="Random") +
  lims(y=c(0, n)) +
  scale_color_identity() +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  coord_flip() -> p2

tmp %>% 
  filter(strategy == "Extrinsic") %>% 
  mutate(
    color = ifelse(strategy == "Curiosity", "chartreuse4", "black")) %>%
  ggplot(aes(x=agent, y=total_R, color=color)) +
  geom_boxplot(outlier.size = 0, width=0.5) +
  geom_hline(aes(yintercept=max(median_R)), 
             color="chartreuse4",
             size=0.3) +
  labs(x="", y="", title="Extrinsic") +
  lims(y=c(0, n)) +
  scale_color_identity() +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  coord_flip() -> p3

tmp %>% 
  filter(strategy == "Intrinsic") %>% 
  mutate(
    color = ifelse(strategy == "Curiosity", "chartreuse4", "black")) %>%
  ggplot(aes(x=agent, y=total_R, color=color)) +
  geom_boxplot(outlier.size = 0, width=0.5) +
  geom_hline(aes(yintercept=max(median_R)), 
             color="chartreuse4",
             size=0.3) +
  labs(x="", y="Reward", title="Extrinsic + Intrinsic") +
  lims(y=c(0, n)) +
  scale_color_identity() +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  coord_flip() -> p4

# ----------------------------------------------------------------------------------------
summary3 <- p1 / p2  / p3 / p4 + 
  plot_layout(heights = c(0.1, 0.3, 0.1, 0.5)) +
  plot_annotation(title = "Task 3 - High dimensional", 
                  theme = theme_pubr(base_size = 8, legend = "none"))

print(summary3)
```