---
title: "Fig. exploration behavoir by strategy and task"
output: html_notebook
---

# Library
```{r, message=FALSE}
library(zoo)
library(ggplot2)
library(ggpubr)
library(patchwork)
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
# library(MASS) 
library(scales)
library(patchwork)
options(scipen=1000000)

# Load load_result and other helpful functions
source("utils.R")

# --- Main path to all data ---
data_path <- "~/Code/infomercial/data"
```

# Load data
## BanditOneHigh4
```{r, message=FALSE, warning=FALSE}
task_name <- "BanditOneHigh4"
task_code <- 2
num_episodes <- 4 * 25

# The overestimate due to E0
num_arms <- 4
E_bias <- log(num_arms) * num_arms

exp_names <- c("exp457",
               # "exp526",
               # "exp527",
               # "exp547",
               "exp502",
               "exp525",
               "exp501",
               "exp504",
               "exp503",
               "exp539")

agent_names <- c(
  "Curiosity\n(IG)", 
  # "Random/Greedy", 
  # "Decay/Greedy", 
  # "Random",
  "Reward", 
  "Reward+\nIG", 
  "Reward+\nNovelty", 
  "Reward+\nEntropy", 
  "Reward+\nEB",
  "Reward+\nUCB")

class_names <- c(
  "E-explore (IG)", 
  # "Random",
  # "Random",
  # "Random",
  "Reward",
  "Mixed",
  "Mixed",
  "Mixed",
  "Mixed",
  "Mixed",
  "Mixed"
)

file_names <- c("action",
                "total_R",
                "policy",
                "regret")

explore_task2 <- NULL
for (i in 1:length(exp_names)) {
  exp_name <- exp_names[i]
  agent_name <- agent_names[i]
  class_name <- class_names[i]
  if (agent_name == "Random") {
    param_codes <- c(0)
    run_codes <- 1:100
  } else{
    param_codes <- 0:9
    run_codes <- 1:10
  }
  
  tmp <- load_result(exp_name, param_codes, run_codes, file_names,
                     n_max = num_episodes + 1)
  
  tmp %>%
    filter(global_step <= num_episodes) -> tmp
  tmp$exp <- exp_name
  tmp$agent <- agent_name
  tmp$task <- task_name
  tmp$task_code <- task_code
  tmp$strategy <- class_name
  tmp$num_episodes <- num_episodes
  
  explore_task2 <- bind_rows(explore_task2, tmp)
}

# ----------------------------------------------------------------------------
# post-process
# Force order
explore_task2$agent <- factor(explore_task2$agent, levels = agent_names)

# Set 'policy' in agents without separate ones.
#
# 1. Policy does not exist as a field in any but curiosity
# it was filled with zero, which is misleading when I go to color by
# policy. All strategies not curiosity should have a policy of 1
# to mean exploitation
explore_task2$policy[explore_task2$strategy != "Curiosity"] <- 1

# 2. To estimate exploration we use regret. Regret driven exploration we
# denote as -1
explore_task2$policy[explore_task2$regret > 0] <- -1 
```

## BanditUniform121
```{r, message=FALSE, warning=FALSE}
# -------------------------------------------------------------
task_name <- "BanditUniform121"
task_code <- 6
num_episodes <- 121 * 25

exp_names <- c("exp548",
               # "exp526",
               # "exp527",
               # "exp547",
               "exp574",
               "exp555",
               "exp557",
               "exp576",
               "exp559",
               "exp561")

agent_names <- c(
  "Curiosity\n(IG)", 
  # "Random/Greedy", 
  # "Decay/Greedy", 
  # "Random",
  "Reward", 
  "Reward+\nIG", 
  "Reward+\nNovelty", 
  "Reward+\nEntropy", 
  "Reward+\nEB",
  "Reward+\nUCB")

class_names <- c(
  "E-explore (IG)", 
  # "Random",
  # "Random",
  # "Random",
  "Reward",
  "Mixed",
  "Mixed",
  "Mixed",
  "Mixed",
  "Mixed",
  "Mixed"
)

file_names <- c("action",
                "total_R",
                "policy",
                "regret")

explore_task6 <- NULL
for (i in 1:length(exp_names)) {
  exp_name <- exp_names[i]
  agent_name <- agent_names[i]
  class_name <- class_names[i]
  if (agent_name == "Random") {
    param_codes <- c(0)
    run_codes <- 1:100
  } else{
    param_codes <- 0:9
    run_codes <- 1:10
  }
  
  tmp <- load_result(exp_name, param_codes, run_codes, file_names,
                     n_max = num_episodes + 1)
  
  tmp %>%
    filter(global_step <= num_episodes) -> tmp
  tmp$exp <- exp_name
  tmp$agent <- agent_name
  tmp$task <- task_name
  tmp$task_code <- task_code
  tmp$strategy <- class_name
  tmp$num_episodes <- num_episodes
  
  explore_task6 <- bind_rows(explore_task6, tmp)
}

# ----------------------------------------------------------------------------
# post-process
# Force order
explore_task6$agent <- factor(explore_task6$agent, levels = agent_names)

# Set 'policy' in agents without separate ones.
#
# 1. Policy does not exist as a field in any but curiosity
# it was filled with zero, which is misleading when I go to color by
# policy. All strategies not curiosity should have a policy of 1
# to mean exploitation
explore_task6$policy[explore_task6$strategy != "Curiosity"] <- 1

# 2. To estimate exploration we use regret. Regret driven exploration we
# denote as -1
explore_task6$policy[explore_task6$regret > 0] <- -1 
```

# Task 2 - Behave
```{r, fig.width=9, fig.height=7}
explore_task2 %>%
  filter(run <= 8) %>%
  filter(param == 1) %>%
  ggplot(aes(x = global_step, y = action + 1, color=strategy)) + #, color=factor(policy))) +
  geom_point(size = 0.3, alpha = 1) +
  geom_line(size = 0.1) +
  labs(x = "Time",
       y = "Action",
       subtitle = "Task 2 - Classic") +
  scale_color_manual("Agent", 
                     values = c("black", "darkgrey", "chartreuse4")) + 
  scale_x_continuous(limits = c(0, 4 * 25),
                     breaks = c(0, 4 * 25)) +
  scale_y_continuous(limits = c(0.9, num_arms + .1), breaks = c(1, 4)) +
  facet_grid(run ~ agent) +
  theme_pubr(base_size = 10, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing.x = unit(0.75, "lines")) +
  theme(panel.spacing.y = unit(0.5, "lines")) +
  theme(strip.background = element_blank()) +
  theme(strip.text.y = element_blank()) +
  theme(strip.text.x = element_text(hjust = -.05)) -> b1

print(b1)
```
# Task 6 - Behave
```{r, fig.width=9, fig.height=7}
explore_task6 %>%
  filter(run <= 8) %>%
  filter(param == 1) %>%
  ggplot(aes(x = global_step, y = action + 1, color=strategy)) + 
  geom_point(size = 0.1, alpha = 1) +
  geom_line(size = 0.1) +
  labs(x = "Time", y = "Action", 
       subtitle = "Task 6 - High dimensional") +
  scale_color_manual("Agent", 
                     values = c("black", "darkgrey", "chartreuse4")) + 
  scale_x_continuous(limits = c(0, 121 * 25),
                     breaks = c(0, 121 * 25)) +
  scale_y_continuous(limits = c(0.9, 121 + .1), breaks = c(1, 121)) +
  facet_grid(run ~ agent) +
  theme_pubr(base_size = 10, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing.x = unit(0.75, "lines")) +
  theme(panel.spacing.y = unit(0.5, "lines")) +
  theme(strip.background = element_blank()) +
  theme(strip.text.y = element_blank()) +
  theme(strip.text.x = element_text(hjust = -.05)) -> b2

print(b2)
```

# Join - Behave
```{r, fig.width=7, fig.height=10}
# Build
exploration1 <- b1 / b2 +
  plot_annotation(
    title = "Examples of bandit exploration",
    subtitle = "8 experiments, best parameters",
    tag_levels = 'a',
    tag_suffix = ".",
    theme = theme_pubr(base_size = 10, legend = "none")
  )
print(exploration1)

# -
name <- "img/exploration1"
ggsave(
  paste(name, ".pdf", sep = ""),
  plot = exploration1,
  width = 7,
  height = 10
)
```

# Task 2 - Reward timecourse
```{r, fig.width=9, fig.height=2}
explore_task2 %>%
  filter(param == 0) %>%
  filter(global_step > 10) %>%
  ggplot(aes(x = global_step, y = total_R / global_step, color=strategy)) +
  geom_point(size = 0.2, alpha = 1) +
  labs(x = "Time",
       y = "Avg. reward",
       subtitle = "Task 2 - Classic") +
  scale_color_manual("Agent", 
                     values = c("black", "darkgrey", "chartreuse4")) + 
  scale_y_continuous(limits = c(0, 1.1), breaks = c(0, 0.5, 1)) +
  scale_x_continuous(limits = c(0, 4 * 25),
                     breaks = c(0, 4 * 25)) +
  facet_grid(. ~ agent) +
  theme_pubr(base_size = 10, legend = "none") +
  theme(panel.spacing = unit(.75, "lines")) +
  theme(strip.background = element_blank()) +
  theme(strip.text.x = element_text(hjust = -0.1)) -> r1

print(r1)
```

# Task 6 - Reward timecourse
```{r, fig.width=9, fig.height=2}
explore_task6 %>%
  filter(param == 0) %>%
  filter(global_step > 10) %>%
  ggplot(aes(x = global_step, y = total_R / global_step, color=strategy)) +
  geom_point(size = 0.1, alpha = .2) +
  labs(x = "Time",
       y = "Avg. reward",
       subtitle = "Task 6 - High dimensional") +
  scale_color_manual("Agent", 
                     values = c("black", "darkgrey", "chartreuse4")) + 
  scale_y_continuous(limits = c(0, 1.1), breaks = c(0, 0.5, 1)) +
  scale_x_continuous(limits = c(0, 121 * 25),
                     breaks = c(0, 121 * 25)) +
  facet_grid(. ~ agent) +
  theme_pubr(base_size = 10, legend = "none") +
  theme(panel.spacing = unit(.75, "lines")) +
  theme(strip.background = element_blank()) +
  theme(strip.text.x = element_text(hjust = -0.1)) -> 
  r2

print(r2)
```

# Join - Reward
```{r, fig.width=7, fig.height=5}
# Build
exploration2 <- r1 / r2 +
  plot_annotation(
    title = "Examples of bandit reward collection",
    subtitle = "10 experiments, Top 10 parameters",
    tag_levels = 'a',
    tag_suffix = ".",
    theme = theme_pubr(base_size = 10, legend = "none")
  )
print(exploration2)

# -
name <- "img/exploration2"
ggsave(
  paste(name, ".pdf", sep = ""),
  plot = exploration2,
  width = 7,
  height = 5
)
```