---
title: "Figs. Forcding det or noise on search algortihms"
output: html_notebook
---

# Library
```{r, message=FALSE}
library(zoo)
library(ggplot2)
library(ggpubr)
library(patchwork)
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
# library(MASS) 
library(scales)
library(patchwork)
options(scipen=1000000)

# Load load_result and other helpful functions
source("utils.R")

# --- Main path to all data ---
data_path <- "/Volumes/Data/infomercial/data"
```

# Forced det
## Load data
```{r, message=FALSE}
# -------------------------------------------------------------
task_name <- "BanditOneHigh4"
task_code <- 1
num_episodes <- 4*50

# The overestimate due to E0
num_arms <- 4
E_bias <- log(num_arms) * num_arms 

exp_names <- c(
  "exp457", 
  "exp579",
  "exp581", 
  "exp582", 
  "exp583", 
  "exp584")

agent_names <- c(
  "Curiosity", 
  "Bayesian", 
  "Novelty", 
  "Entropy", 
  "Count (EB)",
  "Count (UCB)"
)

class_names <- c(
  "Curiosity",
  "Intrinsic",
  "Intrinsic",
  "Intrinsic",
  "Intrinsic",
  "Intrinsic"
)


file_names <- c("action", 
                "p_bests", 
                "total_R",
                "total_E",
                "policy",
                "regret",
                "total_regret")

result_forced<- NULL
for(i in 1:length(exp_names)){
  exp_name <- exp_names[i]
  agent_name <- agent_names[i]
  class_name <- class_names[i]
  if (agent_name == "Random"){
    param_codes <- c(0)
    run_codes <- 1:100
  } else{
    param_codes <- 0:9
    run_codes <- 1:10
  }
  
  tmp <- load_result(exp_name, param_codes, run_codes, file_names, 
                     n_max=num_episodes+1)
  
  tmp %>% 
    filter(global_step <= num_episodes) -> tmp
  tmp$exp <- exp_name
  tmp$agent <- agent_name
  tmp$task <- task_name
  tmp$task_code <- task_code
  tmp$strategy <- class_name
  tmp$num_episodes <- num_episodes
  
  result_forced <- bind_rows(result_forced, tmp)
}

# ----------------------------------------------------------------------------
# post-process
# Force order
result_forced$agent <- factor(result_forced$agent, levels=rev(agent_names))

# Remove E_bias
result_forced$total_E <- result_forced$total_E - E_bias
result_forced$total_E[result_forced$total_E < 0] <- 0
```

## Fig.
```{r, fig.width = 1.2, fig.height = 1.1}
num_episodes <- 4*50

# --
result_forced %>% 
  # filter(agent != "Random") %>%
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R),
            total_E = last(total_E),
            total_regret = last(total_regret),
            p_bests = last(p_bests)) %>% 
  ungroup() -> tmp


# Med R for curiosity
median_R <- median((filter(tmp, strategy == "Curiosity"))$total_R)
  
tmp %>% 
  filter(strategy == "Curiosity") %>% 
  mutate(
    color = ifelse(strategy == "Curiosity", "chartreuse4", "black")) %>%
  ggplot(aes(x=agent, y=total_R/num_episodes, color=color)) +
  geom_boxplot(size=0.3, outlier.shape=NA) + 
  geom_jitter(size=0.1, position=position_jitter(width=.2, height=0)) +
  # geom_hline(aes(yintercept=max(median_R/num_episodes)), 
  #            color="chartreuse4",
  #            size=0.3) +
  labs(x="", y="", title="Deterministic") +
  lims(y=c(0.2, 0.9)) +
  scale_color_identity() +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  coord_flip() -> p1

tmp %>% 
  filter(strategy == "Intrinsic") %>% 
  mutate(
    color = ifelse(strategy == "Curiosity", "chartreuse4", "black")) %>%
  ggplot(aes(x=agent, y=total_R/num_episodes, color=color)) +
  geom_boxplot(size=0.3, outlier.shape=NA) +
  geom_jitter(size=0.1, position=position_jitter(width=.2, height=0)) +
  geom_hline(aes(yintercept=max(median_R/num_episodes)), 
             color="chartreuse4",
             size=0.3) +
  labs(x="", y="Reward", title="Extrinsic + Intrinsic (forced)") +
  lims(y=c(0.2, 0.9)) +
  scale_color_identity() +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  coord_flip() -> p2

# ---
forced1 <- p1 / p2 +
  plot_layout(heights = c(0.2, 0.8)) +
  plot_annotation(
    title = "Forced determinism on stochastic\nsearch",
    theme = theme_pubr(base_size = 8, legend = "none"))
print(forced1)

name <- "img/forced1"
ggsave(paste(name, ".pdf", sep=""), plot=forced1, width = 1.2*2, height = 1.1*2)
```

# Forced noise
## Load data 
```{r, message=FALSE}
# -------------------------------------------------------------
task_name <- "BanditOneHigh4"
task_code <- 1
num_episodes <- 200

# The overestimate due to E0
num_arms <- 4
E_bias <- log(num_arms) * num_arms 

rank_names <- c(
  "exp613_sorted.csv", 
  "exp614_sorted.csv", 
  "exp615_sorted.csv", 
  "exp616_sorted.csv",
  "exp617_sorted.csv", 
  "exp618_sorted.csv", 
  "exp619_sorted.csv", 
  "exp620_sorted.csv", 
  "exp621_sorted.csv")

agent_names <- c(
  "Curiosity", 
  "Random/Greedy", 
  "Decay/Greedy", 
  "Reward", 
  "Info. value", 
  "Novelty", 
  "Entropy", 
  "Count (EB)",
  "Count (UCB)"
)

class_names <- c(
  "Stochastic",
  "Random",
  "Random",
  "Extrinsic",
  "Intrinsic",
  "Intrinsic",
  "Intrinsic",
  "Intrinsic",
  "Intrinsic"
)

result_noise4 <- NULL
for(i in 1:length(rank_names)){
  rank_name <- rank_names[i]
  agent_name <- agent_names[i]
  class_name <- class_names[i]
  if (agent_name == "Random"){
    param_codes <- c(0)
    run_codes <- 1:100
  } else{
    param_codes <- 0:9
    run_codes <- 1:10
  }
  
  tmp <- read_csv(paste(data_path, rank_name, sep="/"))
  
  tmp$exp <- rank_name
  tmp$agent <- agent_name
  tmp$task <- task_name
  tmp$task_code <- task_code
  tmp$strategy <- class_name
  
  result_noise4 <- bind_rows(result_noise4, tmp)
}

result_noise4$agent <- factor(result_noise4$agent, levels = agent_names)
```

## Fig
```{r, fig.width=1, fig.height=2}
result_noise4 %>% 
  filter(strategy == "Stochastic") %>% 
  mutate(
    color = ifelse(agent == "Curiosity", "chartreuse4", "black")) %>% 
  ggplot(aes(x=temp, y=total_R/num_episodes, group=agent, color=factor(color))) +
  geom_line(size=0.6, alpha=0.9) +
  scale_color_identity() +
  labs(x="", y="Reward", title="Stochastic (forced)") +
  lims(y=c(0.2, 0.8)) +
  scale_x_log10() +
  facet_grid(agent~.) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(strip.text.y = element_text(angle=0)) -> p1

result_noise4 %>% 
filter(strategy == "Intrinsic") %>% 
mutate(
    color = ifelse(agent == "Soft curiosity", "chartreuse4", "black")) %>% 
  ggplot(aes(x=temp, y=total_R/num_episodes, group=agent, color=factor(color))) +
  geom_line(size=0.6, alpha=0.9) +
  scale_color_identity() +
  labs(x="Noise level", y="Reward", title="Extrinsic + Intrinsic") +
  lims(y=c(0.2, 0.8)) +
  scale_x_log10() +
  facet_grid(agent~.) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank())  +
  theme(strip.text.y = element_text(angle=0, hjust=1)) -> p2

# ---
forced2 <- p1 / p2 + plot_layout(heights = c(0.16, 0.16*6)) +
  plot_annotation(
    title = "The effect of noise on\nstochastic search",
    theme = theme_pubr(base_size = 8, legend = "none"))
print(forced2)

name <- "img/forced2"
ggsave(paste(name, ".pdf", sep=""), plot=forced2, width = 1*2, height = 2*2)
```
