---
title: "Figs. Independent policies"
output: html_notebook
---

# Library
```{r, message=FALSE}
library(zoo)
library(ggplot2)
library(ggpubr)
library(patchwork)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
# library(MASS) 
library(scales)
library(patchwork)
library(tidyr)
library(dplyr)
options(scipen=1000000)

# Load load_result and other helpful functions
source("utils.R")

# --- Main path to all data ---
data_path <- "~/Code/infomercial/data"
```

# Fig. Example
## Load data
```{r message=FALSE, cache=TRUE}
exp_name <- "exp563"
param_codes <- c(0)
run_codes <- c(1)

# The overestimate due to E0
num_arms <- 4
E_bias <- log(num_arms) 

file_names <- c("score_E", 
                "score_R", 
                "action", 
                "p_bests", 
                "regret", 
                "value_E", 
                "value_R", 
                "ties", 
                "policy",
                "total_E", 
                "total_R",
                "total_regret")

result563 <- load_result(exp_name, param_codes, run_codes, file_names)

# Remove E_bias
result563$total_E <- result563$total_E - (E_bias * num_arms)
result563$total_E[result563$total_E < 0] <- 0
result563$score_E[result563$score_E >= E_bias] <- 0
result563$value_E[result563$value_E >= E_bias] <- 0

# Shift action code up by one
result563$action <- result563$action + 1
```

## Vis
```{r,  fig.width=3, fig.height=6}
# Select data for example plot
r <- 1
p <- 0
n <- 200
eta <- 0.0005

# ---------------------------------------------------------------
# Time course
result563 %>% 
  filter(global_step <= n) %>%
  ggplot(aes(x=global_step, y=factor(1-policy), color=factor(policy))) +
  geom_point(size=0.6, alpha=0.9) +
  labs(x="Time", y="Policy", title="Control", tag="a.") +
  scale_y_discrete(
    breaks=c(0, 1), 
    labels=c("Exploit", "Explore")) +
  scale_color_manual("", values=c("chartreuse4", "black")) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.3, "lines")) -> c1a

result563 %>% 
  filter(global_step <= n) %>%
  ggplot(aes(x=global_step, y=action, color=factor(policy))) +
  geom_point(size=0.6, alpha=0.9) +
  # geom_line(size=0.1) +
  labs(x="Time", y="Arm", title="Choice" , tag="b.") +
  # facet_wrap(policy~., ncol=1) +
  scale_y_continuous(limits=c(0.8, 4.2), breaks = c(1, 2, 3, 4)) +
  scale_color_manual("", values=c("chartreuse4", "black")) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(strip.text = element_blank()) +
  theme(panel.spacing = unit(0.15, "lines")) -> c1b

# Shift scores by one, to show how WSLS works
n <- nrow(result563)
result563 %>% 
  select(global_step, score_R, score_E, policy) %>% 
  summarise(global_step=global_step[1:n-1],
         score_R=score_R[1:n-1],
         score_E=score_E[1:n-1],
         policy=policy[2:n]) -> tmp
tmp %>%
  ggplot(aes(x=global_step, y=score_E, color=factor(policy))) +
  geom_point(size=0.6) +
  geom_hline(
    yintercept = eta, color="chartreuse4", alpha=1, size=0.2) +
  labs(x="", y="Info. value", title="WSLS", tag="c.") +
  scale_color_manual("", values=c("chartreuse4", "black")) +
  scale_y_log10(limits=c(0.00001, 4)) +
  annotation_logticks(side="l", size=.1) + 
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(strip.text.y = element_text(size=6)) -> c1c

tmp %>%
  ggplot(aes(x=global_step, y=score_R, color=factor(policy))) +
  geom_point(size=0.6) +
  labs(x="Time", y="Reward", title="") +
  scale_color_manual("", values=c("chartreuse4", "black")) +
  scale_y_continuous(limits=c(0, 1), breaks = c(0, 1)) +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(strip.text.y = element_text(size=6)) -> c1d

# -----------------------------------------------------------------------
## Build figure
independent1 <- (c1a / c1b / (c1c / c1d)) +
  plot_layout(heights = c(0.2, 0.2, 0.6)) +
  plot_annotation(
      title="Explore-exploit with WSLS",
      theme = theme_pubr(base_size = 10, legend = "none"))
print(independent1)

name <- "img/independent1"
ggsave(paste(name, ".pdf", sep=""), 
       plot=independent1, width = 1.2*2, height = 2.8*2)
```

# Fig. Rew - Sto v. det
## Load data
```{r, message=FALSE}
# -------------------------------------------------------------
task_name <- "BanditOneHigh4"
task_code <- 1
num_episodes <- 4*50

# The overestimate due to E0
num_arms <- 4
E_bias <- log(num_arms) * num_arms 

exp_names <- c(
  "exp457", 
  "exp577", 
  "exp578")

agent_names <- c(
  "Deterministic", 
  "Stochastic (temp=0.1)", 
  "Stochastic (temp=0.05)")

class_names <- c(
  "Deterministic",
  "Stochastic",
  "Stochastic")

file_names <- c("action", 
                "p_bests", 
                "total_R",
                "total_E",
                "policy",
                "regret",
                "total_regret")

result457_577_578<- NULL
for(i in 1:length(exp_names)){
  exp_name <- exp_names[i]
  agent_name <- agent_names[i]
  class_name <- class_names[i]
  if (agent_name == "Random"){
    param_codes <- c(0)
    run_codes <- 1:100
  } else{
    param_codes <- 0:9
    run_codes <- 1:10
  }
  
  tmp <- load_result(exp_name, param_codes, run_codes, file_names, 
                     n_max=num_episodes+1)
  
  tmp %>% 
    filter(global_step <= num_episodes) -> tmp
  tmp$exp <- exp_name
  tmp$agent <- agent_name
  tmp$task <- task_name
  tmp$task_code <- task_code
  tmp$strategy <- class_name
  tmp$num_episodes <- num_episodes
  
  result457_577_578 <- bind_rows(result457_577_578, tmp)
}

# ----------------------------------------------------------------------------
# post-process
# Force order
result457_577_578$agent <- factor(result457_577_578$agent, levels=rev(agent_names))

# Remove E_bias
result457_577_578$total_E <- result457_577_578$total_E - E_bias
result457_577_578$total_E[result457_577_578$total_E < 0] <- 0
```

## Vis
```{r, fig.width=6.6, fig.height=2.8}
result457_577_578 %>% 
filter(exp == "exp457") %>% 
filter(param <= 2, run > 1) %>% 
filter(global_step <= num_episodes) %>%
  ggplot(aes(x=global_step, y=action)) +
  geom_point(size=0.1, alpha=0.9, shape=".") +
  geom_line(size=0.1, alpha=1) +
  labs(x="Time", y="Choice", title="Deterministic", tag="a.") +
  lims(x=c(0, num_episodes)) +
  facet_grid(run~param) +
  scale_color_manual("", values=c("chartreuse4", "black")) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.text = element_blank()) +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.1, "lines")) +
  theme(axis.ticks = element_blank()) + 
  theme(axis.text = element_blank()) -> a1

result457_577_578 %>% 
filter(exp == "exp577") %>% 
filter(param <= 2, run > 1) %>% 
filter(global_step <= num_episodes) %>%
  ggplot(aes(x=global_step, y=action)) +
  geom_point(size=0.1, alpha=0.9, shape=".") +
  geom_line(size=0.1, alpha=1) +
  labs(x="Time", y="Choice", title="Stochastic (temp=0.1)") +
  lims(x=c(0, num_episodes)) +
  facet_grid(run~param) +
  scale_color_manual("", values=c("chartreuse4", "black")) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.text = element_blank()) +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.1, "lines")) +
  theme(axis.ticks = element_blank()) + 
  theme(axis.text = element_blank()) -> a2

result457_577_578 %>% 
filter(exp == "exp578") %>% 
filter(param <= 2, run > 1) %>% 
filter(global_step <= num_episodes) %>%
  ggplot(aes(x=global_step, y=action)) +
  geom_point(size=0.1, alpha=0.9, shape=".") +
  geom_line(size=0.1, alpha=1) +
  labs(x="Time", y="Choice", title="Stochastic (temp=0.05)") +
  lims(x=c(0, num_episodes)) +
  facet_grid(run~param) +
  scale_color_manual("", values=c("chartreuse4", "black")) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.text = element_blank()) +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.1, "lines")) +
  theme(axis.ticks = element_blank()) + 
  theme(axis.text = element_blank()) -> a3

# ---
result457_577_578 %>% 
filter(global_step > 4) %>% 
  filter(param <= 2, run > 1) %>% 
  filter(exp == "exp457") %>% 
  ggplot(aes(x=global_step, y=total_R/global_step, 
             group=interaction(param,run))) +
  geom_line(size=0.1, alpha=1) +
  labs(x="", y="", title="Deterministic", tag="b.") +
  scale_x_continuous(limits=c(0, num_episodes),
                     breaks = c(0, num_episodes/2, num_episodes)) +
  scale_y_continuous(limits=c(0, 1),
                     breaks = c(0, 0.5, 1)) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.background = element_blank()) -> r1

result457_577_578 %>% 
filter(global_step > 4) %>% 
  filter(param <= 2, run > 1) %>% 
  filter(exp == "exp577") %>% 
  ggplot(aes(x=global_step, y=total_R/global_step, 
             group=interaction(param,run))) +
  geom_line(size=0.1, alpha=1) +
  labs(x="", y="Avg. Reward", title="Stochastic (temp=0.1)") +
  scale_x_continuous(limits=c(0, num_episodes),
                     breaks = c(0, num_episodes/2, num_episodes)) +
  scale_y_continuous(limits=c(0, 1),
                     breaks = c(0, 0.5, 1)) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.background = element_blank()) -> r2

result457_577_578 %>% 
  filter(global_step > 4) %>% 
  filter(param <= 2, run > 1) %>% 
  filter(exp == "exp578") %>% 
  ggplot(aes(x=global_step, y=total_R/global_step, 
             group=interaction(param,run))) +
  geom_line(size=0.1, alpha=1) +
  labs(x="Time", y="", title="Stochastic (temp=0.05)") +
  scale_x_continuous(limits=c(0, num_episodes),
                     breaks = c(0, num_episodes/2, num_episodes)) +
  scale_y_continuous(limits=c(0, 1),
                     breaks = c(0, 0.5, 1)) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.background = element_blank()) -> r3

result457_577_578 %>% 
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R),
            total_E = last(total_E),
            total_regret = last(total_regret),
            p_bests = last(p_bests)) %>% 
  ungroup() -> tmp

tmp %>% 
  # mutate(
  #   color = ifelse(strategy == "Deterministic", "chartreuse4", "black")) %>%
  ggplot(aes(x=agent, y=total_R/num_episodes)) +
  geom_boxplot(outlier.size = 0, width=0.5) +
  labs(x="", y="Reward", title="", tag="b.") +
  lims(y=c(0.2, 0.9)) +
  scale_color_identity() +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  coord_flip() -> s1

# Build
independent2 <- (a1 + a2 + a3) + (s1 / plot_spacer() / plot_spacer()) + 
  plot_layout(widths = c(0.26, 0.26, 0.26, 0.22)) +
    plot_annotation(
      title="WSLS - deterministic versus stochastic",
      subtitle = "Reward collection",
                  theme = theme_pubr(base_size = 8, legend = "none"))
print(independent2)

# -- Save a to pdf --
name <- "img/independent2"
ggsave(paste(name, ".pdf", sep=""), 
       plot=independent2, width = 3.3*2, height = 1.4*2)
```

# Fig. Info - Sto v. det
## Load data
```{r message=FALSE, cache=TRUE}
# ---
exp_name <- "exp348"
num_episodes <- 320
num_arms <- 4

actor_names <- c("DeterministicActor", 
                 "SoftmaxActor")
better_names <- c("Deterministic", 
                  "Stochastic")

run_codes <- 1:100
file_names <- c("score_E", 
                "action", 
                "p_bests", 
                "regret", 
                "value_E", 
                "ties", 
                "state", 
                "total_E", 
                "total_regret")

# -------------------------------------------------------------------
# This data has a slightly different structure compared to the rest in 
# this notebook so we Need a custom load loop.
result348 <- NULL
for (i in 1:length(actor_names)){
  actor <- actor_names[i]
  better <- better_names[i]
  for (run in run_codes) {
    runtmp <- read_csv(paste(data_path, 
                             exp_name, 
                             actor,
                             paste("run", run, sep=""), 
                             paste(file_names[1], "csv", sep="."), sep="/"),
                            show_col_types = FALSE)    
    for (name in file_names[2:9]){
      tmp <- read_csv(paste(data_path, 
                            exp_name, 
                            actor,
                            paste("run", run, sep=""), 
                            paste(name, "csv", sep="."), sep="/"),
                      show_col_types = FALSE)  
      runtmp[[name]] <- tmp[[name]]
    }
    runtmp$run <- run
    runtmp$actor <- better
    runtmp$num_episodes <- nrow(tmp)
    result348 <- bind_rows(result348, runtmp)  
  }
}

# -----------------------------------------------------------------------
# Don't need wall time
result348[["t"]] <- NULL

# Remove E_bias
E_bias <- log(num_arms)
 
result348$total_E <- result348$total_E - (E_bias * num_arms)
result348$total_E[result348$total_E < 0] <- 0
# result348$score_E <- result348$score_E - E_bias
# result348$score_E[result348$score_E < 0] <- 0
# result348$value_E <- result348$value_E - E_bias
# result348$value_E[result348$value_E < 0] <- 0

# -----------------------------------------------------------------------
# Summarize the results 
result348 %>% 
  group_by(actor, run) %>% 
  summarise(
    total_E=last(total_E)/last(num_episodes),
    total_regret=last(total_regret)/last(num_episodes),
    num_explore=last(num_episodes)
  ) %>% 
  ungroup() ->
final348
final348$actor <- factor(
  final348$actor, levels=c("Stochastic", "Deterministic"))

final348 %>% 
  group_by(actor) %>% 
  summarise(
            median_E = median(total_E), 
            var_E = mad(total_E),
            median_num_explore = median(num_explore), 
            var_num_explore = mad(num_explore),
            median_regret = median(total_regret),
            var_regret = mad(total_regret)) %>% 
    ungroup() -> summary348
```

## Vis
```{r, fig.width=4.8, fig.height=2.2}
r <- 1

# -------------------------------------------------------------------
result348 %>% 
  filter(actor == "Deterministic") %>% 
  filter(run == r) %>% 
  ggplot(aes(x=global_step, y=action+1)) +
  lims(x=c(0, 320)) +
  geom_point(size=0.2, alpha=1, color="chartreuse4") +
  geom_line(size=0.1, color="chartreuse4") +
  labs(x="", y="Choice", title="Deterministic", tag="a.") +
  facet_wrap(.~run, ncol=1) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  scale_y_continuous(limits=c(0.8,4.5), breaks=c(1,4)) +
  theme(panel.spacing = unit(0.1, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text.y = element_text(angle = 0)) +
  theme(strip.text.x = element_blank()) +
  theme(legend.key.size = unit(0.2, "cm")) -> 
  c1a

result348 %>% 
  filter(actor == "Stochastic") %>% 
  filter(run == r) %>% 
  ggplot(aes(x=global_step, y=action+1)) +
  lims(x=c(0, 320)) +
  geom_point(size=0.2, alpha=1, color="black") +
  geom_line(size=0.1, color="black") +
  scale_y_continuous(limits=c(0.8,4.5), breaks=c(1,4)) +
  labs(x="", y="", title="Stochastic (temp=0.1)") +
  facet_wrap(.~run, ncol=1) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.1, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(plot.title = element_text(size = 6)) +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(strip.text.y = element_text(angle = 0)) +
  theme(strip.text.x = element_blank()) +
  theme(legend.key.size = unit(0.2, "cm")) -> 
  c1b

result348 %>% 
  filter(run == r) %>% 
  filter(global_step > 5) %>%
  ggplot(aes(x=global_step, y=value_E, color=actor)) +
  geom_line(size=0.8, alpha=1) +
  lims(x=c(0, 320)) +
  scale_color_manual("", values = c("chartreuse4", "black")) +
  scale_y_log10() +
  annotation_logticks(size=0.1, sides = "l") +
  facet_wrap(.~actor) +
  labs(x="", y="Info. value", tag="b.") + 
  theme_pubr(base_size = 6, legend = "none") +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.background = element_blank()) +
  theme(strip.text.x = element_blank()) -> 
  c1c

sub1 <- (c1a + c1b) / c1c #+ 

# ------------------------------------------------------------------
final348 %>% 
  ggplot(aes(x=actor, y=total_E)) +
  geom_jitter(width = 0.3, size=0.2, alpha=0.1) +
  stat_summary(fun.y = median, aes(color=actor), size=0.3, shape=1) +
  labs(x="", y="Info. value", tag="c.") +
  scale_color_manual("", values = c("black", "chartreuse4")) +
  scale_y_continuous(
    limits=c(0.0015, 0.0032), breaks = c(0.0015, 0.0015*2, 0.003)) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  coord_flip() -> c2a

final348 %>% 
  ggplot(aes(x=actor, y=num_explore)) +
  geom_jitter(width = 0.3, size=0.2, alpha=0.1) +
  stat_summary(fun.y = median, aes(color=actor), size=0.3, shape=1) +
  labs(x="", y="Num. explore", tag="d.") +
  scale_color_manual("", values = c("black", "chartreuse4")) +
  scale_y_continuous(limits=c(80, 160), breaks = c(80, 120, 160)) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  coord_flip() -> c2c

sub2 <- c2a / c2c

# -------------------------------------------------------------------------
curiosity1 <- (sub1 | sub2) + 
  plot_layout(widths = c(0.7, 0.3)) +
    plot_annotation(
      title="WSLS - deterministic versus stochastic",
      subtitle = "Information collection (Task 1)",
      theme = theme_pubr(base_size=8, legend="none"))
print(curiosity1)

name <- "img/independent3"
ggsave(paste(name, ".pdf", sep=""), 
       plot=curiosity1, width = 4.8, height = 2.2)
```