---
title: "Figures"
output: html_notebook
---

```{r}
library(ggplot2)
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
```

```{r, echo=FALSE, message=FALSE}
data_path <- "~/Code/infomercial/data/"

# Load data
# bandit_name <- "BanditHardAndSparse10-v0"
# bandit_name <- "BanditUniform121-v0"
bandit_name <- "BanditOneHigh10-v0"
# bandit_name <- "BanditTwoHigh10-v0"
one_traces <- read_csv(paste(data_path, "table_traces_", bandit_name, ".csv", sep=""))
one_total <- read_csv(paste(data_path, "table_total_", bandit_name, ".csv", sep=""))
one_critic <- read_csv(paste(data_path, "table_critic_", bandit_name, ".csv", sep=""))
one_bandit <- read_csv(paste(data_path, "table_bandit_", bandit_name, ".csv", sep=""))

one_traces$agents <- factor(one_traces$agents, 
                        levels=rev(c("eta", "beta", "softbeta", "epsilon", "anneal-epsilon", "random")))
```

```{r, fig.width=1.5, fig.height=0.8}
one_traces %>% 
  group_by(episodes, agents) %>% 
  summarise(M = median(p_bests), SD = mad(p_bests)) %>% 
  ggplot(aes(x=episodes, y=M, color=agents, group=interaction(agents))) +
  geom_line(size=1, alpha=0.8) +
  scale_color_manual(
    values=rev(c("darkorchid4", "mediumpurple3", "mediumpurple1", "steelblue3", "steelblue1", "grey"))) +
  # geom_linerange(aes(x=episodes, ymin=M - SD, ymax=M + SD), alpha=0.05) +
  theme_classic() +
  labs(x="Trial", y="P(best)")
```

```{r, fig.width=1.5, fig.height=0.8}
one_traces %>% 
  group_by(episodes, agents) %>% 
  summarise(M = median(values_R), SD = mad(values_R)) %>% 
  ggplot(aes(x=episodes, y=M, color=agents, group=interaction(agents))) +
  geom_point(size=1, alpha=0.8) +
  scale_color_manual(
    values=rev(c("darkorchid4", "mediumpurple3", "mediumpurple1", "steelblue3", "steelblue1", "grey"))) +
  # geom_linerange(aes(x=episodes, ymin=M - SD, ymax=M + SD), alpha=0.05) +
  theme_classic() +
  labs(x="Trial", y="Value")
```

```{r, fig.width=2, fig.height=0.6}
one_critic %>% 
  ggplot((aes(x=as.factor(arms), y=critic_values, color=agents))) +
  geom_point(size=.05, position = position_jitterdodge(dodge.width=0.8, jitter.width=.1)) +
  # geom_boxplot(outlier.shape = NA) +
  theme_classic() +
  labs(x="Arm", y="Value")
```


```{r, fig.width=1.5, fig.height=0.8}
one_total %>% 
  group_by(agents) %>% 
  summarise(M = median(regrets), SD=mad(regrets)) %>% 
  ggplot(aes(x=agents, y=M, color=agents)) +
  geom_point(alpha=.9) +
  # geom_errorbar(aes(ymin=M-SD, ymax=M+SD), width=.1) +
  theme_classic() +
  labs(x="Agent", y="Regret") +
  coord_flip()
```

```{r, fig.width=1.8, fig.height=0.8}
one_total %>% 
  group_by(agents) %>% 
  summarise(M = median(total_R), SD=mad(total_R)) %>% 
  ggplot(aes(x=agents, y=M, color=agents)) +
  geom_point(alpha=.9) +
  geom_errorbar(aes(ymin=M-SD, ymax=M+SD), width=.1) +
  theme_classic() +
  labs(x="Agent", y="Total reward") +
  # lims(y=c(0, 2100)) + 
  coord_flip()
```

```{r, fig.width=1.8, fig.height=0.8}
one_traces %>% 
  group_by(agents) %>% 
  filter(episodes > 450) %>% 
  summarise(M = median(p_bests), SD=mad(p_bests)) %>% 
  ggplot(aes(x=agents, y=M, color=agents)) +
  geom_point(alpha=.9) +
  geom_errorbar(aes(ymin=M-SD, ymax=M+SD), width=.1) +
  theme_classic() +
  labs(x="Agent", y="P(best)") +
  coord_flip() +
  lims(y=c(0, 1))
```