---
title: "Fig. Reward collection performance"
output: html_notebook
---


# Load data
## Cached?
```{r, eval=FALSE}
load.image(file="performance.RData")
```

## New
From indivdual notebooks, for all bandit tasks.
```{r, warning=FALSE, message=FALSE, eval=FALSE}
library(knitr)
source(knitr::purl("task2_results.Rmd", quiet=TRUE))
source(knitr::purl("task3_results.Rmd", quiet=TRUE))
source(knitr::purl("task4_results.Rmd", quiet=TRUE))
source(knitr::purl("task5_results.Rmd", quiet=TRUE))
source(knitr::purl("task6_results.Rmd", quiet=TRUE))
source(knitr::purl("task7_results.Rmd", quiet=TRUE))

# Save
save.image(file="performance.RData")
```


# Vis
## Median/MAD - By Task
### Task 2
```{r, fig.width=4.5, fig.height=2}
# -------------------------------------------------------
# Vars
num_episodes <- max(result_task2$global_step)
limits <- c(0, 0.85)
breaks <- c(0.0, 0.4, 0.8)

# -------------------------------------------------------
# Tabulate
result_task2 %>%  
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R)) %>% 
  ungroup() %>% 
  group_by(strategy, agent) %>% 
  summarise(median_R = median(total_R), 
            var_R = mad(total_R),
            sum_R = sum(total_R),
            mean_R = mean(total_R)) %>% 
  ungroup() -> tmp

# Reference 
wsls_R <- median((filter(tmp, strategy == "WSLS"))$median_R)
random_R <- median((filter(tmp, strategy == "Random"))$median_R)

# -------------------------------------------------------
# Vis
tmp %>% 
  filter(agent != "Random") %>%
  ggplot(aes(x=agent, y=median_R, color=strategy)) +
  geom_point(size=2.5, alpha=0.8) +
  geom_linerange(aes(
    ymin=(median_R+var_R),
    ymax=(median_R-var_R)),
    alpha=0.4) +
  geom_hline(aes(yintercept=wsls_R),
             color="chartreuse4",
             size=0.4) +
  geom_hline(aes(yintercept=random_R),
             color="black",
             size=0.2,
             linetype="dashed") +
  scale_color_manual("", values = c("black", "darkgrey", "chartreuse4")) +
  labs(x="", y="Reward", subtitle = "Task 2 - Classic") +
  # scale_y_continuous(limits = limits, breaks = breaks) +
  theme_pubr(base_size = 10, legend = "none") +
  theme(strip.background = element_blank()) +
  coord_flip() -> m2

print(m2)
```

### Task 3
```{r, fig.width=4.5, fig.height=2}
# -------------------------------------------------------
# Vars
num_episodes <- max(result_task3$global_step)
limits <- c(0, 0.025)
breaks <- c(0.0, 0.01, 0.02)

# -------------------------------------------------------
# Tabulate
result_task3 %>%  
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R),
            total_E = last(total_E),
            total_value = last(total_R) + last(total_E),
            total_regret = last(total_regret)) %>% 
  ungroup() %>% 
  group_by(strategy, agent) %>% 
  summarise(median_R = median(total_R), 
            var_R = mad(total_R),
            median_E = median(total_E), 
            var_E = mad(total_E),
            median_total_value = median(total_value), 
            var_total_value = mad(total_value),
            median_regret = median(total_regret),
            var_regret = mad(total_regret)) %>% 
  ungroup() -> tmp

# Reference 
wsls_R <- median((filter(tmp, strategy == "WSLS"))$median_R)
random_R <- median((filter(tmp, strategy == "Random"))$median_R)

# -------------------------------------------------------
# Vis
tmp %>% 
  filter(agent != "Random") %>%
  ggplot(aes(x=agent, y=median_R/num_episodes, color=strategy)) +
  geom_point(size=2.5, alpha=0.8) +
  geom_linerange(aes(
    ymin=(median_R+var_R)/num_episodes, 
    ymax=(median_R-var_R)/num_episodes), 
    alpha=0.4) +
  geom_hline(aes(yintercept=wsls_R/num_episodes), 
             color="chartreuse4",
             size=0.4) +
  geom_hline(aes(yintercept=random_R/num_episodes), 
             color="black",
             size=0.2,
             linetype="dashed") +
  labs(x="", y="Average reward", subtitle = "Task 3 - Sparse") +
  scale_y_continuous(limits = limits, breaks = breaks) +
  scale_color_manual("", values = c("black", "darkgrey", "chartreuse4")) +
  theme_pubr(base_size = 10, legend = "none") +
  theme(strip.background = element_blank()) +
  coord_flip() -> m3

print(m3)
```

### Task 4
```{r, fig.width=4.5, fig.height=2}
# -------------------------------------------------------
# Vars
num_episodes <- max(result_task4$global_step)
limits <- c(0, 0.45)
breaks <- c(0.0, 0.2, 0.4)

# -------------------------------------------------------
# Tabulate
result_task4 %>%  
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R),
            total_E = last(total_E),
            total_value = last(total_R) + last(total_E),
            total_regret = last(total_regret)) %>% 
  ungroup() %>% 
  group_by(strategy, agent) %>% 
  summarise(median_R = median(total_R), 
            var_R = mad(total_R),
            median_E = median(total_E), 
            var_E = mad(total_E),
            median_total_value = median(total_value), 
            var_total_value = mad(total_value),
            median_regret = median(total_regret),
            var_regret = mad(total_regret)) %>% 
  ungroup() -> tmp

# Reference 
wsls_R <- median((filter(tmp, strategy == "WSLS"))$median_R)
random_R <- median((filter(tmp, strategy == "Random"))$median_R)

# -------------------------------------------------------
# Vis
tmp %>% 
  filter(agent != "Random") %>%
  ggplot(aes(x=agent, y=median_R/num_episodes, color=strategy)) +
  geom_point(size=2.5, alpha=0.8) +
  geom_linerange(aes(
    ymin=(median_R+var_R)/num_episodes, 
    ymax=(median_R-var_R)/num_episodes), 
    alpha=0.4) +
  geom_hline(aes(yintercept=wsls_R/num_episodes), 
             color="chartreuse4",
             size=0.4) +
  geom_hline(aes(yintercept=random_R/num_episodes), 
             color="black",
             size=0.2,
             linetype="dashed") +
  labs(x="", y="Average reward", subtitle = "Task 4 - Deception") +
  scale_y_continuous(limits = limits, breaks = breaks) +
  scale_color_manual("", values = c("black", "darkgrey", "chartreuse4")) +
  theme_pubr(base_size = 10, legend = "none") +
  theme(strip.background = element_blank()) +
  coord_flip() -> m4

print(m4)
```
### Task 5
```{r, fig.width=4.5, fig.height=2}
# -------------------------------------------------------
# Vars
num_episodes <- max(result_task5$global_step)
limits <- c(0, 0.85)
breaks <- c(0.0, 0.4, 0.8)

# -------------------------------------------------------
# Tabulate
result_task5 %>%  
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R),
            total_E = last(total_E),
            total_value = last(total_R) + last(total_E),
            total_regret = last(total_regret)) %>% 
  ungroup() %>% 
  group_by(strategy, agent) %>% 
  summarise(median_R = median(total_R), 
            var_R = mad(total_R),
            median_E = median(total_E), 
            var_E = mad(total_E),
            median_total_value = median(total_value), 
            var_total_value = mad(total_value),
            median_regret = median(total_regret),
            var_regret = mad(total_regret)) %>% 
  ungroup() -> tmp

# Reference 
wsls_R <- median((filter(tmp, strategy == "WSLS"))$median_R)
random_R <- median((filter(tmp, strategy == "Random"))$median_R)

# -------------------------------------------------------
# Vis
tmp %>% 
  filter(agent != "Random") %>%
  ggplot(aes(x=agent, y=median_R/num_episodes, color=strategy)) +
  geom_point(size=2.5, alpha=0.8) +
  geom_linerange(aes(
    ymin=(median_R+var_R)/num_episodes, 
    ymax=(median_R-var_R)/num_episodes), 
    alpha=0.4) +
  geom_hline(aes(yintercept=wsls_R/num_episodes), 
             color="chartreuse4",
             size=0.4) +
  geom_hline(aes(yintercept=random_R/num_episodes), 
             color="black",
             size=0.2,
             linetype="dashed") +
  labs(x="", y="Average reward", subtitle = "Task 5 - Distraction") +
  scale_y_continuous(limits = limits, breaks = breaks) +
  scale_color_manual("", values = c("black", "darkgrey", "chartreuse4")) +
  theme_pubr(base_size = 10, legend = "none") +
  theme(strip.background = element_blank()) +
  coord_flip() -> m5

print(m5)
```


### Task 6
```{r, fig.width=4.5, fig.height=2}
# -------------------------------------------------------
# Vars
num_episodes <- max(result_task6$global_step)
limits <- c(0, 0.85)
breaks <- c(0.0, 0.4, 0.8)

# -------------------------------------------------------
# Tabulate
result_task6 %>%  
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R),
            total_E = last(total_E),
            total_value = last(total_R) + last(total_E),
            total_regret = last(total_regret)) %>% 
  ungroup() %>% 
  group_by(strategy, agent) %>% 
  summarise(median_R = median(total_R), 
            var_R = mad(total_R),
            median_E = median(total_E), 
            var_E = mad(total_E),
            median_total_value = median(total_value), 
            var_total_value = mad(total_value),
            median_regret = median(total_regret),
            var_regret = mad(total_regret)) %>% 
  ungroup() -> tmp

# Reference 
wsls_R <- median((filter(tmp, strategy == "WSLS"))$median_R)
random_R <- median((filter(tmp, strategy == "Random"))$median_R)

# -------------------------------------------------------
# Vis
tmp %>% 
  filter(agent != "Random") %>%
  ggplot(aes(x=agent, y=median_R/num_episodes, color=strategy)) +
  geom_point(size=2.5, alpha=0.8) +
  geom_linerange(aes(
    ymin=(median_R+var_R)/num_episodes, 
    ymax=(median_R-var_R)/num_episodes), 
    alpha=0.4) +
  geom_hline(aes(yintercept=wsls_R/num_episodes), 
             color="chartreuse4",
             size=0.4) +
  geom_hline(aes(yintercept=random_R/num_episodes), 
             color="black",
             size=0.2,
             linetype="dashed") +
  labs(x="", y="Average reward", subtitle = "Task 6 - High dimensional") +
  scale_y_continuous(limits = limits, breaks = breaks) +
  scale_color_manual("", values = c("black", "darkgrey", "chartreuse4")) +
  theme_pubr(base_size = 10, legend = "none") +
  theme(strip.background = element_blank()) +
  coord_flip() -> m6

print(m6)
```
### Task 7
```{r, fig.width=4.5, fig.height=2}
# -------------------------------------------------------
# Vars
num_episodes <- max(result_task7$global_step)
limits <- c(0, 0.85)
breaks <- c(0.0, 0.4, 0.8)

# -------------------------------------------------------
# Tabulate
result_task7 %>%  
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R),
            total_E = last(total_E),
            total_value = last(total_R) + last(total_E),
            total_regret = last(total_regret)) %>% 
  ungroup() %>% 
  group_by(strategy, agent) %>% 
  summarise(median_R = median(total_R), 
            var_R = mad(total_R),
            median_E = median(total_E), 
            var_E = mad(total_E),
            median_total_value = median(total_value), 
            var_total_value = mad(total_value),
            median_regret = median(total_regret),
            var_regret = mad(total_regret)) %>% 
  ungroup() -> tmp

# Reference 
wsls_R <- median((filter(tmp, strategy == "WSLS"))$median_R)
random_R <- median((filter(tmp, strategy == "Random"))$median_R)

# -------------------------------------------------------
# Vis
tmp %>% 
  filter(agent != "Random") %>%
  ggplot(aes(x=agent, y=median_R/num_episodes, color=strategy)) +
  geom_point(size=2.5, alpha=0.8) +
  geom_linerange(aes(
    ymin=(median_R+var_R)/num_episodes, 
    ymax=(median_R-var_R)/num_episodes), 
    alpha=0.4) +
  geom_hline(aes(yintercept=wsls_R/num_episodes), 
             color="chartreuse4",
             size=0.4) +
  geom_hline(aes(yintercept=random_R/num_episodes), 
             color="black",
             size=0.2,
             linetype="dashed") +
  labs(x="", y="Average reward", subtitle = "Task 7 - Unexpected change") +
  scale_y_continuous(limits = limits, breaks = breaks) +
  scale_color_manual("", values = c("black", "darkgrey", "chartreuse4")) +
  theme_pubr(base_size =  10, legend = "none") +
  theme(strip.background = element_blank()) +
  coord_flip() -> m7

print(m7)
```

## Jitter
### Task 2
```{r, fig.width=5, fig.height=3}
# -------------------------------------------------------
# Vars
num_episodes <- max(result_task2$global_step)
limits <- c(50, 200)
breaks <- c(50, 100, 150, 200)

# Vis
result_task2 %>%
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R)) %>% 
  ungroup() -> tmp

# Reference 
wsls_2 <- median((filter(tmp, strategy == "WSLS"))$total_R)
random_2 <- median((filter(tmp, strategy == "Random"))$total_R)

tmp %>% 
  filter(strategy != "Random") %>% 
  ggplot(aes(x=agent, y=total_R)) +
  geom_jitter(width = 0.3, size=0.2, alpha=0.1) +
  stat_summary(fun.y = median, aes(color=strategy), size=0.3) +
  geom_hline(aes(yintercept=wsls_2), 
             color="chartreuse4",
             size=0.4) +
  geom_hline(aes(yintercept=random_2), 
             color="black",
             size=0.2,
             linetype="dashed") +
  labs(x="", y="Total reward") +
  theme_pubr(base_size = 10, legend = "none") +
  theme(panel.spacing = unit(.5, "lines")) +
  theme(strip.text.y = element_text(angle = 0, hjust = -.1)) +
  theme(strip.background = element_blank()) +
  scale_color_manual("", values = c("black", "gray45", "chartreuse4")) +
  labs(x="", y="Total reward", subtitle = "Task 2 - Classic") +
  scale_y_continuous(limits = limits, breaks = breaks) +
  coord_flip() -> j2

print(j2)
```

### Task 3
```{r, fig.width=5, fig.height=3}
# -------------------------------------------------------
# Vars
num_episodes <- max(result_task3$global_step)
limits <- c(500, 1000)
breaks <- c(500, 750, 1000)

result_task3 %>%
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R)) %>% 
  ungroup() -> tmp

# Reference 
wsls_3 <- median((filter(tmp, strategy == "WSLS"))$total_R)
random_3 <- median((filter(tmp, strategy == "Random"))$total_R)

tmp %>% 
  filter(strategy != "Random") %>% 
  ggplot(aes(x=agent, y=total_R)) +
  geom_jitter(width = 0.3, size=0.2, alpha=0.1) +
  stat_summary(fun.y = median, aes(color=strategy), size=0.3) +
  geom_hline(aes(yintercept=wsls_3), 
             color="chartreuse4",
             size=0.4) +
  geom_hline(aes(yintercept=random_3), 
             color="black",
             size=0.2,
             linetype="dashed") +
  labs(x="", y="Total reward") +
  scale_color_manual("", values = c("black", "gray45", "chartreuse4")) +
  labs(x="", y="Total reward", subtitle = "Task 3 - Sparse") +
  scale_y_continuous(limits = limits, breaks = breaks) +
  theme_pubr(base_size = 10, legend = "none") +
  theme(axis.text.y = element_blank()) +
  theme(panel.spacing = unit(.5, "lines")) +
  theme(strip.text.y = element_text(angle = 0, hjust = -.1)) +
  theme(strip.background = element_blank()) +
  coord_flip() -> j3

print(j3)
```

### Task 4
```{r, fig.width=5, fig.height=3}
# -------------------------------------------------------
# Vars
num_episodes <- max(result_task4$global_step)
limits <- c(0, 125)
breaks <- c(0, 25, 50, 75, 100, 125)

result_task4 %>%
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R)) %>% 
  ungroup() -> tmp

# Reference 
wsls_4 <- median((filter(tmp, strategy == "WSLS"))$total_R)
random_4 <- median((filter(tmp, strategy == "Random"))$total_R)

tmp %>% 
  filter(strategy != "Random") %>% 
  ggplot(aes(x=agent, y=total_R)) +
  geom_jitter(width = 0.3, size=0.2, alpha=0.1) +
  stat_summary(fun.y = median, aes(color=strategy), size=0.3) +
  geom_hline(aes(yintercept=wsls_4), 
             color="chartreuse4",
             size=0.4) +
  geom_hline(aes(yintercept=random_4), 
             color="black",
             size=0.2,
             linetype="dashed") +
  labs(x="", y="Total reward") +
  theme_pubr(base_size = 10, legend = "none") +
  theme(panel.spacing = unit(.5, "lines")) +
  theme(strip.text.y = element_text(angle = 0, hjust = -.1)) +
  theme(strip.background = element_blank()) +
  scale_color_manual("", values = c("black", "gray45", "chartreuse4")) +
  labs(x="", y="Total reward", subtitle = "Task 4 - Deception") +
  scale_y_continuous(limits = limits, breaks = breaks) +
  coord_flip() -> j4

print(j4)
```

### Task 5
```{r, fig.width=5, fig.height=3}
# -------------------------------------------------------
# Vars
num_episodes <- max(result_task5$global_step)
limits <- c(0, 500) 
breaks <- c(0, 250, 500)

result_task5 %>%
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R)) %>% 
  ungroup() -> tmp

# Reference 
wsls_5 <- median((filter(tmp, strategy == "WSLS"))$total_R)
random_5 <- median((filter(tmp, strategy == "Random"))$total_R)

tmp %>% 
  filter(strategy != "Random") %>% 
  ggplot(aes(x=agent, y=total_R)) +
  geom_jitter(width = 0.3, size=0.2, alpha=0.1) +
  stat_summary(fun.y = median, aes(color=strategy), size=0.3) +
  geom_hline(aes(yintercept=wsls_5), 
             color="chartreuse4",
             size=0.4) +
  geom_hline(aes(yintercept=random_5), 
             color="black",
             size=0.2,
             linetype="dashed") +
  labs(x="", y="Total reward") +
  theme_pubr(base_size = 10, legend = "none") +
  theme(axis.text.y = element_blank()) +
  theme(panel.spacing = unit(.5, "lines")) +
  theme(strip.text.y = element_text(angle = 0, hjust = -.1)) +
  theme(strip.background = element_blank()) +
  scale_color_manual("", values = c("black", "gray45", "chartreuse4")) +
  labs(x="", y="Total reward", subtitle = "Task 5 - Distraction") +
  scale_y_continuous(limits = limits, breaks = breaks) +
  coord_flip() -> j5

print(j5)
```

### Task 6
```{r, fig.width=5, fig.height=3}
# -------------------------------------------------------
# Vars
num_episodes <- max(result_task6$global_step)
limits <- c(20000, 60000)
breaks <- c(20000, 40000, 60000)

result_task6 %>%
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R)) %>% 
  ungroup() -> tmp

# Reference 
wsls_6 <- median((filter(tmp, strategy == "WSLS"))$total_R)
random_6 <- median((filter(tmp, strategy == "Random"))$total_R)

tmp %>% 
  filter(strategy != "Random") %>% 
  ggplot(aes(x=agent, y=total_R)) +
  geom_jitter(width = 0.3, size=0.2, alpha=0.1) +
  stat_summary(fun.y = median, aes(color=strategy), size=0.3) +
  geom_hline(aes(yintercept=wsls_6), 
             color="chartreuse4",
             size=0.4) +
  geom_hline(aes(yintercept=random_6), 
             color="black",
             size=0.2,
             linetype="dashed") +
  labs(x="", y="Total reward") +
  theme_pubr(base_size = 10, legend = "none") +
  theme(panel.spacing = unit(.5, "lines")) +
  theme(strip.text.y = element_text(angle = 0, hjust = -.1)) +
  theme(strip.background = element_blank()) +
  scale_color_manual("", values = c("black", "gray45", "chartreuse4")) +
  labs(x="", y="Total reward", subtitle = "Task 6 - High dim.") +
  scale_y_continuous(limits = limits, breaks = breaks) +
  coord_flip() -> j6

print(j6)
```

### Task 7
```{r, fig.width=5, fig.height=3}
# -------------------------------------------------------
# Vars
num_episodes <- max(result_task7$global_step)
limits <- c(4000, 8000)
breaks <- c(4000, 6000, 8000)

result_task7 %>%
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R)) %>% 
  ungroup() -> tmp

# Reference 
wsls_7 <- median((filter(tmp, strategy == "WSLS"))$total_R)
random_7 <- median((filter(tmp, strategy == "Random"))$total_R)

tmp %>% 
  filter(strategy != "Random") %>% 
  ggplot(aes(x=agent, y=total_R)) +
  geom_jitter(width = 0.3, size=0.3, alpha=0.1) +
  stat_summary(fun.y = median, aes(color=strategy), size=0.3) +
  geom_hline(aes(yintercept=wsls_7), 
             color="chartreuse4",
             size=0.4) +
  geom_hline(aes(yintercept=random_7), 
             color="black",
             size=0.2,
             linetype="dashed") +
  labs(x="", y="Total reward") +
  theme_pubr(base_size = 10, legend = "none") +
  theme(panel.spacing = unit(.5, "lines")) +
  theme(strip.text.y = element_text(angle = 0, hjust = -.1)) +
  theme(strip.background = element_blank()) +
  theme(axis.text.y = element_blank()) +
  scale_color_manual("", values = c("black", "gray45", "chartreuse4")) +
  labs(x="", y="Total reward", subtitle = "Task 7 - Unexpected") +
  scale_y_continuous(limits = limits, breaks = breaks) +
  coord_flip() -> j7

print(j7)
```

## Boxplot
### Task 2
```{r, fig.width=5, fig.height=3}
# -------------------------------------------------------
# Vars
num_episodes <- max(result_task2$global_step)
limits <- c(0, 200)
breaks <- c(0.0, 100, 200)

# Vis
result_task2 %>%
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R)) %>% 
  ungroup() -> tmp

# Reference 
wsls_2 <- median((filter(tmp, strategy == "WSLS"))$total_R)
random_2 <- median((filter(tmp, strategy == "Random"))$total_R)

tmp %>% 
  filter(strategy != "Random") %>% 
  ggplot(aes(x=agent, y=total_R, color=strategy)) +
  geom_boxplot(width=0.4) +
  geom_hline(aes(yintercept=wsls_2), 
             color="chartreuse4",
             size=0.4) +
  geom_hline(aes(yintercept=random_2), 
             color="black",
             size=0.2,
             linetype="dashed") +
  labs(x="", y="Total reward") +
  theme_pubr(base_size = 10, legend = "none") +
  theme(panel.spacing = unit(.5, "lines")) +
  theme(strip.text.y = element_text(angle = 0, hjust = -.1)) +
  theme(strip.background = element_blank()) +
  scale_color_manual("", values = c("black", "gray45", "chartreuse4")) +
  labs(x="", y="Total reward", subtitle = "Task 2 - Classic") +
  scale_y_continuous(limits = limits, breaks = breaks) +
  coord_flip() -> b2

print(b2)
```

### Task 3
```{r, fig.width=5, fig.height=3}
# -------------------------------------------------------
# Vars
num_episodes <- max(result_task3$global_step)
limits <- c(0, 1100)
breaks <- c(0, 500, 1000)

result_task3 %>%
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R)) %>% 
  ungroup() -> tmp

# Reference 
wsls_3 <- median((filter(tmp, strategy == "WSLS"))$total_R)
random_3 <- median((filter(tmp, strategy == "Random"))$total_R)

tmp %>% 
  filter(strategy != "Random") %>% 
  ggplot(aes(x=agent, y=total_R, color=strategy)) +
  geom_boxplot(width=0.4) +
  geom_hline(aes(yintercept=wsls_3), 
             color="chartreuse4",
             size=0.4) +
  geom_hline(aes(yintercept=random_3), 
             color="black",
             size=0.2,
             linetype="dashed") +
  labs(x="", y="Total reward") +
  scale_color_manual("", values = c("black", "gray45", "chartreuse4")) +
  labs(x="", y="Total reward", subtitle = "Task 3 - Sparse") +
  scale_y_continuous(limits = limits, breaks = breaks) +
  theme_pubr(base_size = 10, legend = "none") +
  theme(axis.text.y = element_blank()) +
  theme(panel.spacing = unit(.5, "lines")) +
  theme(strip.text.y = element_text(angle = 0, hjust = -.1)) +
  theme(strip.background = element_blank()) +
  coord_flip() -> b3

print(b3)
```

### Task 4
```{r, fig.width=5, fig.height=3}
# -------------------------------------------------------
# Vars
num_episodes <- max(result_task4$global_step)
limits <- c(0, 150)
breaks <- c(0, 75, 150)

result_task4 %>%
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R)) %>% 
  ungroup() -> tmp

# Reference 
wsls_4 <- median((filter(tmp, strategy == "WSLS"))$total_R)
random_4 <- median((filter(tmp, strategy == "Random"))$total_R)

tmp %>% 
  filter(strategy != "Random") %>% 
  ggplot(aes(x=agent, y=total_R, color=strategy)) +
  geom_boxplot(width=0.4) +
  geom_hline(aes(yintercept=wsls_4), 
             color="chartreuse4",
             size=0.4) +
  geom_hline(aes(yintercept=random_4), 
             color="black",
             size=0.2,
             linetype="dashed") +
  labs(x="", y="Total reward") +
  theme_pubr(base_size = 10, legend = "none") +
  theme(panel.spacing = unit(.5, "lines")) +
  theme(strip.text.y = element_text(angle = 0, hjust = -.1)) +
  theme(strip.background = element_blank()) +
  scale_color_manual("", values = c("black", "gray45", "chartreuse4")) +
  labs(x="", y="Total reward", subtitle = "Task 4 - Deception") +
  scale_y_continuous(limits = limits, breaks = breaks) +
  coord_flip() -> b4

print(b4)
```

### Task 5
```{r, fig.width=5, fig.height=3}
# -------------------------------------------------------
# Vars
num_episodes <- max(result_task5$global_step)
limits <- c(0, 500) 
breaks <- c(0, 250, 500)

result_task5 %>%
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R)) %>% 
  ungroup() -> tmp

# Reference 
wsls_5 <- median((filter(tmp, strategy == "WSLS"))$total_R)
random_5 <- median((filter(tmp, strategy == "Random"))$total_R)

tmp %>% 
  filter(strategy != "Random") %>% 
  ggplot(aes(x=agent, y=total_R, color=strategy)) +
  geom_boxplot(width=0.4) +
  geom_hline(aes(yintercept=wsls_5), 
             color="chartreuse4",
             size=0.4) +
  geom_hline(aes(yintercept=random_5), 
             color="black",
             size=0.2,
             linetype="dashed") +
  labs(x="", y="Total reward") +
  theme_pubr(base_size = 10, legend = "none") +
  theme(axis.text.y = element_blank()) +
  theme(panel.spacing = unit(.5, "lines")) +
  theme(strip.text.y = element_text(angle = 0, hjust = -.1)) +
  theme(strip.background = element_blank()) +
  scale_color_manual("", values = c("black", "gray45", "chartreuse4")) +
  labs(x="", y="Total reward", subtitle = "Task 5 - Distraction") +
  scale_y_continuous(limits = limits, breaks = breaks) +
  coord_flip() -> b5

print(b5)
```

### Task 6
```{r, fig.width=5, fig.height=3}
# -------------------------------------------------------
# Vars
num_episodes <- max(result_task6$global_step)
limits <- c(0, 60000)
breaks <- c(0, 30000, 60000)

result_task6 %>%
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R)) %>% 
  ungroup() -> tmp

# Reference 
wsls_6 <- median((filter(tmp, strategy == "WSLS"))$total_R)
random_6 <- median((filter(tmp, strategy == "Random"))$total_R)

tmp %>% 
  filter(strategy != "Random") %>% 
  ggplot(aes(x=agent, y=total_R, color=strategy)) +
  geom_boxplot(width=0.4) +
  geom_hline(aes(yintercept=wsls_6), 
             color="chartreuse4",
             size=0.4) +
  geom_hline(aes(yintercept=random_6), 
             color="black",
             size=0.2,
             linetype="dashed") +
  labs(x="", y="Total reward") +
  theme_pubr(base_size = 10, legend = "none") +
  theme(panel.spacing = unit(.5, "lines")) +
  theme(strip.text.y = element_text(angle = 0, hjust = -.1)) +
  theme(strip.background = element_blank()) +
  scale_color_manual("", values = c("black", "gray45", "chartreuse4")) +
  labs(x="", y="Total reward", subtitle = "Task 6 - High dim.") +
  scale_y_continuous(limits = limits, breaks = breaks) +
  coord_flip() -> b6

print(b6)
```

### Task 7
```{r, fig.width=5, fig.height=3}
# -------------------------------------------------------
# Vars
num_episodes <- max(result_task7$global_step)
limits <- c(0, 12000)
breaks <- c(0, 6000, 12000)

result_task7 %>%
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R)) %>% 
  ungroup() -> tmp

# Reference 
wsls_7 <- median((filter(tmp, strategy == "WSLS"))$total_R)
random_7 <- median((filter(tmp, strategy == "Random"))$total_R)

tmp %>% 
  filter(strategy != "Random") %>% 
  ggplot(aes(x=agent, y=total_R, color=strategy)) +
  geom_boxplot(width=0.4) +
  geom_hline(aes(yintercept=wsls_7), 
             color="chartreuse4",
             size=0.4) +
  geom_hline(aes(yintercept=random_7), 
             color="black",
             size=0.2,
             linetype="dashed") +
  labs(x="", y="Total reward") +
  theme_pubr(base_size = 10, legend = "none") +
  theme(panel.spacing = unit(.5, "lines")) +
  theme(strip.text.y = element_text(angle = 0, hjust = -.1)) +
  theme(strip.background = element_blank()) +
  theme(axis.text.y = element_blank()) +
  scale_color_manual("", values = c("black", "gray45", "chartreuse4")) +
  labs(x="", y="Total reward", subtitle = "Task 7 - Unexpected") +
  scale_y_continuous(limits = limits, breaks = breaks) +
  coord_flip() -> b7

print(b7)
```

## Overall
```{r, message=FALSE, warning=FALSE, fig.width=5, fig.height=5.0}
# Sum
result_task2 %>%  
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R)) %>% 
  ungroup() %>% 
  group_by(strategy, agent) %>% 
  summarise(median_R = median(total_R)) -> tmp
# Norm
tmp %>%
  group_by(agent, strategy) %>%
  mutate(median_R = median_R / max(tmp$median_R)) ->
  tmp2

# Sum
result_task3 %>%  
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R)) %>% 
  ungroup() %>% 
  group_by(strategy, agent) %>% 
  summarise(median_R = median(total_R)) -> tmp
# Norm
tmp %>%
  group_by(agent, strategy) %>%
  mutate(median_R = median_R / max(tmp$median_R)) ->
  tmp3

result_task4 %>%  
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R)) %>% 
  ungroup() %>% 
  group_by(strategy, agent) %>% 
  summarise(median_R = median(total_R)) -> tmp
# Norm
tmp %>%
  group_by(agent, strategy) %>%
  mutate(median_R = median_R / max(tmp$median_R)) ->
  tmp4

result_task5 %>%  
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R)) %>% 
  ungroup() %>% 
  group_by(strategy, agent) %>% 
  summarise(median_R = median(total_R)) -> tmp
# Norm
tmp %>%
  group_by(agent, strategy) %>%
  mutate(median_R = median_R / max(tmp$median_R)) ->
  tmp5

result_task6 %>%  
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R)) %>% 
  ungroup() %>% 
  group_by(strategy, agent) %>% 
  summarise(median_R = median(total_R)) -> tmp
# Norm
tmp %>%
  group_by(agent, strategy) %>%
  mutate(median_R = median_R / max(tmp$median_R)) ->
  tmp6

result_task7 %>%  
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R)) %>% 
  ungroup() %>% 
  group_by(strategy, agent) %>% 
  summarise(median_R = median(total_R)) -> tmp
# Norm
tmp %>%
  group_by(agent, strategy) %>%
  mutate(median_R = median_R / max(tmp$median_R)) ->
  tmp7


# todo = rest of tmps
# Join
# bind_rows(tmp2, tmp3, tmp4, tmp5, tmp6, tmp7) %>%
bind_rows(tmp2, tmp3, tmp6, tmp7) %>%
  group_by(agent, strategy) %>%
  summarise(var_R = mad(median_R),
            median_R = median(median_R)) ->
  tmp

# bind_rows(tmp2, tmp3, tmp4, tmp5, tmp6, tmp7) ->
#   tmp_r

# -------------------------------------------------------------
# Our value
wsls_s <- filter(tmp, strategy == "WSLS")$median_R
random_s <-  filter(tmp, strategy == "Random")$median_R

tmp %>% 
  filter(agent != "Random") %>% 
  ggplot(aes(
    x = agent,
    y = median_R,
    color = factor(strategy)
  )) +
  geom_point(size=2) +
  geom_linerange(aes(
    ymin = (median_R + var_R),
    ymax = (median_R - var_R)
  ), alpha = 0.4) +
  geom_hline(aes(yintercept=wsls_s), 
             color="chartreuse4",
             size=0.4) +
  geom_hline(aes(yintercept=random_s), 
             color="black",
             size=0.2,
             linetype="dashed") +
  theme_pubr(base_size = 12, legend = "none") +
  scale_color_manual("", values = c("black", "darkgrey", "chartreuse4")) +
  labs(
    x = "",
    y = "Normalized reward",
    subtitle = "Overall",
  ) +
  scale_y_continuous(limits = c(0.5, 1.1), breaks = c(0.5, 0.75, 1.0)) +
  coord_flip() ->
  perf2

print(perf2)
```

# Join regular bandits
```{r, fig.width=9, fig.height=5.0}
# layout <- "
# AAAAABBBCCC
# AAAAABBBCCC
# AAAAABBBCCC
# AAAAADDDEEE
# AAAAADDDEEE
# AAAAADDDEEE
# #####FFFGGG
# #####FFFGGG
# #####FFFGGG
# "
# perf <- perf2 + p2 + p3 + p4 + p5 + p6 + p7 +

layout <- "
AAAAABBBCCC
AAAAABBBCCC
AAAAABBBCCC
AAAAADDDEEE
AAAAADDDEEE
AAAAADDDEEE
"
perf_reg <- perf2 + j2 + j3 + j6 + j7 +
  plot_layout(design = layout, guides = "collect") +
  plot_annotation(
    title = "Reward collection performance with standard bandits",
                  theme = theme_pubr(base_size = 14, legend = "right"),
                  tag_levels = "a", tag_suffix = ".")
print(perf_reg)

# Save
name <- "img/performance1"
ggsave(paste(name, ".pdf", sep=""), plot=perf_reg, width = 9, height = 5)
```
# Join - deception and ditraction
```{r, fig.width=7, fig.height=3}
perf_dd <- j4 + j5 +
  plot_annotation(
    title = "Performance with deception or distraction",
                  theme = theme_pubr(base_size = 14, legend = "right"),
                  tag_levels = "a", tag_suffix = ".")
print(perf_dd)

# Save
name <- "img/performance2"
ggsave(paste(name, ".pdf", sep=""), plot=perf_dd, width = 7, height = 3)
```