---
title: "Reanalysis of parameter robustness"
output: html_notebook
---

# Library
```{r, message=FALSE}
library(zoo)
library(ggplot2)
library(tidyr)
library(ggpubr)
library(patchwork)
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
# library(MASS) 
library(scales)
library(patchwork)
options(scipen=1000000)

# Load load_result and other helpful functions
source("utils.R")

# --- Main path to all data ---
data_path <- "~/Code/infomercial/data"
```

# Load data
## Task 2 - BanditOneHigh4
```{r, message=FALSE}
# -------------------------------------------------------------
task_name <- "BanditOneHigh4"
task_code <- 2

rank_names <- c(
  "exp595_sorted.csv",
  # "exp596_sorted.csv",
  # "exp597_sorted.csv",
  "exp598_sorted.csv",
  "exp599_sorted.csv",
  "exp600_sorted.csv",
  "exp601_sorted.csv",
  "exp602_sorted.csv",
  "exp603_sorted.csv"
)

agent_names <- c(
  "E-explore (IG)",
  # "Random",
  # "Decay",
  "Reward",
  "Reward+IG",
  "Reward+Novelty",
  "Reward+Entropy",
  "Reward+EB",
  "Reward+UCB"
)

class_names <- c("E-explore (IG)",
                 # "Random",
                 # "Random",
                 "Reward",
                 "Mixed",
                 "Mixed",
                 "Mixed",
                 "Mixed",
                 "Mixed")

tune_task2 <- NULL
for (i in 1:length(rank_names)) {
  # Meta
  rank_name <- rank_names[i]
  agent_name <- agent_names[i]
  class_name <- class_names[i]
  
  # Get run?
  if (agent_name == "Random") {
    param_codes <- c(0)
    run_codes <- 1:100
  } else{
    param_codes <- 0:9
    run_codes <- 1:10
  }
  
  # Load and add meta
  tmp <-
    read_csv(paste(data_path, rank_name, sep = "/"), show_col_types = FALSE)
  tmp$exp <- rank_name
  tmp$agent <- agent_name
  tmp$task <- task_name
  tmp$task_code <- task_code
  tmp$strategy <- class_name
  
  # Save
  tune_task2 <- bind_rows(tune_task2, tmp)
}

# Order factors for later vis
tune_task2$agent <-
  factor(tune_task2$agent, levels = rev(agent_names))
tune_task2$strategy <-
  factor(tune_task2$strategy,
         levels = c("E-explore (IG)", "Reward", "Mixed"))
```

## Task 3 - BanditHardAndSparse10
```{r, message=FALSE}
task_name <- "BanditHardAndSparse10"
task_code <- 3

rank_names <- c(
  "exp387_sorted.csv",
  # "exp385_sorted.csv",
  # "exp386_sorted.csv",
  "exp485_sorted.csv",
  "exp388_sorted.csv",
  "exp484_sorted.csv",
  "exp487_sorted.csv",
  "exp486_sorted.csv",
  "exp531_sorted.csv"
)

agent_names <- c(
  "E-explore (IG)",
  # "Random",
  # "Decay",
  "Reward",
  "Reward+IG",
  "Reward+Novelty",
  "Reward+Entropy",
  "Reward+EB",
  "Reward+UCB"
)

class_names <- c("E-explore (IG)",
                 # "Random",
                 # "Random",
                 "Reward",
                 "Mixed",
                 "Mixed",
                 "Mixed",
                 "Mixed",
                 "Mixed")

tune_task3 <- NULL
for (i in 1:length(rank_names)) {
  rank_name <- rank_names[i]
  agent_name <- agent_names[i]
  class_name <- class_names[i]
  if (agent_name == "Random") {
    param_codes <- c(0)
    run_codes <- 1:100
  } else{
    param_codes <- 0:9
    run_codes <- 1:10
  }
  
  tmp <-
    read_csv(paste(data_path, rank_name, sep = "/"), show_col_types = FALSE)
  
  tmp$exp <- rank_name
  tmp$agent <- agent_name
  tmp$task <- task_name
  tmp$task_code <- task_code
  tmp$strategy <- class_name
  
  tune_task3 <- bind_rows(tune_task3, tmp)
}

# Order factors for later vis
tune_task3$agent <-
  factor(tune_task3$agent, levels = agent_names)
tune_task3$strategy <-
  factor(tune_task3$strategy,
         levels = c("E-explore (IG)", "Reward", "Mixed"))
```

## Task 4 - DeceptiveBanditOneHigh10
```{r, message=FALSE}
task_name <- "DeceptiveBanditOneHigh10"
task_code <- 4

rank_names <- c(
  "exp391_sorted.csv",
  # "exp389_sorted.csv",
  # "exp390_sorted.csv",
  "exp489_sorted.csv",
  "exp392_sorted.csv",
  "exp488_sorted.csv",
  "exp491_sorted.csv",
  "exp490_sorted.csv",
  "exp532_sorted.csv"
)

agent_names <- c(
  "E-explore (IG)",
  # "Random",
  # "Decay",
  "Reward",
  "Reward+IG",
  "Reward+Novelty",
  "Reward+Entropy",
  "Reward+EB",
  "Reward+UCB"
)

class_names <- c("E-explore (IG)",
                 # "Random",
                 # "Random",
                 "Reward",
                 "Mixed",
                 "Mixed",
                 "Mixed",
                 "Mixed",
                 "Mixed")

tune_task4 <- NULL
for (i in 1:length(rank_names)) {
  rank_name <- rank_names[i]
  agent_name <- agent_names[i]
  class_name <- class_names[i]
  if (agent_name == "Random") {
    param_codes <- c(0)
    run_codes <- 1:100
  } else{
    param_codes <- 0:9
    run_codes <- 1:10
  }
  
  tmp <-
    read_csv(paste(data_path, rank_name, sep = "/"), show_col_types = FALSE)
  
  tmp$exp <- rank_name
  tmp$agent <- agent_name
  tmp$task <- task_name
  tmp$task_code <- task_code
  tmp$strategy <- class_name
  
  tune_task4 <- bind_rows(tune_task4, tmp)
}

# Order factors for later vis
tune_task4$agent <-
  factor(tune_task4$agent, levels = agent_names)
tune_task4$strategy <-
  factor(tune_task4$strategy,
         levels = c("E-explore (IG)", "Reward", "Mixed"))
```

## Task 5 - DistractionBanditOneHigh10
```{r, message=FALSE}
task_name <- "DistractionBanditOneHigh10"
task_code <- 5

rank_names <- c(
  "exp460_sorted.csv",
  # "exp458_sorted.csv",
  # "exp459_sorted.csv",
  "exp493_sorted.csv",
  "exp461_sorted.csv",
  "exp492_sorted.csv",
  "exp495_sorted.csv",
  "exp494_sorted.csv",
  "exp533_sorted.csv"
)

agent_names <- c(
  "E-explore (IG)",
  # "Random",
  # "Decay",
  "Reward",
  "Reward+IG",
  "Reward+Novelty",
  "Reward+Entropy",
  "Reward+EB",
  "Reward+UCB"
)

class_names <- c("E-explore (IG)",
                 # "Random",
                 # "Random",
                 "Reward",
                 "Mixed",
                 "Mixed",
                 "Mixed",
                 "Mixed",
                 "Mixed")

tune_task5 <- NULL
for (i in 1:length(rank_names)) {
  rank_name <- rank_names[i]
  agent_name <- agent_names[i]
  class_name <- class_names[i]
  if (agent_name == "Random") {
    param_codes <- c(0)
    run_codes <- 1:100
  } else{
    param_codes <- 0:9
    run_codes <- 1:10
  }
  
  tmp <-
    read_csv(paste(data_path, rank_name, sep = "/"), show_col_types = FALSE)
  
  tmp$exp <- rank_name
  tmp$agent <- agent_name
  tmp$task <- task_name
  tmp$task_code <- task_code
  tmp$strategy <- class_name
  
  tune_task5 <- bind_rows(tune_task5, tmp)
}

# Order factors for later vis
tune_task5$agent <-
  factor(tune_task5$agent, levels = agent_names)
tune_task5$strategy <-
  factor(tune_task5$strategy,
         levels = c("E-explore (IG)", "Reward", "Mixed"))
```

## Task 6 - BanditUniform121
```{r, message=FALSE}
task_name <- "BanditUniform121"
task_code <- 6

rank_names <- c(
  "exp604_sorted.csv",
  # "exp605_sorted.csv",
  # "exp606_sorted.csv",
  "exp607_sorted.csv",
  "exp608_sorted.csv",
  "exp609_sorted.csv",
  "exp610_sorted.csv",
  "exp611_sorted.csv",
  "exp612_sorted.csv"
)

agent_names <- c(
  "E-explore (IG)",
  # "Random",
  # "Decay",
  "Reward",
  "Reward+IG",
  "Reward+Novelty",
  "Reward+Entropy",
  "Reward+EB",
  "Reward+UCB"
)

class_names <- c("E-explore (IG)",
                 # "Random",
                 # "Random",
                 "Reward",
                 "Mixed",
                 "Mixed",
                 "Mixed",
                 "Mixed",
                 "Mixed")

tune_task6 <- NULL
for (i in 1:length(rank_names)) {
  rank_name <- rank_names[i]
  agent_name <- agent_names[i]
  class_name <- class_names[i]
  if (agent_name == "Random") {
    param_codes <- c(0)
    run_codes <- 1:100
  } else{
    param_codes <- 0:9
    run_codes <- 1:10
  }
  
  tmp <-
    read_csv(paste(data_path, rank_name, sep = "/"), show_col_types = FALSE)
  
  tmp$exp <- rank_name
  tmp$agent <- agent_name
  tmp$task <- task_name
  tmp$task_code <- task_code
  tmp$strategy <- class_name
  
  tune_task6 <- bind_rows(tune_task6, tmp)
}

# Order factors for later vis
tune_task6$agent <-
  factor(tune_task6$agent, levels = agent_names)
tune_task6$strategy <-
  factor(tune_task6$strategy,
         levels = c("E-explore (IG)", "Reward", "Mixed"))
```

## Join
```{r, message=FALSE}
tune_task <-
  bind_rows(tune_task2, tune_task3, tune_task4, tune_task5, tune_task6)
```

# Vis
## Overall - tasks and parameters
```{r, fig.width=6, fig.height=3}
# ---------------------------------------------------------
# Sum
tune_task2 %>%
  group_by(agent, strategy) %>%
  summarise(total_R = sum(total_R)) ->
  tmp2
# Norm
tmp2 %>% 
  group_by(agent) %>%
  mutate(total_R = total_R / max(tmp2$total_R)) ->
  tmp2

# Sum
tune_task3 %>%
  group_by(agent, strategy) %>%
  summarise(total_R = sum(total_R)) ->
  tmp3
# Norm
tmp3 %>% 
  group_by(agent) %>%
  mutate(total_R = total_R / max(tmp3$total_R)) ->
  tmp3

# Sum
tune_task4 %>%
  group_by(agent, strategy) %>%
  summarise(total_R = sum(total_R)) ->
  tmp4
# Norm
tmp4 %>% 
  group_by(agent) %>%
  mutate(total_R = total_R / max(tmp4$total_R)) ->
  tmp4

# Sum
tune_task5 %>%
  group_by(agent, strategy) %>%
  summarise(total_R = sum(total_R)) ->
  tmp5
# Norm
tmp5 %>% 
  group_by(agent) %>%
  mutate(total_R = total_R / max(tmp5$total_R)) ->
  tmp5

# Sum
tune_task6 %>%
  group_by(agent, strategy) %>%
  summarise(total_R = sum(total_R)) ->
  tmp6
# Norm
tmp6 %>% 
  group_by(agent) %>%
  mutate(total_R = total_R / max(tmp6$total_R)) ->
  tmp6

# Join
bind_rows(tmp2, tmp3, tmp4, tmp5, tmp6) %>%
  group_by(agent, strategy) %>%
  summarise(median_R=median(total_R),
         var_R=mad(total_R)) ->
  tmp

# Our value
wsls_R <- filter(tmp, strategy == "E-explore (IG)")$median_R

# ---------------------------------------------------------
tmp %>%
  ggplot(aes(
    x = agent,
    y = median_R,
    color = factor(strategy)
  )) +
  geom_point(size=4) +
  geom_linerange(aes(
    ymin = (median_R + var_R),
    ymax = (median_R - var_R)
  ), alpha = 0.4) +
  geom_hline(aes(yintercept=wsls_R), 
             color="chartreuse4",
             size=0.5) +
  theme_pubr(base_size = 12, legend = "none") +
  scale_color_manual("", values = c("chartreuse4", "darkgrey", "black")) +
  labs(
    x = "",
    y = "Normalized reward",
    # tag = "a.",
    subtitle = "Overall"
  ) +
  scale_y_continuous(limits = c(0, 1.2), breaks = c(0, 0.5, 1)) +
  coord_flip() -> p1

# Disp
robust1 <- p1
print(robust1)

# ---------------------------------------------------------
# Write pdf
name <- "img/robust1"
ggsave(paste(name, ".pdf", sep=""), plot=robust1, width = 6, height = 3)
```
## Tasks, by rank
```{r, fig.width=6, fig.height=6.0}
# -------------------------------------------------
# 2
max_tune2 <- max(tune_task2$total_R)

tune_task2 %>%
  ggplot(aes(
    x = index + 1,
    y = total_R / max_tune2,
    group = agent,
    color = strategy
  )) +
  geom_line(size = 1.2, alpha = 0.9) +
  labs(
    x = "Ranked parameters",
    y = "Norm. reward",
    subtitle = "Task 2 - Classic",
    # tag = "a."
  ) +
  theme_pubr(base_size = 12) +
  theme(legend.position = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.text.y = element_text(angle = 0, hjust = 1)) +
  theme(strip.text.y = element_blank()) +
  scale_color_manual("", values = c("chartreuse4", "darkgrey", "black")) +
  scale_x_continuous(breaks = c(0, 500, 1000)) +
  scale_y_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1)) -> p2

# -------------------------------------------------
# 3
max_tune3 <- max(tune_task3$total_R)

tune_task3 %>%
  ggplot(aes(
    x = index + 1,
    y = total_R / max_tune3,
    group = agent,
    color = strategy
  )) +
  geom_line(size = 1.2, alpha = 0.9) +
  labs(
    x = "Ranked parameters",
    y = "Norm. reward",
    subtitle = "Task 2 - Sparse",
    # tag = "a."
  ) +
  theme_pubr(base_size = 12) +
  theme(legend.position = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.text.y = element_text(angle = 0, hjust = 1)) +
  theme(strip.text.y = element_blank()) +
  scale_color_manual("", values = c("chartreuse4", "darkgrey", "black")) +
  scale_x_continuous(breaks = c(0, 500, 1000)) +
  scale_y_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1)) -> p3

# -------------------------------------------------
# 4
max_tune4 <- max(tune_task3$total_R)

tune_task4 %>%
  ggplot(aes(
    x = index + 1,
    y = total_R / max_tune4,
    group = agent,
    color = strategy
  )) +
  geom_line(size = 1.2, alpha = 0.9) +
  labs(
    x = "Ranked parameters",
    y = "Norm. reward",
    subtitle = "Task 4 - Distraction",
    # tag = "a."
  ) +
  theme_pubr(base_size = 12) +
  theme(legend.position = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.text.y = element_text(angle = 0, hjust = 1)) +
  theme(strip.text.y = element_blank()) +
  scale_color_manual("", values = c("chartreuse4", "darkgrey", "black")) +
  scale_x_continuous(breaks = c(0, 500, 1000)) +
  scale_y_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1)) -> p4

# -------------------------------------------------
# 5
max_tune5 <- max(tune_task5$total_R)

tune_task5 %>%
  ggplot(aes(
    x = index + 1,
    y = total_R / max_tune5,
    group = agent,
    color = strategy
  )) +
  geom_line(size = 1.2, alpha = 0.9) +
  labs(
    x = "Ranked parameters",
    y = "Norm. reward",
    subtitle = "Task 5 - Deception",
    # tag = "a."
  ) +
  theme_pubr(base_size = 12) +
  theme(legend.position = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.text.y = element_text(angle = 0, hjust = 1)) +
  theme(strip.text.y = element_blank()) +
  scale_color_manual("", values = c("chartreuse4", "darkgrey", "black")) +
  scale_x_continuous(breaks = c(0, 500, 1000)) +
  scale_y_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1)) -> p5


# -------------------------------------------------
# 6
max_tune6 <- max(tune_task6$total_R)

tune_task6 %>%
  ggplot(aes(
    x = index + 1,
    y = total_R / max_tune6,
    group = agent,
    color = factor(strategy)
  )) +
  geom_line(size = 1.2, alpha = 0.9) +
  labs(
    x = "Ranked parameters",
    y = "Norm. reward",
    subtitle = "Task 6 - High dimensional",
    # tag = "b."
  ) +
  theme_pubr(base_size = 12) +
  theme(legend.position = "right") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.text.y = element_text(angle = 0, hjust = 1)) +
  scale_color_manual("Strategy",
                     values = c("chartreuse4", "darkgrey", "black")) +
  scale_x_continuous(breaks = c(0, 500, 1000)) +
  scale_y_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1)) -> p6

robust2 <- (p2 + p3) / (p4 + p5) / (p6 + plot_spacer()) 
print(robust2)

# ---
# Write pdf
name <- "img/robust2"
ggsave(paste(name, ".pdf", sep=""), plot=robust2, width = 6, height = 3)
```
## Join 1-2
```{r, fig.width=11, fig.height=8.0}
layout <- "
AAAAABBBBCCCC
AAAAABBBBCCCC
AAAAABBBBCCCC
AAAAADDDDEEEE
AAAAADDDDEEEE
AAAAADDDDEEEE
#####FFFFGGGG
#####FFFFGGGG
#####FFFFGGGG
"

robust <- robust1 + p2 + p3 + p4 + p5 + p6 + guide_area() +
  plot_layout(design = layout, guides = "collect") +
  plot_annotation(title = "Robustness of bandit exploration strategy",
                  theme = theme_pubr(base_size = 14, legend = "right"),
                  tag_levels = "a", tag_suffix = ".")
print(robust)

# Save
name <- "img/robust"
ggsave(paste(name, ".pdf", sep=""), plot=robust, width = 11, height = 8)
```