---
title: "Task 7 - BanditChange121 - Top10 results"
output: html_notebook
---

# Library
```{r, message=FALSE}
library(zoo)
library(ggplot2)
library(ggpubr)
library(patchwork)
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
# library(MASS) 
library(scales)
library(patchwork)
options(scipen=1000000)

# Load load_result and other helpful functions
source("utils.R")

# --- Main path to all data ---
data_path <- "~/Code/infomercial/data"
```

# Load data
## Vars
```{r, message=FALSE, warning=FALSE}
# -------------------------------------------------------------
task_name <- "BanditChange121"
task_code <- 7
num_episodes <- 12100
# num_episodes <- 121*50

# Set axis
limits <- c(0, 0.8)
breaks <- c(0.0, 0.4, 0.8)

# The overestimate due to E0
num_arms <- 121
E_bias <- log(num_arms) * num_arms 

exp_names <- c("exp585",
               # "exp586", 
               # "exp587", 
               "exp588", 
               "exp589",
               "exp590", 
               "exp591", 
               "exp592", 
               "exp593", 
               "exp594")
```

## Load
```{r, message=FALSE, warning=FALSE}
agent_names <- c(
  "Curiosity (Info.)", 
  # "Random/Greedy", 
  # "Decay/Greedy", 
  "Random",
  "Reward", 
  "Reward+Info.", 
  "Reward+Novelty", 
  "Reward+Entropy", 
  "Reward+EB",
  "Reward+UCB")

class_names <- c(
  "Dual value (WSLS)", 
  # "Random",
  # "Random",
  "Random",
  "Single value",
  "Single value",
  "Single value",
  "Single value",
  "Single value",
  "Single value",
  "Single value"
)

file_names <- c("action", 
                "total_R",
                "total_E",
                "policy",
                "regret",
                "total_regret")

result_task7 <- NULL
for(i in 1:length(exp_names)){
  exp_name <- exp_names[i]
  agent_name <- agent_names[i]
  class_name <- class_names[i]
  if (agent_name == "Random"){
    param_codes <- c(0)
    run_codes <- 1:100
  } else{
    param_codes <- 0:9
    run_codes <- 1:10
  }
  
  tmp <- load_result(
    exp_name, param_codes, run_codes, file_names, n_max=num_episodes+1)
  
  tmp %>% 
    filter(global_step <= num_episodes) -> tmp
  tmp$exp <- exp_name
  tmp$agent <- agent_name
  tmp$task <- task_name
  tmp$task_code <- task_code
  tmp$strategy <- class_name
  tmp$num_episodes <- num_episodes
  
  result_task7 <- bind_rows(result_task7, tmp)
}

# ----------------------------------------------------------------------------
# post-process
# Force order
result_task7$agent <- factor(result_task7$agent, levels=rev(agent_names))

# Remove E_bias
result_task7$total_E <- result_task7$total_E - E_bias
result_task7$total_E[result_task7$total_E < 0] <- 0
```


# Summary, by strategy
## Boxplot
```{r, fig.width=4.5, fig.height=3.5}
result_task7 %>% 
  # filter(agent != "Random") %>%
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R),
            total_E = last(total_E),
            total_regret = last(total_regret)) %>% 
  ungroup() -> tmp


# Med R for curiosity
wsls_R <- median((filter(tmp, strategy == "Dual value (WSLS)"))$total_R)
random_R <- median((filter(tmp, strategy == "Random"))$total_R)

tmp %>% 
  filter(strategy == "Dual value (WSLS)") %>% 
  mutate(
    color = ifelse(strategy == "Dual value (WSLS)", "chartreuse4", "black")) %>%
  ggplot(aes(x=agent, y=total_R/num_episodes, color=color)) +
  geom_boxplot(outlier.size = 0.2, width=0.5) +
  geom_hline(aes(yintercept=random_R/num_episodes), 
             color="darkgrey",
             size=0.5) +
  labs(x="", y="", title="Dual value (WSLS)") +
  scale_y_continuous(limits = limits, breaks = breaks) +
  scale_color_identity() +
  theme_pubr(base_size = 10, legend = "none") +
  theme(strip.background = element_blank()) +
  coord_flip() -> p1

tmp %>% 
  filter(strategy == "Single value") %>% 
  mutate(
    color = ifelse(strategy == "Dual value (WSLS)", "chartreuse4", "black")) %>%
  ggplot(aes(x=agent, y=total_R/num_episodes, color=color)) +
  geom_boxplot(outlier.size = 0.2, width=0.5) +
  geom_hline(aes(yintercept=wsls_R/num_episodes), 
             color="chartreuse4",
             size=0.5) +
  geom_hline(aes(yintercept=random_R/num_episodes), 
             color="darkgrey",
             size=0.5) +
  labs(x="", y="Reward", title="Single value") +
  scale_y_continuous(limits = limits, breaks = breaks) +
  scale_color_identity() +
  theme_pubr(base_size = 10, legend = "none") +
  theme(strip.background = element_blank()) +
  coord_flip() -> p2

# ---
p1 /  p2  + 
  plot_layout(heights = c(0.2, 0.8)) +
  plot_annotation(title = "Task 7 - Unexpected change", 
                  theme = theme_pubr(base_size = 12, legend = "none"))
```

## Median/MAD
```{r, fig.width=4.5, fig.height=3.5}
result_task7 %>%  
  # filter(agent != "Random") %>%
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R),
            total_E = last(total_E),
            total_value = last(total_R) + last(total_E),
            total_regret = last(total_regret)) %>% 
  ungroup() -> tmp

tmp %>% 
  group_by(strategy, agent) %>% 
  summarise(median_R = median(total_R), 
            var_R = mad(total_R),
            median_E = median(total_E), 
            var_E = mad(total_E),
            median_total_value = median(total_value), 
            var_total_value = mad(total_value),
            median_regret = median(total_regret),
            var_regret = mad(total_regret)) %>% 
  ungroup() -> tmp

# Med R for curiosity
wsls_R <- median((filter(tmp, strategy == "Dual value (WSLS)"))$median_R)
random_R <- median((filter(tmp, strategy == "Random"))$median_R)

tmp %>% 
  filter(strategy == "Dual value (WSLS)") %>% 
  mutate(
    color = ifelse(strategy == "Dual value (WSLS)", "chartreuse4", "black")) %>%
  ggplot(aes(x=agent, y=median_R/num_episodes, color=color)) +
  geom_point(size=2.5, alpha=0.8) +
  geom_linerange(aes(
    ymin=(median_R+var_R)/num_episodes, 
    ymax=(median_R-var_R)/num_episodes), 
    alpha=0.4) +
  geom_hline(aes(yintercept=wsls_R/num_episodes), 
             color="chartreuse4",
             size=0.5) +
  geom_hline(aes(yintercept=random_R/num_episodes), 
             color="grey",
             size=0.5) +
  labs(x="", y="", title="Dual value (WSLS)") +
  scale_y_continuous(limits = limits, breaks = breaks) +
  scale_color_identity() +
  theme_pubr(base_size = 10, legend = "none") +
  theme(strip.background = element_blank()) +
  coord_flip() -> p1

tmp %>% 
  filter(strategy == "Single value") %>% 
  mutate(
    color = ifelse(strategy == "Dual value (WSLS)", "chartreuse4", "black")) %>%
  ggplot(aes(x=agent, y=median_R/num_episodes, color=color)) +
  geom_point(size=2, alpha=0.8) +
  geom_linerange(aes(
    ymin=(median_R+var_R)/num_episodes, 
    ymax=(median_R-var_R)/num_episodes), 
    alpha=0.4) +
  geom_hline(aes(yintercept=wsls_R/num_episodes), 
             color="chartreuse4",
             size=0.5) +
  geom_hline(aes(yintercept=random_R/num_episodes), 
             color="grey",
             size=0.5) +
  labs(x="", y="Reward", title="Single value") +
  scale_y_continuous(limits = limits, breaks = breaks) +
  scale_color_identity() +
  theme_pubr(base_size = 10, legend = "none") +
  theme(strip.background = element_blank()) +
  coord_flip() -> p2

# ---
p1 /  p2  + 
  plot_layout(heights = c(0.15, 0.85)) +
  plot_annotation(title = "Task 7 - Unexpected change", 
                  theme = theme_pubr(base_size = 12, legend = "none"))
```


# Actions
```{r, fig.width=8, fig.height=6}
# Pick an exp to show actions for
r <- 1

# Plot actions
result_task7 %>%
  filter(agent != "Random") %>%
  filter(run == r) %>%
  ggplot(aes(x = global_step, y = action + 1)) + #, color=factor(policy))) +
  geom_point(size = 0.1, alpha = 0.9) +
  geom_line(size = 0.1) +
  labs(x = "Time", y = "Arm") +
  scale_x_continuous(limits = c(0, num_episodes + (num_episodes * .1)),
                     breaks = c(0, num_episodes)) +
  scale_color_manual("", values = c("darkslategray4", "chartreuse4", "black")) +
  facet_grid(param ~ agent) +
  theme_pubr(base_size = 10, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(.5, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(legend.box.background = element_rect(colour = "black", size = 1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text.y = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks.y = element_blank()) +
  theme(strip.text.x = element_text(hjust = 0)) +
  plot_annotation(subtitle = "Exploration strategies (Task 7)",
                  theme = theme_pubr(base_size = 10, legend = "none")) 
```

# Rewards
```{r, fig.width=4.2, fig.height=4.2}
result_task7 %>%
  filter(agent != "Random") %>%
  filter(global_step > 10) %>%
  ggplot(aes(
    x = global_step,
    y = total_R / global_step,
    group = interaction(param, run)
  )) +
  geom_line(size = 0.1, alpha = 0.8) +
  labs(x = "Time", y = "Avg. reward", subtitle = "Value timecourse (Task 7)") +
  scale_x_continuous(limits = c(0, num_episodes + (num_episodes * .1)),
                     breaks = c(0, num_episodes)) +
  scale_y_continuous(limits = c(-.1, 1.1), breaks = c(0, 1)) +
  facet_wrap(agent ~ .) +
  theme_pubr(base_size = 10, legend = "none") +
  theme(panel.spacing = unit(.2, "lines")) +
  theme(strip.text.y = element_text(angle = 0, hjust = -.1)) +
  theme(strip.background = element_blank()) 
```
  