---
title: "Tasks - illustration"
output: html_notebook
---

# Library
```{r, message=FALSE}
library(zoo)
library(ggplot2)
library(ggpubr)
library(patchwork)
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
# library(MASS) 
library(scales)
library(patchwork)
options(scipen=1000000)

# Load load_result and other helpful functions
source("utils.R")

# --- Main path to all data ---
data_path <- "/Volumes/Data/infomercial/data"
```

# Shared art
```{r}
# arrow 
arrow <- data.frame(x=0, xend=2, y=0.5, yend=0.5)
arrow %>% 
ggplot(aes(x=x, y=y, xend=xend, yend = yend)) +
  geom_segment(
    lineend = "butt", linejoin = "mitre",
    size = 1, arrow = arrow(length = unit(0.2, "inches"))
  ) +
  labs(x="", y="") +
  theme_pubr(base_size = 8, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(axis.text = element_blank()) +
  theme(axis.text = element_blank()) +
  theme(axis.ticks = element_blank()) +
  theme(strip.text = element_blank()) +
  theme(axis.line = element_blank()) -> a1
```

# Task - info forced choice
```{r, fig.width=1, fig.height=1}
info <- data.frame(
  choice=c(1,2,3,4,1,2,3,4),
  color=c(1,1,1,1,2,2,2,2),
  prob=c(0.99, 0.5, 0.99, 0.01, 0.01, 0.5, 0.01, 0.99))

# ------------------------------------------------------------------------
# Choice
info %>% 
  ggplot(aes(label=choice)) + 
  geom_text(x=0.5, y=0.5) +
  labs(x="", y="", title="Choose?") +
  facet_wrap(choice~., ncol=1) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(strip.text = element_blank()) +
  theme(axis.line = element_blank()) +
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank())+
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1)) -> p1

# Result
info %>% 
  ggplot(aes(x=factor(color), y=prob, fill=factor(color))) + 
  geom_bar(width=0.5, stat="identity") +
  scale_y_continuous(limits=c(0,1.05), breaks = c(0, 1)) +
  scale_fill_manual(values=c("yellow", "blue")) +
  labs(x="", y="", title="Stimulus") +
  facet_wrap(choice~., ncol=1) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(axis.text.x = element_blank()) +
  # theme(axis.text.y = element_blank()) +
  theme(axis.ticks.x = element_blank()) +
  theme(strip.text = element_blank()) +
  theme(axis.line = element_blank()) +
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank()) +
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1)) -> p2


# ------------------------------------------------------------------------
p1 + a1 + p2 + 
  plot_layout(widths=c(0.3, 0.3, 0.3)) +
  plot_annotation(title = "Task 0 - Information")
```

# Task - classic forced choice
```{r, fig.width=0.9, fig.height=1.2}
best <- 2
best_choice = rep(0, 4)
best_choice[best] <- 1

classic <- data.frame(
  best=best_choice,
  choice=1:4,
  payout=c(0.2, 0.8, 0.2, 0.2))

# ------------------------------------------------------------------------
# Choice
classic %>% 
  ggplot(aes(label=choice)) + 
  geom_text(x=0.5, y=0.5) +
  labs(x="", y="", title="Choose?") +
  facet_wrap(choice~., ncol=1) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(strip.text = element_blank()) +
  theme(axis.line = element_blank()) +
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank())+
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1)) -> p1

# Result
classic %>% 
  ggplot(aes(x=1, y=payout, fill=factor(best))) + 
  geom_bar(width=0.5, alpha=1, stat="identity") +
  lims(x=c(0, 2)) +
  scale_y_continuous(limits=c(0,1.1), breaks = c(0, 1)) +
  scale_fill_manual(values=c("darkgrey", "black")) +
  labs(x="", y="", title="Average\npayout") +
  facet_wrap(choice~., ncol=1) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(axis.text.x = element_blank()) +
  # theme(axis.text.y = element_blank()) +
  theme(axis.ticks.x = element_blank()) +
  theme(strip.text = element_blank()) +
  theme(axis.line = element_blank()) +
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank()) +
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1)) -> p2


# ------------------------------------------------------------------------
p1 + a1 + p2 + 
  plot_layout(widths=c(0.3, 0.3, 0.3)) +
  plot_annotation(title = "Task 1 - Classic")
```

# Task - sparse forced choice
```{r, fig.width=0.9, fig.height=2}
best <- 8
best_choice = rep(0, 10)
best_choice[best] <- 1

sparse <- data.frame(
  choice=1:10,
  best=best_choice,
  payout=c(0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.02, 0.01, 0.01))

# ------------------------------------------------------------------------
# Choice
sparse %>% 
  ggplot(aes(label=choice)) + 
  geom_text(x=0.5, y=0.5) +
  labs(x="", y="", title="Choose?") +
  facet_wrap(choice~., ncol=1) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(strip.text = element_blank()) +
  theme(axis.line = element_blank()) +
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank())+
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1)) -> p1

# Result
sparse %>% 
  ggplot(aes(x=1, y=payout, label=payout, color=factor(best))) + 
  geom_bar(width=0.5, fill="black", alpha=1, stat="identity") +
  geom_text(size=2, position = position_stack(vjust = 20)) +
  lims(x=c(0, 2)) +
  scale_y_continuous(limits=c(0,1.1), breaks = c(0, 1)) +
  scale_color_manual(values=c("darkgrey", "black")) +
  labs(x="", y="", title="Average\npayout") +
  facet_wrap(choice~., ncol=1) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(axis.text.x = element_blank()) +
  # theme(axis.text.y = element_blank()) +
  theme(axis.ticks.x = element_blank()) +
  theme(strip.text = element_blank()) +
  theme(axis.line = element_blank()) +
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank()) +
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1)) -> p2


# ------------------------------------------------------------------------
p1 + a1 + p2 + 
  plot_layout(widths=c(0.3, 0.3, 0.3)) + 
  plot_annotation(title = "Task 2 - Sparse")
```
# Task - large forced choice
```{r, fig.width=4.4, fig.height=2.2}
best <- 55
payout = runif(121, 0.2, 0.6)
payout[best] <- 0.8

best_choice = rep(0, 121)
best_choice[best] <- 1

large <- data.frame(
  choice=1:121,
  best=best_choice,
  payout=payout)

# ------------------------------------------------------------------------
# Choice
large %>% 
  ggplot(aes(label=choice)) + 
  geom_text(x=0.5, y=0.5) +
  labs(x="", y="", title="Choose?") +
  facet_wrap(choice~., ncol=11) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(strip.text = element_blank()) +
  theme(axis.line = element_blank()) +
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank())+
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1)) -> p1

# Result
large %>% 
  ggplot(aes(x=1, y=payout, fill=factor(best_choice))) + 
  geom_bar(width=0.5, alpha=1, stat="identity") +
  lims(x=c(0, 2)) +
  scale_y_continuous(limits=c(0,1.1), breaks = c(0, 1)) +
  scale_fill_manual(values=c("darkgrey", "black")) +
  labs(x="", y="", title="Payout") +
  facet_wrap(choice~., ncol=11) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(axis.text.x = element_blank()) +
  # theme(axis.text.y = element_blank()) +
  theme(axis.ticks.x = element_blank()) +
  theme(strip.text = element_blank()) +
  theme(axis.line = element_blank()) +
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank()) +
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1)) +
  plot_annotation(title="Task 3 - Large", subtitle = "Average payout") -> p2

# ------------------------------------------------------------------------
p1 + a1 + p2 + 
  plot_layout(widths=c(0.45, 0.1, 0.45)) + 
  plot_annotation(title = "Task 3 - Large")
```

# Task - Deception
```{r, fig.width=1.5, fig.height=2}
best <- 8
best_choice = rep(0, 10)
best_choice[best] <- 1

# -------------------------------------------------------
# p(R)
deception_prob <- data.frame(
  choice=1:10,
  best=best_choice,
  prob=c(0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.8, 0.2, 0.2))

# -------------------------------------------------------
# parts of
# R values in time
std_R <- rep(1, 200)
deception_R <- c(
    rev(seq(0,1,.1)), 
    seq(0,0.9,.1), 
    rep(1,10), 
    rep(1,169))

# build df
deception_value <- NULL
for(n in 1:10){
  if (n == best) {
    R = deception_R
    b <- 1
  } else {
    R = std_R
    b <- 0
  }
  tmp <- data.frame(
    time=1:200,
    choice=rep(n, 200),
    value=R,
    best=rep(b, 200)
  )
    
  deception_value <- bind_rows(tmp, deception_value)
}

# -------------------------------------------------------

# Avg payout in time
deception_payout <- data.frame(
  choice=1:10,
  best=best_choice,
  payout=c(0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.2, 0.2))

# -------------------------------------------------------
# Build

# Choice
deception_prob %>% 
  ggplot(aes(label=choice)) + 
  geom_text(x=0.5, y=0.5) +
  labs(x="", y="", title="Choose?") +
  facet_wrap(choice~., ncol=1) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(strip.text = element_blank()) +
  theme(axis.line = element_blank()) +
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank())+
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1)) -> p1

# Prob
deception_prob %>% 
  ggplot(aes(x=1, y=prob, fill=factor(best))) + 
  geom_bar(width=0.5, alpha=1, stat="identity") +
  lims(x=c(0, 2)) +
  scale_y_continuous(limits=c(0,1.1), breaks = c(0, 1)) +
  scale_fill_manual(values=c("darkgrey", "black")) +
  labs(x="", y="", title="Reward\nprob.") +
  facet_wrap(choice~., ncol=1) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(axis.text.x = element_blank()) +
  # theme(axis.text.y = element_blank()) +
  theme(axis.ticks.x = element_blank()) +
  theme(strip.text = element_blank()) +
  theme(axis.line = element_blank()) +
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank()) +
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1)) -> p2

# value
deception_value %>% 
  ggplot(aes(x=time, y=value, color=factor(best), group=choice)) + 
  geom_line(size=0.6, alpha=1) +
  scale_x_continuous(limits=c(-20,220), breaks = c(0, 200)) +
  scale_y_continuous(limits=c(0,1.2), breaks = c(0, 1)) +
  scale_color_manual(values=c("darkgrey", "black")) +
  labs(x="Time", y="", title="Reward\nvalue") +
  facet_wrap(choice~., ncol=1) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  # theme(axis.text.x = element_blank()) +
  # theme(axis.text.y = element_blank()) +
  # theme(axis.ticks.x = element_blank()) +
  theme(strip.text = element_blank()) +
  theme(axis.line = element_blank()) +
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank()) +
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1)) -> p3

# Prob
deception_payout %>% 
  ggplot(aes(x=1, y=payout, fill=factor(best))) + 
  geom_bar(width=0.5, alpha=1, stat="identity") +
  lims(x=c(0, 2)) +
  scale_y_continuous(limits=c(0,1.1), breaks = c(0, 1)) +
  scale_fill_manual(values=c("darkgrey", "black")) +
  labs(x="", y="", title="Average\npayout") +
  facet_wrap(choice~., ncol=1) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(axis.text.x = element_blank()) +
  # theme(axis.text.y = element_blank()) +
  theme(axis.ticks.x = element_blank()) +
  theme(strip.text = element_blank()) +
  theme(axis.line = element_blank()) +
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank()) +
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1)) -> p4

# ------------------------------------------------------------------------
p1 + a1 + p3 + p2 + p4 +
  plot_layout(widths=c(0.2, 0.2, 0.2, 0.2, 0.2)) + 
  plot_annotation(title = "Task 4 - Deception")
```

# Task - Distraction forced choise
```{r, fig.width=1.2, fig.height=2.1}
distraction_stim <- data.frame(
  choice=c(1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10),
  color=c(1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2),
  prob=rep(0.5, 20))

best <- 8
best_choice = rep(0, 10)
best_choice[best] <- 1

distraction_payout <- data.frame(
  choice=1:10,
  best=best_choice,
  payout=c(0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.8, 0.2, 0.2))

# ------------------------------------------------------------------------
# Choice
distraction_stim %>% 
  ggplot(aes(label=choice)) + 
  geom_text(x=0.5, y=0.5) +
  labs(x="", y="", title="Choose?") +
  facet_wrap(choice~., ncol=1) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(strip.text = element_blank()) +
  theme(axis.line = element_blank()) +
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank())+
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1)) -> p1

# Result stim
distraction_stim %>% 
  ggplot(aes(x=factor(color), y=prob, fill=factor(color))) + 
  geom_bar(width=0.5, stat="identity") +
  scale_y_continuous(limits=c(0,1.05), breaks = c(0, 1)) +
  scale_fill_manual(values=c("yellow", "blue")) +
  labs(x="", y="", title="Stimulus") +
  facet_wrap(choice~., ncol=1) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(axis.text.x = element_blank()) +
  # theme(axis.text.y = element_blank()) +
  theme(axis.ticks.x = element_blank()) +
  theme(strip.text = element_blank()) +
  theme(axis.line = element_blank()) +
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank()) +
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1)) -> p2

# Result reward
distraction_payout %>% 
  ggplot(aes(x=1, y=payout, label=payout, fill=factor(best))) + 
  geom_bar(width=0.5, alpha=1, stat="identity") +
  lims(x=c(0, 2)) +
  scale_y_continuous(limits=c(0,1.1), breaks = c(0, 1)) +
  scale_fill_manual(values=c("darkgrey", "black")) +
  labs(x="", y="", title="Average\npayout") +
  facet_wrap(choice~., ncol=1) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(axis.text.x = element_blank()) +
  # theme(axis.text.y = element_blank()) +
  theme(axis.ticks.x = element_blank()) +
  theme(strip.text = element_blank()) +
  theme(axis.line = element_blank()) +
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank()) +
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1)) -> p3

# ------------------------------------------------------------------------
p1 + a1 + p2 + p3 +
  plot_layout(widths=c(0.25, 0.25, 0.25, 0.25)) + 
  plot_annotation(title = "Task 5 - Distraction")
```
