---
title: "Task 4 - DeceptiveBanditOneHigh10 - Top10 results"
output: html_notebook
---

# Library
```{r, message=FALSE}
library(zoo)
library(ggplot2)
library(ggpubr)
library(patchwork)
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
# library(MASS) 
library(scales)
library(patchwork)
options(scipen=1000000)

# Load load_result and other helpful functions
source("utils.R")

# --- Main path to all data ---
data_path <- "~/Code/infomercial/data"
```

# Load data
## Vars
```{r, message=FALSE, warning=FALSE}
# -------------------------------------------------------------
task_name <- "DeceptiveBanditOneHigh10"
task_code <- 4
num_episodes <- 200

# Set axis
limits <- c(0, 0.4)
breaks <- c(0.0, 0.2, 0.4)

# The overestimate due to E0
num_arms <- 10
E_bias <- log(num_arms) * num_arms 

exp_names <- c("exp449",
               # "exp450", 
               # "exp451", 
               "exp453", 
               "exp518",
               "exp452", 
               "exp517", 
               "exp520", 
               "exp519", 
               "exp543")
```

## Load
```{r, message=FALSE, warning=FALSE}
agent_names <- c(
  "Curiosity (Info.)", 
  # "Random/Greedy", 
  # "Decay/Greedy", 
  "Random",
  "Reward", 
  "Reward+Info.", 
  "Reward+Novelty", 
  "Reward+Entropy", 
  "Reward+EB",
  "Reward+UCB")

class_names <- c(
  "WSLS", 
  # "Random",
  # "Random",
  "Random",
  "Reward",
  "Mixed",
  "Mixed",
  "Mixed",
  "Mixed",
  "Mixed",
  "Mixed"
)


file_names <- c("action", 
                "total_R",
                "total_E",
                "policy",
                "regret",
                "total_regret")

result_task4 <- NULL
for(i in 1:length(exp_names)){
  exp_name <- exp_names[i]
  agent_name <- agent_names[i]
  class_name <- class_names[i]
  if (agent_name == "Random"){
    param_codes <- c(0)
    run_codes <- 1:100
  } else{
    param_codes <- 0:9
    run_codes <- 1:10
  }
  
  tmp <- load_result(
    exp_name, param_codes, run_codes, file_names, n_max=num_episodes+1)
  
  tmp %>% 
    filter(global_step <= num_episodes) -> tmp
  tmp$exp <- exp_name
  tmp$agent <- agent_name
  tmp$task <- task_name
  tmp$task_code <- task_code
  tmp$strategy <- class_name
  tmp$num_episodes <- num_episodes
  
  result_task4 <- bind_rows(result_task4, tmp)
}

# ----------------------------------------------------------------------------
# post-process
# Force order
result_task4$agent <- factor(result_task4$agent, levels=rev(agent_names))

# Remove E_bias
result_task4$total_E <- result_task4$total_E - E_bias
result_task4$total_E[result_task4$total_E < 0] <- 0
```


# Summary, by strategy
## Boxplot
```{r, fig.width=4.5, fig.height=3.5}
result_task4 %>% 
  # filter(agent != "Random") %>%
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R),
            total_E = last(total_E),
            total_regret = last(total_regret),
            global_step=last(global_step)) %>% 
  ungroup() %>% 
  ungroup() -> tmp


# Med R for curiosity
wsls_R <- median((filter(tmp, strategy == "WSLS"))$total_R)
random_R <- median((filter(tmp, strategy == "Random"))$total_R)

tmp %>% 
  filter(strategy == "WSLS") %>% 
  mutate(
    color = ifelse(strategy == "WSLS", "chartreuse4", "black")) %>%
  ggplot(aes(x=agent, y=total_R, color=color)) +
  geom_boxplot(outlier.size = 0.2, width=0.5) +
  geom_hline(aes(yintercept=random_R), 
             color="darkgrey",
             size=0.5) +
  labs(x="", y="", title="WSLS") +
  # scale_y_continuous(limits = limits, breaks = breaks) +
  scale_color_identity() +
  theme_pubr(base_size = 10, legend = "none") +
  theme(strip.background = element_blank()) +
  coord_flip() -> p1

tmp %>% 
  filter(strategy == "Mixed") %>% 
  mutate(
    color = ifelse(strategy == "WSLS", "chartreuse4", "black")) %>%
  ggplot(aes(x=agent, y=total_R, color=color)) +
  geom_boxplot(outlier.size = 0.2, width=0.5) +
  geom_hline(aes(yintercept=wsls_R), 
             color="chartreuse4",
             size=0.5) +
  geom_hline(aes(yintercept=random_R), 
             color="darkgrey",
             size=0.5) +
  labs(x="", y="Reward", title="Mixed") +
  # scale_y_continuous(limits = limits, breaks = breaks) +
  scale_color_identity() +
  theme_pubr(base_size = 10, legend = "none") +
  theme(strip.background = element_blank()) +
  coord_flip() -> p2

# ---
p1 /  p2  + 
  plot_layout(heights = c(0.2, 0.8)) +
  plot_annotation(title = "Task 4 - Deception", 
                  theme = theme_pubr(base_size = 12, legend = "none"))
```
## Dist
```{r, fig.width=2.5, fig.height=6}
result_task4 %>% 
  # filter(agent != "Random") %>%
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R),
            total_E = last(total_E),
            total_regret = last(total_regret)) %>% 
  ungroup() -> tmp

# Medum
wsls_R <- median((filter(tmp, strategy == "WSLS"))$total_R)

tmp %>% 
  mutate(
    fill = ifelse(strategy == "WSLS", "chartreuse4", "black")) %>% 
  ggplot(aes(x=total_R/num_episodes, fill=fill)) +
  geom_density(alpha=1, color=NA) +
  geom_vline(aes(xintercept=wsls_R/num_episodes), 
             color="chartreuse4",
             size=0.5) +
  scale_fill_identity() +
  labs(x="Avg. reward", y="Count") +
  facet_grid(agent~.) +
  theme_pubr(base_size = 10, legend = "none") +
  theme(panel.spacing = unit(.5, "lines")) +
  theme(strip.text.y = element_text(angle = 0, hjust = -.1)) +
  theme(strip.background = element_blank()) 
```

## Jitter
```{r, fig.width=4, fig.height=3} 
result_task4 %>% 
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R)) %>% 
  ungroup() %>% 
  ggplot(aes(x=agent, y=total_R)) +
  geom_jitter(width = 0.4, size=0.2, alpha=0.4) +
  stat_summary(fun.y = mean, color="goldenrod3") +
  stat_summary(fun.y = median, color="firebrick3") +
  labs(x="", y="Total reward") +
  theme_pubr(base_size = 10, legend = "none") +
  theme(panel.spacing = unit(.5, "lines")) +
  theme(strip.text.y = element_text(angle = 0, hjust = -.1)) +
  theme(strip.background = element_blank()) +
  coord_flip()
```

## Median/MAD
```{r, fig.width=4.5, fig.height=2}
result_task4 %>%  
  # filter(agent != "Random") %>%
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R),
            total_E = last(total_E),
            total_value = last(total_R) + last(total_E),
            total_regret = last(total_regret)) %>% 
  ungroup() -> tmp

tmp %>% 
  group_by(strategy, agent) %>% 
  summarise(median_R = median(total_R), 
            var_R = mad(total_R),
            median_E = median(total_E), 
            var_E = mad(total_E),
            median_total_value = median(total_value), 
            var_total_value = mad(total_value),
            median_regret = median(total_regret),
            var_regret = mad(total_regret)) %>% 
  ungroup() -> tmp

# Med R for curiosity
wsls_R <- median((filter(tmp, strategy == "WSLS"))$median_R)
random_R <- median((filter(tmp, strategy == "Random"))$median_R)

tmp %>% 
  # filter(strategy == "WSLS") %>% 
  mutate(
    color = ifelse(strategy == "WSLS", "chartreuse4", "black")) %>%
  ggplot(aes(x=agent, y=median_R/num_episodes, color=color)) +
  geom_point(size=2.5, alpha=0.8) +
  geom_linerange(aes(
    ymin=(median_R+var_R)/num_episodes, 
    ymax=(median_R-var_R)/num_episodes), 
    alpha=0.4) +
  geom_hline(aes(yintercept=wsls_R/num_episodes), 
             color="chartreuse4",
             size=0.5) +
  geom_hline(aes(yintercept=random_R/num_episodes), 
             color="grey",
             size=0.5) +
  labs(x="", y="Reward", title = "Performance") +
  scale_y_continuous(limits = limits, breaks = breaks) +
  scale_color_identity() +
  theme_pubr(base_size = 10, legend = "none") +
  theme(strip.background = element_blank()) +
  coord_flip() -> p1

p1 
```

## MAD
```{r, fig.width=4.5, fig.height=2}
result_task4 %>%  
  # filter(agent != "Random") %>%
  group_by(strategy, agent, param, run) %>% 
  summarise(total_R = last(total_R)) %>% 
  ungroup() %>% 
  group_by(strategy, agent) %>% 
  summarise(var_R = mad(total_R)) %>% 
  ungroup() -> tmp

# Med R for curiosity
wsls_R <- median((filter(tmp, strategy == "WSLS"))$var_R)
random_R <- median((filter(tmp, strategy == "Random"))$var_R)

tmp %>% 
  # filter(strategy == "WSLS") %>% 
  mutate(
    color = ifelse(strategy == "WSLS", "chartreuse4", "black")) %>%
  ggplot(aes(x=agent, y=var_R/num_episodes, color=color)) +
  geom_point(size=2.5, alpha=0.8) +
  geom_hline(aes(yintercept=wsls_R/num_episodes), 
             color="chartreuse4",
             size=0.5) +
  geom_hline(aes(yintercept=random_R/num_episodes), 
             color="grey",
             size=0.5) +
  labs(x="", y="Reward deviance", title="Consistency") +
  # scale_y_continuous(limits = c(0.0, 0.10), breaks = c(0.0, 0.05,0.10)) +
  scale_color_identity() +
  theme_pubr(base_size = 10, legend = "none") +
  theme(strip.background = element_blank()) +
  coord_flip() 
```

# Actions
```{r, fig.width=8, fig.height=6}
# Pick an exp to show actions for
param_n <- 4

best_arm <- 8
result_task4 -> tmp
tmp$best <- FALSE
tmp$best[tmp$action == best_arm] <- TRUE

# Plot actions
tmp %>%
  filter(agent != "Random") %>%
  filter(param == param_n) %>%
  ggplot(aes(x = global_step, y = action + 1, color=best)) + #, color=factor(policy))) +
  geom_point(size = 0.1, alpha = 0.9) +
  geom_line(size = 0.1) +
  labs(x = "Time", y = "Action") +
  scale_x_continuous(limits = c(0, num_episodes + (num_episodes * .1)),
                     breaks = c(0, num_episodes)) +
  scale_color_manual("", values = c("black", "darkorange4")) +
  facet_grid(run ~ agent) +
  theme_pubr(base_size = 10) +
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(.5, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.box.background = element_rect(colour = "black", size = 1)) +
  theme(plot.title = element_text(size = 6)) +
  theme(strip.text.y = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks.y = element_blank()) +
  theme(strip.text.x = element_text(hjust = 0)) +
  plot_annotation(subtitle = "Exploration strategies",
                  theme = theme_pubr(base_size = 10, legend = "right")) 
```
# Rewards
```{r, fig.width=8, fig.height=2}
result_task4 %>%
  filter(agent != "Random") %>%
  filter(global_step > 10) %>%
  ggplot(aes(
    x = global_step,
    y = total_R / global_step,
    group = interaction(param, run)
  )) +
  geom_line(size = 0.1, alpha = 0.8) +
  labs(x = "Time", y = "Reward", title = "Timecourse (Task 4)") +
  scale_x_continuous(limits = c(0, num_episodes + (num_episodes * .1)),
                     breaks = c(0, num_episodes)) +
  # scale_y_continuous(limits = c(-.1, 1.1), breaks = c(0, 1)) +
  facet_grid(.~agent) +
  theme_pubr(base_size = 10, legend = "none") +
  theme(panel.spacing = unit(.2, "lines")) +
  theme(strip.text.y = element_text(angle = 0, hjust = -.1)) +
  theme(strip.background = element_blank()) 
```
  