---
title: "Exp345 - InfoBlueYellow4c, 100 experiments (seeds) with and without initial values in M."
output: html_notebook
---

```{r, message=FALSE}
library(ggplot2)
library(patchwork)
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
library(MASS) 
library(scales)
library(patchwork)
options(scipen=1000000)

kl_divergence <- function(p, q) {
  sum(p * log(p/q))
}
```

# Load data
## Set a main path
```{r}
data_path <- "~/Code/infomercial/data/"
```

## Load
```{r message=FALSE, cache=TRUE}
# ---
exp_name <- "exp345"

actor_names <- c("DeterministicActor", "ThresholdActor", "SoftmaxActor", "RandomActor")
initial_memory <- c("with", "without")
run_codes <- 1:100
file_names <- c("score_E", "action", "p_bests", "regret", "value_E", "ties", "state")

# ---
result345 <- NULL
for (actor in actor_names){
  for (mem in initial_memory){
    for (run in run_codes) {
      runtmp <- read_csv(paste(data_path, 
                           exp_name, 
                           actor,
                           mem,
                           paste("run", run, sep=""), 
                           paste(file_names[1], "csv", sep="."), sep="/"))    
      for (name in file_names[2:7]){
        tmp <- read_csv(paste(data_path, 
                          exp_name, 
                          actor,
                          mem,
                          paste("run", run, sep=""), 
                          paste(name, "csv", sep="."), sep="/"))  
        runtmp[[name]] <- tmp[[name]]
      }
      runtmp$run <- run
      runtmp$memory <- mem
      runtmp$actor <-actor
      runtmp$num_trials <- nrow(tmp)
      result345 <- bind_rows(result345, runtmp)  
    }
  }
}


# ---
rm(tmp, runtmp, run, name)
```

## Summarize
```{r}
result345 %>% 
  filter(value_E < 1) %>% 
  group_by(actor, memory, run) %>% 
  summarise(
    total_E=median(value_E),
    total_regret=median(regret),
    num_steps=max(num_trials)
  ) %>% 
  ungroup() ->
summary345

summary345$actor <- factor(summary345$actor, levels=c("DeterministicActor", "ThresholdActor", "SoftmaxActor", "RandomActor"))
```

# Plot
## steps dist
```{r, fig.height=1.8, fig.width=3.5}
summary345 %>% 
  ggplot(aes(x=num_steps, fill=actor)) +
  geom_histogram(color="black", alpha=1) +
  scale_fill_manual("", values=c("mediumorchid4", "grey", "plum4",  "paleturquoise4")) +
  labs(x="N trials") +
  theme_classic() +
  facet_grid(memory~actor) +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.75, "lines")) +
  theme(strip.text.y = element_text(angle = 0)) -> p1
print(p1)
```
## steps total
```{r, fig.height=1.2, fig.width=1.8}
summary345 %>% 
  ggplot(aes(x=actor, y=num_steps, color=actor)) +
  geom_jitter(size=0.1, alpha=0.9, width=0.2) +
  stat_summary(fun=mean, color="black", alpha=0.9, size=1, shape="|") +
  scale_color_manual("", values=c("mediumorchid4", "grey", "plum4",  "paleturquoise4")) +
  labs(x="", y="N", title="Steps until bored") +
  facet_grid(memory~.) +
  theme_classic() +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.text.y = element_text(angle = 0)) +
  coord_flip() -> p2
print(p2)
```
## value timecourse
```{r, fig.height=1.4, fig.width=6}
result345 %>% 
  ggplot(aes(x=global_step, y=log10(value_E), color=actor, group=interaction(run,actor))) +
  geom_point(alpha=.1, size=0.2) +
  geom_line(alpha=.1, size=0.2) +
  scale_color_manual("", values=c("mediumorchid4", "grey", "plum4",  "paleturquoise4")) +
  labs(x="Step", y="Value") +
  theme_classic() +
  facet_grid(memory~actor) +
  theme(legend.position = "none") + 
  theme(panel.spacing = unit(0.75, "lines")) +
  theme(strip.background = element_blank()) +
  theme(strip.text.y = element_text(angle = 0)) 
```

## value dist
```{r, fig.height=1.8, fig.width=3.5}
summary345 %>% 
  ggplot(aes(x=total_E, fill=actor)) +
  geom_histogram(color="black", alpha=1) +
  scale_fill_manual("", values=c("mediumorchid4", "grey", "plum4",  "paleturquoise4")) +
  labs(x="Average value") +
  theme_classic() +
  facet_grid(memory~actor) +
  theme(legend.position = "none") + 
  theme(panel.spacing = unit(0.75, "lines")) +
  theme(strip.background = element_blank()) +
  theme(strip.text.y = element_text(angle = 0)) ->
  p3
print(p3)
```

## value total
```{r, fig.height=1.2, fig.width=1.8}
summary345 %>% 
  ggplot(aes(x=actor, y=total_E, color=actor)) +
  geom_jitter(size=0.1, alpha=0.9, width=0.2) +
  stat_summary(fun=mean, color="black", alpha=0.9, size=1, shape="|") +
  scale_color_manual("", values=c("mediumorchid4", "grey", "plum4",  "paleturquoise4")) +
  labs(x="", y="E", title="Average value") +
  facet_grid(memory~.) +
  theme_classic() +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(axis.text.y = element_blank()) +
  theme(strip.text.y = element_text(angle = 0)) +
  coord_flip() ->
  p4
print(p4)
```


## Assemble
```{r, fig.height=1.2, fig.width=3}
(p2 + p4)
```