---
title: "Exp348 - 100 experiments, sto v det"
output: html_notebook
---

```{r, message=FALSE}
library(ggplot2)
library(ggpubr)
library(patchwork)
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
library(MASS) 
library(scales)
library(patchwork)
options(scipen=1000000)

kl_divergence <- function(p, q) {
  sum(p * log(p/q))
}
```

# Load data
## Set a main path
```{r}
data_path <- "~/Code/infomercial/data/"
```

## Load
```{r message=FALSE, cache=TRUE}
# ---
exp_name <- "exp348"

actor_names <- c("DeterministicActor", "SoftmaxActor", "RandomActor")
run_codes <- 1:100
file_names <- c("score_E", "action", "p_bests", "regret", "value_E", 
                "ties", "state", "total_E", "total_regret")

# ---
result348 <- NULL
for (actor in actor_names){
  for (run in run_codes) {
    runtmp <- read_csv(paste(data_path, 
                             exp_name, 
                             actor,
                             paste("run", run, sep=""), 
                             paste(file_names[1], "csv", sep="."), sep="/"))    
    for (name in file_names[2:9]){
      tmp <- read_csv(paste(data_path, 
                            exp_name, 
                            actor,
                            paste("run", run, sep=""), 
                            paste(name, "csv", sep="."), sep="/"))  
      runtmp[[name]] <- tmp[[name]]
    }
    runtmp$run <- run
    runtmp$actor <-actor
    runtmp$num_trials <- nrow(tmp)
    result348 <- bind_rows(result348, runtmp)  
  }
}

# ---
rm(tmp, runtmp, run, name)
```

## Summarize
```{r}
# --
Ebias <- 4*1.38

result348 %>% 
  group_by(actor, run) %>% 
  summarise(
    total_E=max(total_E),
    total_regret=max(total_regret),
    value_E=mean(value_E),
    regret=mean(regret),
    num_steps=max(num_trials)
  ) %>% 
  ungroup() ->
summary348

# --
summary348$actor <- factor(summary348$actor, 
                           levels=c("DeterministicActor", "SoftmaxActor", "RandomActor"))
```

# Plot
# Total E examples
```{r, fig.width=2, fig.height=7}
result348 %>% 
  filter(actor != "RandomActor") %>% 
  filter(global_step > 10) %>%
  # filter(run <= 50) %>% 
  ggplot(aes(x=global_step, y=total_E, color=actor)) +
  # geom_point(size=0.6) +
  geom_line(size=.7) +
  labs(x="Time", y="Cumulative value") +
  facet_wrap(.~run, ncol=5) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  scale_color_manual("Search", values=c("mediumorchid4", "paleturquoise4")) +
  theme(panel.spacing = unit(0.5, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "right") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(strip.text.y = element_text(angle = 0)) +
  # theme(strip.text.x = element_blank()) +
  theme(axis.text.x = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks = element_blank()) + 
  theme(legend.key.size = unit(0.2, "cm"))
```

## Action examples
```{r, fig.width=4, fig.height=2}
result348 %>% 
  filter(actor == "DeterministicActor") %>% 
  filter(global_step < 40) %>%
  filter(run <= 40) %>% 
  ggplot(aes(x=global_step, y=action, color=actor)) +
  # geom_point(size=0.2) +
  geom_line(size=0.8) +
  labs(x="Time", y="Choice") +
  facet_wrap(.~run, ncol=5) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  scale_color_manual("Search", values=c("mediumorchid4", "paleturquoise4", "darkgrey")) +
  theme(panel.spacing = unit(0.75, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "right") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(strip.text.y = element_text(angle = 0)) +
  theme(strip.text.x = element_blank()) +
  theme(axis.text.x = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks = element_blank()) + 
  theme(legend.key.size = unit(0.2, "cm"))
```
```{r, fig.width=4, fig.height=2}
result348 %>% 
  filter(actor == "SoftmaxActor") %>% 
  filter(global_step < 40) %>%
  filter(run <= 40) %>% 
  ggplot(aes(x=global_step, y=action, color=actor)) +
  # geom_point(size=0.2) +
  geom_line(size=0.8) +
  labs(x="Time", y="Choice") +
  facet_wrap(.~run, ncol=5) +
  theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  scale_color_manual("Search", values=c("paleturquoise4")) +
  theme(panel.spacing = unit(0.75, "lines")) +
  theme(strip.background = element_blank()) +
  theme(legend.position = "right") +
  theme(legend.box.background = element_rect(colour = "black", size=1)) +
  theme(strip.text.y = element_text(angle = 0)) +
  theme(strip.text.x = element_blank()) +
  theme(axis.text.x = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks = element_blank()) + 
  theme(legend.key.size = unit(0.2, "cm"))
```

## dists - value and steps
```{r,  fig.width=1.4, fig.height=2}
# average value
summary348 %>% 
  ggplot(aes(x=value_E, fill=actor)) +
  # geom_histogram(color=NA, alpha=0.8) +
  geom_density(color=NA, alpha=0.8) +
  scale_fill_manual("", values=c("mediumorchid4", "paleturquoise4", "grey")) +
  labs(x="Average value") +
  theme_classic() +
  theme(legend.position = "none") + 
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.background = element_blank()) +
  theme(strip.text.y = element_text(angle = 0)) ->
  p1

# step
summary348 %>% 
  ggplot(aes(x=num_steps, fill=actor)) +
  # geom_histogram(color=NA, alpha=0.8) +
  geom_density(color=NA, alpha=0.8) +
  scale_fill_manual("", values=c("mediumorchid4", "paleturquoise4", "darkgray")) +
  labs(x="Steps until bored") +
  theme_classic() +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(0.75, "lines")) +
  theme(strip.text.y = element_text(angle = 0)) -> 
  p2

## total value dist
summary348 %>% 
  ggplot(aes(x=total_E, fill=actor)) +
  # geom_histogram(color=NA, alpha=0.8) +
  geom_density(color=NA, alpha=0.8) +
  scale_fill_manual("", values=c("mediumorchid4", "paleturquoise4", "grey")) +
  labs(x="Total value") +
  theme_classic() +
  theme(legend.position = "none") + 
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.background = element_blank()) +
  theme(strip.text.y = element_text(angle = 0)) -> 
  p3

p1 / p2 / p3
```
## jitter = value and steps
```{r, fig.height=2, fig.width=1.6}
# average value
summary348 %>% 
  ggplot(aes(x=actor, y=value_E, color=actor)) +
  geom_jitter(size=0.1, alpha=0.9, width=0.2) +
  stat_summary(fun=mean, color="black", alpha=0.9, size=1, shape="|") +
  scale_colour_manual("", values=c("mediumorchid4", "paleturquoise4", "darkgray")) +
  labs(x="", y="Average value") +
  lims(y=c(0, 0.08)) +
  theme_classic() +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) +
  # theme(axis.text.y = element_blank()) +
  theme(strip.text.y = element_text(angle = 0)) +
  coord_flip() ->
  p1

# steps
summary348 %>% 
  ggplot(aes(x=actor, y=num_steps, color=actor)) +
  geom_jitter(size=0.1, alpha=0.9, width=0.2) +
  stat_summary(fun=mean, color="black", alpha=0.9, size=1, shape="|") +
  scale_colour_manual("", values=c("mediumorchid4", "paleturquoise4", "darkgray")) +
  labs(x="", y="Steps until bored") +
  lims(y=c(0, 320)) +
  theme_classic() +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.text.y = element_text(angle = 0)) +
  coord_flip() -> p2

# total value
summary348 %>% 
  ggplot(aes(x=actor, y=total_E - Ebias, color=actor)) +
  geom_jitter(size=0.1, alpha=0.9, width=0.2) +
  stat_summary(fun=mean, color="black", alpha=0.9, size=1, shape="|") +
  scale_colour_manual("", values=c("mediumorchid4", "paleturquoise4", "darkgray")) +
  labs(x="", y="Total value") +
  lims(y=c(0, 0.5)) +
  theme_classic() +
  theme(legend.position = "none") + 
  theme(strip.background = element_blank()) +
  theme(panel.spacing = unit(1, "lines")) +
  # theme(axis.text.y = element_blank()) +
  theme(strip.text.y = element_text(angle = 0)) +
  coord_flip() ->
  p3

p1 / p2 / p3
```

