---
title: "Exp328-329 - two examples of curiosity bandits"
output: html_notebook
---

```{r, message=FALSE}
library(ggplot2)
library(patchwork)
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
library(MASS) 
library(scales)
library(patchwork)
options(scipen=1000000)

kl_divergence <- function(p, q) {
  sum(p * log(p/q))
}
```

# Load data
## Set a main path
```{r}
data_path <- "~/Code/infomercial/data/"
```

## Loader defs
```{r, message=FALSE}
file_names <- c("score_E", "action", "p_bests", "regret", "value_E", "ties")

exp_name <- "exp328"
result328 <- read_csv(paste(data_path, exp_name, paste(file_names[1], "csv", sep="."), sep="/"))
for(name in file_names[2:6]){
  tmp <- read_csv(paste(data_path, exp_name, paste(name, "csv", sep="."), sep="/"))
  result328[[name]] <- tmp[[name]]
}

exp_name <- "exp329"
result329 <- read_csv(paste(data_path, exp_name, paste(file_names[1], "csv", sep="."), sep="/"))
for(name in file_names[2:6]){
  tmp <- read_csv(paste(data_path, exp_name, paste(name, "csv", sep="."), sep="/"))
  result329[[name]] <- tmp[[name]]
}
```


# Actions
```{r, fig.height=1.4, fig.width=1.2}
result328 %>% 
  ggplot(aes(x=global_step, y=action)) +
  geom_point() + 
  theme_classic() -> p1

result329 %>% 
  ggplot(aes(x=global_step, y=action)) +
  geom_point() + 
  theme_classic() -> p2

p1 / p2
```
```{r, fig.height=1.4, fig.width=0.6}
result328 %>% 
  ggplot(aes(x=action)) +
  geom_histogram() + 
  theme_classic() -> p1

result329 %>% 
  ggplot(aes(x=action)) +
  geom_histogram() + 
  theme_classic() -> p2

p1 / p2
```
## Ties
```{r, fig.height=1.4, fig.width=1.2}
result328 %>% 
  ggplot(aes(x=global_step, y=ties)) +
  geom_point() + 
  theme_classic() -> p1

result329 %>% 
  ggplot(aes(x=global_step, y=ties)) +
  geom_point() + 
  theme_classic() -> p2

p1 / p2
```

# Scores
```{r, fig.height=1.4, fig.width=1.2}
result328 %>% 
  ggplot(aes(x=global_step, y=score_E)) +
  geom_point() + 
  scale_y_log10() +
  theme_classic() -> p1

result329 %>% 
  ggplot(aes(x=global_step, y=score_E)) +
  geom_point() + 
  scale_y_log10() +
  theme_classic() -> p2

p1/p2
```

# Regret
```{r, fig.height=1.4, fig.width=1.2}
result328 %>% 
  ggplot(aes(x=global_step, y=regret)) +
  geom_point() + 
  lims(y=c(0, 0.005)) +
  theme_classic() -> p1

result329 %>% 
  ggplot(aes(x=global_step, y=regret)) +
  geom_point() + 
  lims(y=c(0, 0.005)) +
  theme_classic() -> p2

p1 / p2
```