---
title: "Figures"
output: html_notebook
---

```{r}
library(ggplot2)
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
```

```{r, echo=FALSE, message=FALSE}
data_path <- "~/Code/infomercial/data/"

# Load data
traces <- NULL
total <- NULL
critic <- NULL
bandit <- NULL
bandit_names <- c("BanditOneHigh10-v0", "BanditTwoHigh10-v0", "BanditUniform121-v0", "BanditHardAndSparse10-v0")
for(bandit_name in bandit_names){
  tmp <- read_csv(paste(data_path, "table_traces_", bandit_name, ".csv", sep=""))
  tmp$env <- rep(bandit_name, nrow(tmp))
  traces <- rbind(traces, tmp)
  
  tmp <- read_csv(paste(data_path, "table_total_", bandit_name, ".csv", sep=""))
  tmp$env <- rep(bandit_name, nrow(tmp))
  total <- rbind(total, tmp)
  
  tmp <- read_csv(paste(data_path, "table_critic_", bandit_name, ".csv", sep=""))
  tmp$env <- rep(bandit_name, nrow(tmp))
  critic <- rbind(critic, tmp)
  
  tmp <- read_csv(paste(data_path, "table_bandit_", bandit_name, ".csv", sep=""))
  tmp$env <- rep(bandit_name, nrow(tmp))
  bandit <- rbind(bandit, tmp)
}

# Set agent order

traces$agents <- factor(traces$agents, levels=rev(c("eta", "beta", "softbeta", "epsilon")))
total$agents <- factor(total$agents, levels=rev(c("eta", "beta", "softbeta", "epsilon")))
critic$agents <- factor(critic$agents, levels=rev(c("eta", "beta", "softbeta", "epsilon")))
traces$agents <- factor(traces$agents, levels=rev(c("eta", "beta", "softbeta", "epsilon")))

rm(tmp)
```


# Regret
```{r, fig.width=1.5, fig.height=1.8}
total %>% 
  filter(env == "BanditOneHigh10-v0") %>% 
  group_by(agents, env) %>% 
  summarise(M = median(regrets), SD=mad(regrets)) %>% 
  ggplot(aes(x=agents, y=M, color=agents)) +
  geom_point(alpha=.9) +
  geom_errorbar(aes(ymin=M-SD, ymax=M+SD), width=.1) +
  theme_classic() +
  theme(legend.position="none",
        plot.margin = margin(.2, .5, .2, .2, "cm")) +
  labs(x="Agent", y="Regret") +
  scale_y_continuous(breaks=c(0, 15, 30)) +
  geom_hline(aes(yintercept=min(M)), color="black", size=.2) +
  scale_color_manual(values=rev(c("darkorchid4", "mediumpurple3", "mediumpurple1", "steelblue3"))) +
  coord_flip() -> p1

total %>% 
  filter(env == "BanditTwoHigh10-v0") %>% 
  group_by(agents, env) %>% 
  summarise(M = median(regrets), SD=mad(regrets)) %>% 
  ggplot(aes(x=agents, y=M, color=agents)) +
  geom_point(alpha=.9) +
  geom_errorbar(aes(ymin=M-SD, ymax=M+SD), width=.1) +
  theme_classic() +
  theme(legend.position="none",
        plot.margin = margin(.2, .5, .2, .2, "cm")) +
  geom_hline(aes(yintercept=min(M)), color="black", size=.2) +
  scale_color_manual(values=rev(c("darkorchid4", "mediumpurple3", "mediumpurple1", "steelblue3"))) +
  labs(x="Agent", y="Regret") +
  coord_flip() -> p2

total %>% 
  filter(env == "BanditUniform121-v0") %>% 
  group_by(agents, env) %>% 
  summarise(M = median(regrets), SD=mad(regrets)) %>% 
  ggplot(aes(x=agents, y=M, color=agents)) +
  geom_point(alpha=.9) +
  geom_errorbar(aes(ymin=M-SD, ymax=M+SD), width=.1) +
  theme_classic() +
  theme(legend.position="none",
        plot.margin = margin(.2, .5, .2, .2, "cm")) +
  labs(x="Agent", y="Regret") +
  scale_y_continuous(breaks=c(0, 15000, 30000)) +
  geom_hline(aes(yintercept=min(M)), color="black", size=.2) +
  scale_color_manual(values=rev(c("darkorchid4", "mediumpurple3", "mediumpurple1", "steelblue3"))) +
  coord_flip() -> p3

total %>% 
  filter(env == "BanditHardAndSparse10-v0") %>% 
  group_by(agents, env) %>% 
  summarise(M = median(regrets), SD=mad(regrets)) %>% 
  ggplot(aes(x=agents, y=M, color=agents)) +
  geom_point(alpha=.9) +
  geom_errorbar(aes(ymin=M-SD, ymax=M+SD), width=.1) +
  theme_classic() +
  theme(legend.position="none", 
        plot.margin = margin(.2, .5, .2, .2, "cm")) +
  labs(x="Agent", y="Regret") +
  scale_y_continuous(breaks=c(0, 750, 1500)) +
  geom_hline(aes(yintercept=min(M)), color="black", size=.2) +
  scale_color_manual(values=rev(c("darkorchid4", "mediumpurple3", "mediumpurple1", "steelblue3"))) +
  coord_flip() -> p4

p5 <- textGrob("One winner", vjust=-.2, gp = gpar(fontsize = 10))
p6 <- textGrob("Distractor", vjust=-.2, gp = gpar(fontsize = 10))
p7 <- textGrob("Random 121", vjust=-.2, gp = gpar(fontsize = 10))
p8 <- textGrob("Sparse", vjust=-.2, gp = gpar(fontsize = 10))

plot_grid <- rbind(
  c(1, 1, 1, 1, 5, 5),
  c(2, 2, 2, 2, 6, 6),
  c(3, 3, 3, 3, 7, 7),
  c(4, 4, 4, 4, 8, 8))
  
grid.arrange(p1, p2, p3, p4, p5, p6, p7, p8, layout_matrix=plot_grid)
```

# Total Reward
```{r, fig.width=1.5 , fig.height=1.8}
total %>% 
  filter(env == "BanditOneHigh10-v0") %>% 
  group_by(agents, env) %>% 
  summarise(M = median(total_R), SD=mad(total_R)) %>% 
  ggplot(aes(x=agents, y=M, color=agents)) +
  geom_point(alpha=.9) +
  geom_errorbar(aes(ymin=M-SD, ymax=M+SD), width=.1) +
  theme_classic() +
  theme(legend.position="none",
        plot.margin = margin(.2, .5, .2, .2, "cm")) +
  labs(x="Agent", y=" ") +
  scale_y_continuous(breaks=c(0, 200, 400), limits = c(0, 500)) +
  geom_hline(aes(yintercept=max(M)), color="black", size=.2) +
  scale_color_manual(values=rev(c("darkorchid4", "mediumpurple3", "mediumpurple1", "steelblue3"))) +
  coord_flip() -> p1

total %>% 
  filter(env == "BanditTwoHigh10-v0") %>% 
  group_by(agents, env) %>% 
  summarise(M = median(total_R), SD=mad(total_R)) %>% 
  ggplot(aes(x=agents, y=M, color=agents)) +
  geom_point(alpha=.9) +
  geom_errorbar(aes(ymin=M-SD, ymax=M+SD), width=.1) +
  theme_classic() +
  theme(legend.position="none",
        plot.margin = margin(.2, .5, .2, .2, "cm")) +
  scale_y_continuous(breaks=c(0, 200, 400), limits = c(0, 500)) +
  geom_hline(aes(yintercept=max(M)), color="black", size=.2) +
  scale_color_manual(values=rev(c("darkorchid4", "mediumpurple3", "mediumpurple1", "steelblue3"))) +
  labs(x=" ", y=" ") +
  coord_flip() -> p2

total %>% 
  filter(env == "BanditUniform121-v0") %>% 
  group_by(agents, env) %>% 
  summarise(M = median(total_R), SD=mad(total_R)) %>% 
  ggplot(aes(x=agents, y=M, color=agents)) +
  geom_point(alpha=.9) +
  geom_errorbar(aes(ymin=M-SD, ymax=M+SD), width=.1) +
  theme_classic() +
  theme(legend.position="none",
        plot.margin = margin(.2, .5, .2, .2, "cm")) +
  labs(x=" ", y=" ") +
  ylim(c(0, 100000)) +
  geom_hline(aes(yintercept=max(M)), color="black", size=.2) +
  scale_color_manual(values=rev(c("darkorchid4", "mediumpurple3", "mediumpurple1", "steelblue3"))) +
  coord_flip() -> p3

total %>% 
  filter(env == "BanditHardAndSparse10-v0") %>% 
  group_by(agents, env) %>% 
  summarise(M = median(total_R), SD=mad(total_R)) %>% 
  ggplot(aes(x=agents, y=M, color=agents)) +
  geom_point(alpha=.9) +
  geom_errorbar(aes(ymin=M-SD, ymax=M+SD), width=.1) +
  theme_classic() +
  theme(legend.position="none", 
        plot.margin = margin(.2, .5, .2, .2, "cm")) +
  labs(x=" ", y="Total Reward") +
  scale_y_continuous(breaks=c(0, 1000, 2000), limits = c(0, 2100)) +
  geom_hline(aes(yintercept=max(M)), color="black", size=.2) +
  scale_color_manual(values=rev(c("darkorchid4", "mediumpurple3", "mediumpurple1", "steelblue3"))) +
  coord_flip() -> p4


p5 <- textGrob("One winner", vjust=-.2, gp = gpar(fontsize = 10))
p6 <- textGrob("Distractor", vjust=-.2, gp = gpar(fontsize = 10))
p7 <- textGrob("Random 121", vjust=-.2, gp = gpar(fontsize = 10))
p8 <- textGrob("Sparse", vjust=-.2, gp = gpar(fontsize = 10))


plot_grid <- rbind(
  c(1, 1, 1, 1, 5, 5),
  c(2, 2, 2, 2, 6, 6),
  c(3, 3, 3, 3, 7, 7),
  c(4, 4, 4, 4, 8, 8))
  
grid.arrange(p1, p2, p3, p4, p5, p6, p7, p8, layout_matrix=plot_grid)
```

# P(best)
```{r, fig.width=1.6 , fig.height=1.8}
total %>% 
  filter(env == "BanditOneHigh10-v0") %>% 
  group_by(agents, env) %>% 
  summarise(M = median(p_bests), SD=mad(p_bests)) %>% 
  ggplot(aes(x=agents, y=M, color=agents)) +
  geom_point(alpha=.9) +
  geom_errorbar(aes(ymin=M-SD, ymax=M+SD), width=.1) +
  theme_classic() +
  theme(legend.position="none",
        plot.margin = margin(.2, .5, .2, .2, "cm")) +
  labs(x="Agent", y=" ") +
  ylim(c(0, 1)) +
  geom_hline(aes(yintercept=max(M)), color="black", size=.2) +
  scale_color_manual(values=rev(c("darkorchid4", "mediumpurple3", "mediumpurple1", "steelblue3"))) +
  coord_flip() -> p1

total %>% 
  filter(env == "BanditTwoHigh10-v0") %>% 
  group_by(agents, env) %>% 
  summarise(M = median(p_bests), SD=mad(p_bests)) %>% 
  ggplot(aes(x=agents, y=M, color=agents)) +
  geom_point(alpha=.9) +
  geom_errorbar(aes(ymin=M-SD, ymax=M+SD), width=.1) +
  theme_classic() +
  theme(legend.position="none",
        plot.margin = margin(.2, .5, .2, .2, "cm")) +
  ylim(c(0, 1)) +
  geom_hline(aes(yintercept=max(M)), color="black", size=.2) +
  scale_color_manual(values=rev(c("darkorchid4", "mediumpurple3", "mediumpurple1", "steelblue3"))) +
  labs(x=" ", y=" ") +
  coord_flip() -> p2

total %>% 
  filter(env == "BanditUniform121-v0") %>% 
  group_by(agents, env) %>% 
  summarise(M = median(p_bests), SD=mad(p_bests)) %>% 
  ggplot(aes(x=agents, y=M, color=agents)) +
  geom_point(alpha=.9) +
  geom_errorbar(aes(ymin=M-SD, ymax=M+SD), width=.1) +
  theme_classic() +
  theme(legend.position="none",
        plot.margin = margin(.2, .5, .2, .2, "cm")) +
  labs(x=" ", y=" ") +
  ylim(c(0, 1)) +
  geom_hline(aes(yintercept=max(M)), color="black", size=.2) +
  scale_color_manual(values=rev(c("darkorchid4", "mediumpurple3", "mediumpurple1", "steelblue3"))) +
  coord_flip() -> p3

total %>% 
  filter(env == "BanditHardAndSparse10-v0") %>% 
  group_by(agents, env) %>% 
  summarise(M = median(p_bests), SD=mad(p_bests)) %>% 
  ggplot(aes(x=agents, y=M, color=agents)) +
  geom_point(alpha=.9) +
  geom_errorbar(aes(ymin=M-SD, ymax=M+SD), width=.1) +
  theme_classic() +
  theme(legend.position="none", 
        plot.margin = margin(.2, .5, .2, .2, "cm")) +
  labs(x=" ", y="P(best)") +
  ylim(c(0, 1)) +
  geom_hline(aes(yintercept=max(M)), color="black", size=.2) +
  scale_color_manual(values=rev(c("darkorchid4", "mediumpurple3", "mediumpurple1", "steelblue3"))) +
  coord_flip() -> p4


p5 <- textGrob("One winner", vjust=-.2, gp = gpar(fontsize = 10))
p6 <- textGrob("Distractor", vjust=-.2, gp = gpar(fontsize = 10))
p7 <- textGrob("Random 121", vjust=-.2, gp = gpar(fontsize = 10))
p8 <- textGrob("Sparse", vjust=-.2, gp = gpar(fontsize = 10))


plot_grid <- rbind(
  c(1, 1, 1, 1, 5, 5),
  c(2, 2, 2, 2, 6, 6),
  c(3, 3, 3, 3, 7, 7),
  c(4, 4, 4, 4, 8, 8))
  
grid.arrange(p1, p2, p3, p4, p5, p6, p7, p8, layout_matrix=plot_grid)
```